// DESIGN SPEC — generated by Designer agent // Preserve component structure and accessibility attributes.
#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@class CarrierSelectionViewController;

@interface PXTrustedCarrierOption : NSObject

@property (nonatomic, copy, readonly) NSString *stableIdentifier;
@property (nonatomic, copy, readonly) NSString *countryName;
@property (nonatomic, copy, readonly) NSString *carrierName;

- (instancetype)initWithStableIdentifier:(NSString *)stableIdentifier
                             countryName:(NSString *)countryName
                             carrierName:(NSString *)carrierName;

@end

@protocol CarrierSelectionViewControllerDelegate <NSObject>

- (void)carrierSelectionViewController:(CarrierSelectionViewController *)viewController
         didCommitSelectedCarrierIDs:(NSSet<NSString *> *)selectedCarrierIDs;

@optional
- (BOOL)carrierSelectionViewController:(CarrierSelectionViewController *)viewController
        canCommitSelectedCarrierID:(NSString *)selectedCarrierID;
- (BOOL)carrierSelectionViewController:(CarrierSelectionViewController *)viewController
       persistSelectedCarrierIDs:(NSSet<NSString *> *)selectedCarrierIDs;

@end

@interface CarrierSelectionViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UISearchResultsUpdating, UISearchControllerDelegate>

@property (nonatomic, weak, nullable) id<CarrierSelectionViewControllerDelegate> delegate;
@property (nonatomic, copy, readonly) NSArray<PXTrustedCarrierOption *> *carrierOptions;
@property (nonatomic, copy, readonly) NSSet<NSString *> *selectedCarrierIDs;
// Set by a pushed Settings destination. The modal default retains Cancel/dismiss behavior.
@property (nonatomic, assign) BOOL usesPushNavigation;

- (instancetype)initWithCarrierOptions:(NSArray<PXTrustedCarrierOption *> *)carrierOptions
                    selectedCarrierIDs:(NSSet<NSString *> *)selectedCarrierIDs;

@end

NS_ASSUME_NONNULL_END
