// DESIGN SPEC — generated by Designer agent // Preserve component structure and accessibility attributes.
#import "CarrierSelectionViewController.h"

#import "PXLocalizedStrings.h"

@implementation PXTrustedCarrierOption
- (instancetype)initWithStableIdentifier:(NSString *)stableIdentifier countryName:(NSString *)countryName carrierName:(NSString *)carrierName {
    self = [super init];
    if (self) { _stableIdentifier = [stableIdentifier copy]; _countryName = [countryName copy]; _carrierName = [carrierName copy]; }
    return self;
}
@end

@interface CarrierSelectionViewController ()
@property (nonatomic, strong) UITableView *tableView;
@property (nonatomic, strong) UISearchController *searchController;
@property (nonatomic, strong) UIBarButtonItem *confirmButton;
@property (nonatomic, copy) NSArray<NSString *> *visibleCountries;
@property (nonatomic, copy) NSDictionary<NSString *, NSArray<PXTrustedCarrierOption *> *> *visibleOptions;
@property (nonatomic, copy, readwrite) NSArray<PXTrustedCarrierOption *> *carrierOptions;
@property (nonatomic, copy, readwrite) NSSet<NSString *> *selectedCarrierIDs;
@property (nonatomic, copy) NSSet<NSString *> *originalSelectedCarrierIDs;
@property (nonatomic, assign) BOOL confirmAfterSearchDismissal;
@end

@implementation CarrierSelectionViewController

- (instancetype)initWithCarrierOptions:(NSArray<PXTrustedCarrierOption *> *)carrierOptions selectedCarrierIDs:(NSSet<NSString *> *)selectedCarrierIDs {
    self = [super initWithNibName:nil bundle:nil];
    if (self) { _carrierOptions = [carrierOptions copy] ?: @[]; _selectedCarrierIDs = [selectedCarrierIDs copy] ?: [NSSet set]; _originalSelectedCarrierIDs = _selectedCarrierIDs; _visibleCountries = @[]; _visibleOptions = @{}; }
    return self;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    self.title = PXLocalizedString(@"image.carrier.title");
    self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeNever;
    self.view.backgroundColor = UIColor.systemGroupedBackgroundColor;
    if (!self.usesPushNavigation) { [self configureModalActions]; }
    [self configureSearch];
    if (self.usesPushNavigation) { [self configureConfirmButton]; }
    [self configureTable];
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(handleLanguagePreferenceChanged:)
                                                 name:PXUILanguagePreferenceDidChangeNotification
                                               object:nil];
    [self rebuildVisibleOptions];
}

- (void)dealloc {
    [[NSNotificationCenter defaultCenter] removeObserver:self
                                                    name:PXUILanguagePreferenceDidChangeNotification
                                                  object:nil];
}

- (void)handleLanguagePreferenceChanged:(NSNotification *)notification {
    (void)notification;
    self.title = PXLocalizedString(@"image.carrier.title");
    self.searchController.searchBar.placeholder = PXLocalizedString(@"image.carrier.search.placeholder");
    self.searchController.searchBar.accessibilityLabel = PXLocalizedString(@"image.carrier.search.accessibility_label");
    self.tableView.accessibilityLabel = PXLocalizedString(@"image.carrier.accessibility.list");
    if (!self.usesPushNavigation) {
        self.navigationItem.leftBarButtonItem.accessibilityLabel = PXLocalizedString(@"carrier.cancel.accessibility_label");
        self.navigationItem.rightBarButtonItem.accessibilityLabel = PXLocalizedString(@"carrier.done.accessibility_label");
    } else {
        self.confirmButton.title = PXLocalizedString(@"image.carrier.confirm.title");
        self.confirmButton.accessibilityLabel = PXLocalizedString(@"image.carrier.confirm.title");
        self.confirmButton.accessibilityHint = PXLocalizedString(@"image.carrier.confirm.hint");
    }
    [self rebuildVisibleOptions];
    if (self.view.window) {
        UIAccessibilityPostNotification(UIAccessibilityScreenChangedNotification, self.tableView);
    }
}

- (void)configureModalActions {
    UIBarButtonItem *cancel = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemCancel target:self action:@selector(handleCancelTapped:)];
    cancel.accessibilityLabel = PXLocalizedString(@"carrier.cancel.accessibility_label");
    self.navigationItem.leftBarButtonItem = cancel;
    UIBarButtonItem *done = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemDone target:self action:@selector(handleDoneTapped:)];
    done.accessibilityLabel = PXLocalizedString(@"carrier.done.accessibility_label");
    self.navigationItem.rightBarButtonItem = done;
}

- (void)configureSearch {
    self.searchController = [[UISearchController alloc] initWithSearchResultsController:nil];
    self.searchController.searchResultsUpdater = self;
    self.searchController.delegate = self;
    self.searchController.obscuresBackgroundDuringPresentation = NO;
    if (self.usesPushNavigation) self.searchController.automaticallyShowsCancelButton = NO;
    self.searchController.searchBar.placeholder = PXLocalizedString(@"image.carrier.search.placeholder");
    self.searchController.searchBar.accessibilityLabel = PXLocalizedString(@"image.carrier.search.accessibility_label");
    self.navigationItem.searchController = self.searchController;
    self.navigationItem.hidesSearchBarWhenScrolling = NO;
    self.definesPresentationContext = YES;
}

- (void)configureConfirmButton {
    UIBarButtonItem *button = [[UIBarButtonItem alloc]
        initWithTitle:PXLocalizedString(@"image.carrier.confirm.title")
                style:UIBarButtonItemStyleDone
               target:self
               action:@selector(handleConfirmTapped:)];
    button.accessibilityIdentifier = @"image-carrier-confirm";
    button.accessibilityLabel = PXLocalizedString(@"image.carrier.confirm.title");
    button.accessibilityHint = PXLocalizedString(@"image.carrier.confirm.hint");
    self.confirmButton = button;
    self.navigationItem.rightBarButtonItem = button;
    [self updateConfirmButtonState];
}

- (void)updateConfirmButtonState {
    self.confirmButton.enabled = self.selectedCarrierIDs.count == 1 &&
        ![self.selectedCarrierIDs isEqualToSet:self.originalSelectedCarrierIDs];
}

- (void)configureTable {
    self.tableView = [[UITableView alloc] initWithFrame:CGRectZero style:UITableViewStyleInsetGrouped];
    self.tableView.translatesAutoresizingMaskIntoConstraints = NO;
    self.tableView.dataSource = self;
    self.tableView.delegate = self;
    self.tableView.rowHeight = UITableViewAutomaticDimension;
    self.tableView.estimatedRowHeight = 58.0;
    self.tableView.allowsMultipleSelection = !self.usesPushNavigation;
    self.tableView.cellLayoutMarginsFollowReadableWidth = YES;
    self.tableView.accessibilityIdentifier = @"image-carrier-list";
    self.tableView.accessibilityLabel = PXLocalizedString(@"image.carrier.accessibility.list");
    [self.view addSubview:self.tableView];
    [NSLayoutConstraint activateConstraints:@[
        [self.tableView.topAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.topAnchor],
        [self.tableView.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor],
        [self.tableView.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor],
        [self.tableView.bottomAnchor constraintEqualToAnchor:self.view.bottomAnchor]
    ]];
}

- (void)updateSearchResultsForSearchController:(UISearchController *)searchController { [self rebuildVisibleOptions]; }

- (void)didDismissSearchController:(UISearchController *)searchController {
    (void)searchController;
    if (!self.confirmAfterSearchDismissal) { return; }
    self.confirmAfterSearchDismissal = NO;
    [self commitSelectedCarrier];
}

- (void)rebuildVisibleOptions {
    NSString *query = [self.searchController.searchBar.text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];
    NSMutableDictionary<NSString *, NSMutableArray<PXTrustedCarrierOption *> *> *grouped = [NSMutableDictionary dictionary];
    for (PXTrustedCarrierOption *option in self.carrierOptions) {
        if (query.length > 0 && ![option.countryName localizedCaseInsensitiveContainsString:query] && ![option.carrierName localizedCaseInsensitiveContainsString:query]) { continue; }
        NSMutableArray<PXTrustedCarrierOption *> *countryOptions = grouped[option.countryName];
        if (!countryOptions) { countryOptions = [NSMutableArray array]; grouped[option.countryName] = countryOptions; }
        [countryOptions addObject:option];
    }
    self.visibleCountries = [grouped.allKeys sortedArrayUsingSelector:@selector(localizedCaseInsensitiveCompare:)];
    NSMutableDictionary<NSString *, NSArray<PXTrustedCarrierOption *> *> *sorted = [NSMutableDictionary dictionary];
    for (NSString *country in self.visibleCountries) { sorted[country] = [grouped[country] sortedArrayUsingComparator:^NSComparisonResult(PXTrustedCarrierOption *left, PXTrustedCarrierOption *right) { return [left.carrierName localizedCaseInsensitiveCompare:right.carrierName]; }]; }
    self.visibleOptions = sorted;
    [self updateEmptyState];
    [self.tableView reloadData];
}

- (void)updateEmptyState {
    if (self.visibleCountries.count > 0) { self.tableView.backgroundView = nil; return; }
    UILabel *emptyLabel = [[UILabel alloc] init];
    emptyLabel.text = self.carrierOptions.count == 0 ? PXLocalizedString(@"carrier.empty.catalog") : PXLocalizedString(@"carrier.empty.search");
    emptyLabel.textAlignment = NSTextAlignmentCenter; emptyLabel.numberOfLines = 0; emptyLabel.textColor = UIColor.secondaryLabelColor; emptyLabel.font = [UIFont preferredFontForTextStyle:UIFontTextStyleBody]; emptyLabel.adjustsFontForContentSizeCategory = YES; emptyLabel.accessibilityTraits = UIAccessibilityTraitStaticText;
    self.tableView.backgroundView = emptyLabel;
}

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView { return self.visibleCountries.count; }
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section { return self.visibleOptions[self.visibleCountries[(NSUInteger)section]].count; }
- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section { return self.visibleCountries[(NSUInteger)section]; }
- (NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section { return self.usesPushNavigation && section == self.visibleCountries.count - 1 ? PXLocalizedString(@"image.carrier.footer") : nil; }

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    static NSString *const reuseIdentifier = @"ImageCarrierCell";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:reuseIdentifier] ?: [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:reuseIdentifier];
    NSString *country = self.visibleCountries[(NSUInteger)indexPath.section];
    PXTrustedCarrierOption *option = self.visibleOptions[country][(NSUInteger)indexPath.row];
    BOOL selected = [self.selectedCarrierIDs containsObject:option.stableIdentifier];
    UIListContentConfiguration *content = [UIListContentConfiguration subtitleCellConfiguration];
    content.text = option.carrierName; content.secondaryText = option.countryName; content.image = [UIImage systemImageNamed:@"antenna.radiowaves.left.and.right"]; content.imageProperties.tintColor = UIColor.systemBlueColor; cell.contentConfiguration = content;
    if (self.usesPushNavigation) {
        UIImageView *indicator = [[UIImageView alloc] initWithImage:[UIImage systemImageNamed:selected ? @"checkmark.circle.fill" : @"circle"]]; indicator.tintColor = selected ? UIColor.systemBlueColor : UIColor.tertiaryLabelColor; indicator.frame = CGRectMake(0.0, 0.0, 24.0, 24.0); cell.accessoryView = indicator; cell.accessoryType = UITableViewCellAccessoryNone;
    } else { cell.accessoryView = nil; cell.accessoryType = selected ? UITableViewCellAccessoryCheckmark : UITableViewCellAccessoryNone; }
    cell.accessibilityIdentifier = [@"image-carrier-" stringByAppendingString:option.stableIdentifier];
    cell.accessibilityLabel = PXLocalizedFormat(@"accessibility.settings.row", option.countryName, option.carrierName);
    cell.accessibilityValue = selected ? PXLocalizedString(@"accessibility.selected") : PXLocalizedString(@"accessibility.not_selected");
    cell.accessibilityHint = self.usesPushNavigation ? PXLocalizedString(@"image.carrier.selection_hint") : PXLocalizedString(@"carrier.row.add_hint");
    cell.accessibilityTraits = UIAccessibilityTraitButton | (selected ? UIAccessibilityTraitSelected : 0);
    return cell;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    PXTrustedCarrierOption *option = self.visibleOptions[self.visibleCountries[(NSUInteger)indexPath.section]][(NSUInteger)indexPath.row];
    if (self.usesPushNavigation) {
        self.selectedCarrierIDs = [NSSet setWithObject:option.stableIdentifier];
        [self updateConfirmButtonState];
        [self.tableView reloadData];
        UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, PXLocalizedFormat(@"image.carrier.selected_announcement", option.countryName, option.carrierName));
        return;
    }
    NSMutableSet<NSString *> *updated = [self.selectedCarrierIDs mutableCopy];
    if ([updated containsObject:option.stableIdentifier]) { [updated removeObject:option.stableIdentifier]; } else { [updated addObject:option.stableIdentifier]; }
    self.selectedCarrierIDs = updated;
    [self.tableView reloadData];
}

- (void)handleConfirmTapped:(UIBarButtonItem *)sender {
    if (!sender.enabled || self.selectedCarrierIDs.count != 1) { return; }
    if (self.searchController.isActive) {
        self.confirmAfterSearchDismissal = YES;
        self.searchController.active = NO;
        return;
    }
    [self commitSelectedCarrier];
}

- (void)commitSelectedCarrier {
    if (!self.confirmButton.enabled || self.selectedCarrierIDs.count != 1) { return; }
    NSString *selectedCarrierID = self.selectedCarrierIDs.anyObject;
    if ([self.delegate respondsToSelector:@selector(carrierSelectionViewController:canCommitSelectedCarrierID:)] &&
        ![self.delegate carrierSelectionViewController:self canCommitSelectedCarrierID:selectedCarrierID]) {
        return;
    }
    if ([self.delegate respondsToSelector:@selector(carrierSelectionViewController:persistSelectedCarrierIDs:)] &&
        ![self.delegate carrierSelectionViewController:self persistSelectedCarrierIDs:self.selectedCarrierIDs]) {
        return;
    }
    [self.delegate carrierSelectionViewController:self didCommitSelectedCarrierIDs:self.selectedCarrierIDs];
    [self.navigationController popViewControllerAnimated:YES];
}

- (void)handleCancelTapped:(UIBarButtonItem *)sender { [self dismissViewControllerAnimated:YES completion:nil]; }
- (void)handleDoneTapped:(UIBarButtonItem *)sender { if (self.selectedCarrierIDs.count > 0) { [self.delegate carrierSelectionViewController:self didCommitSelectedCarrierIDs:self.selectedCarrierIDs]; } [self dismissViewControllerAnimated:YES completion:nil]; }
@end
