// DESIGN SPEC — generated by Designer agent; preserve direct startup and guardian launch.
#import <UIKit/UIKit.h>
#import "ProjectX.h"
#import "TabBarController.h"
#import "APIManager.h"
#import "SupportViewController.h"
#import <UserNotifications/UserNotifications.h>
#import "AppDataCleaner.h"

// Import our guardian
extern void StartWeaponXGuardian(void);

@interface AppDelegate : UIResponder <UIApplicationDelegate, UNUserNotificationCenterDelegate>
@property (strong, nonatomic) UIWindow *window;
@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    self.window.backgroundColor = [UIColor systemBackgroundColor];
    
    // Set notification delegate
    [UNUserNotificationCenter currentNotificationCenter].delegate = self;
    
    TabBarController *tabBarController = [[TabBarController alloc] init];
    
    self.window.rootViewController = tabBarController;
    [self.window makeKeyAndVisible];
    
    // Register for push notifications after a delay, not during initial launch
    // This prevents the permission prompt from showing immediately on launch
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self registerForPushNotifications];
    });
    
    // Start the guardian to ensure persistent background execution
    StartWeaponXGuardian();
    
    return YES;
}

- (void)applicationWillEnterForeground:(UIApplication *)application {
    // Set a flag to indicate the app is resuming from recents
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
    [defaults setBool:YES forKey:@"WeaponXIsResuming"];
    [defaults synchronize];
    
    // Reset the resuming flag after a delay to ensure it's used by all components
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [defaults setBool:NO forKey:@"WeaponXIsResuming"];
        [defaults synchronize];
    });
}

- (void)applicationWillTerminate:(UIApplication *)application {
    // Clean up notification center if needed
    [[NSNotificationCenter defaultCenter] removeObserver:self];
}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
    // Convert token to string
    NSString *token = [self stringFromDeviceToken:deviceToken];
    NSLog(@"[WeaponX] Device Token: %@", token);
    
    // Save token to defaults
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
    [defaults setObject:token forKey:@"WeaponXPushToken"];
    [defaults synchronize];
    
    // Send token to server if user is logged in
    NSString *authToken = [defaults objectForKey:@"WeaponXAuthToken"];
    if (authToken) {
        [self registerPushTokenWithServer:token];
    }
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
    NSLog(@"[WeaponX] Push notification received in background: %@", userInfo);
    
    // For background notification handling
    // This method is called when the app is in the background and a notification arrives
    
    // Process the notification data
    NSDictionary *aps = userInfo[@"aps"];
    NSString *notificationType = userInfo[@"type"];
    
    // Handle different notification types for background processing
    if (aps) {
        if ([notificationType isEqualToString:@"broadcast"]) {
            // Optionally pre-fetch broadcast data in the background
            NSNumber *broadcastId = userInfo[@"broadcast_id"];
            if (broadcastId) {
                NSLog(@"[WeaponX] Received broadcast notification in background for broadcast ID: %@", broadcastId);
                // Here you could pre-fetch the broadcast data
            }
        } else if ([notificationType isEqualToString:@"admin_reply"] || [notificationType isEqualToString:@"ticket_reply"]) {
            // Optionally pre-fetch ticket data in the background
            NSNumber *ticketId = userInfo[@"ticket_id"];
            if (ticketId) {
                NSLog(@"[WeaponX] Received ticket reply notification in background for ticket ID: %@", ticketId);
                // Here you could pre-fetch the ticket data
            }
        }
    }
    
    // Update badge count for the support tab
    dispatch_async(dispatch_get_main_queue(), ^{
        [self updateSupportTabBadge];
    });
    
    // Indicate that new data was fetched
    completionHandler(UIBackgroundFetchResultNewData);
}

- (void)handleBroadcastNotification:(NSNumber *)broadcastId {
    if (!broadcastId) {
        return;
    }
    
    dispatch_async(dispatch_get_main_queue(), ^{
        // Update notification badge on Support tab
        [self updateSupportTabBadge];
        
        // If app is active, show the broadcast alert
        if ([UIApplication sharedApplication].applicationState == UIApplicationStateActive) {
            UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"New Announcement"
                                                                          message:@"A new announcement has been posted. Would you like to view it now?"
                                                                   preferredStyle:UIAlertControllerStyleAlert];
            
            [alert addAction:[UIAlertAction actionWithTitle:@"Later" style:UIAlertActionStyleCancel handler:nil]];
            [alert addAction:[UIAlertAction actionWithTitle:@"View" style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {
                // Open the broadcast detail view
                [self openBroadcastDetail:broadcastId];
            }]];
            
            [self.window.rootViewController presentViewController:alert animated:YES completion:nil];
        }
    });
}

- (void)handleTicketReplyNotification:(NSNumber *)ticketId {
    if (!ticketId) {
        return;
    }
    
    dispatch_async(dispatch_get_main_queue(), ^{
        // Update notification badge on Support tab
        [self updateSupportTabBadge];
        
        // If app is active, show the ticket reply alert
        if ([UIApplication sharedApplication].applicationState == UIApplicationStateActive) {
            UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"Support Ticket Update"
                                                                          message:@"There's a new reply to your support ticket. Would you like to view it now?"
                                                                   preferredStyle:UIAlertControllerStyleAlert];
            
            [alert addAction:[UIAlertAction actionWithTitle:@"Later" style:UIAlertActionStyleCancel handler:nil]];
            [alert addAction:[UIAlertAction actionWithTitle:@"View" style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {
                // Open the ticket detail view
                [self openTicketDetail:ticketId];
            }]];
            
            [self.window.rootViewController presentViewController:alert animated:YES completion:nil];
        }
    });
}

- (void)updateSupportTabBadge {
    TabBarController *tabBarController = (TabBarController *)self.window.rootViewController;
    if ([tabBarController isKindOfClass:[TabBarController class]]) {
        [tabBarController updateNotificationBadge];
    }
}

- (void)openBroadcastDetail:(NSNumber *)broadcastId {
    // Find the TabBarController
    TabBarController *tabBarController = (TabBarController *)self.window.rootViewController;
    if (![tabBarController isKindOfClass:[TabBarController class]]) {
        return;
    }
    
    // Support tab should be accessible by all users
    // Switch to the Support tab (index 3)
    [tabBarController setSelectedIndex:3];
    
    // Navigate to broadcast detail
    UINavigationController *supportNav = tabBarController.viewControllers[3];
    if ([supportNav isKindOfClass:[UINavigationController class]]) {
        SupportViewController *supportVC = supportNav.viewControllers.firstObject;
        if ([supportVC isKindOfClass:[SupportViewController class]]) {
            [supportVC openBroadcastDetail:broadcastId];
        }
    }
}

- (void)openTicketDetail:(NSNumber *)ticketId {
    // Find the TabBarController
    TabBarController *tabBarController = (TabBarController *)self.window.rootViewController;
    if (![tabBarController isKindOfClass:[TabBarController class]]) {
        return;
    }
    
    // Support tab should be accessible by all users
    // Switch to the Support tab (index 3)
    [tabBarController setSelectedIndex:3];
    
    // Navigate to ticket detail
    UINavigationController *supportNav = tabBarController.viewControllers[3];
    if ([supportNav isKindOfClass:[UINavigationController class]]) {
        SupportViewController *supportVC = supportNav.viewControllers.firstObject;
        if ([supportVC isKindOfClass:[SupportViewController class]]) {
            [supportVC openTicketDetail:ticketId];
        }
    }
}

- (NSString *)stringFromDeviceToken:(NSData *)deviceToken {
    NSUInteger length = deviceToken.length;
    if (length == 0) {
        return nil;
    }
    
    const unsigned char *buffer = deviceToken.bytes;
    NSMutableString *hexString = [NSMutableString stringWithCapacity:(length * 2)];
    
    for (int i = 0; i < length; ++i) {
        [hexString appendFormat:@"%02x", buffer[i]];
    }
    
    return [hexString copy];
}

- (void)registerPushTokenWithServer:(NSString *)token {
    if (!token || token.length == 0) {
        return;
    }
    
    [[APIManager sharedManager] registerDeviceToken:token deviceType:@"ios" completion:^(BOOL success, NSError *error) {
        if (error) {
            NSLog(@"[WeaponX] Error registering push token: %@", error);
        } else {
            NSLog(@"[WeaponX] Push token registered successfully");
        }
    }];
}

#pragma mark - UNUserNotificationCenterDelegate Methods

// Called when a notification is delivered to a foreground app
- (void)userNotificationCenter:(UNUserNotificationCenter *)center 
       willPresentNotification:(UNNotification *)notification 
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {
    
    NSLog(@"[WeaponX] Notification received in foreground: %@", notification.request.content.userInfo);
    
    // Parse the notification content
    NSDictionary *userInfo = notification.request.content.userInfo;
    NSString *notificationType = userInfo[@"type"];
    
    // Update badge count for the support tab
    [self updateSupportTabBadge];
    
    if ([notificationType isEqualToString:@"broadcast"]) {
        // For broadcasts, check if we should show an alert or let the system handle it
        NSNumber *broadcastId = userInfo[@"broadcast_id"];
        
        if (broadcastId) {
            // Show our custom alert for broadcasts
            [self showBroadcastAlertForBroadcastId:broadcastId];
            completionHandler(UNNotificationPresentationOptionNone);
        } else {
            // If no valid broadcast ID, still show the system notification
            completionHandler(UNNotificationPresentationOptionBadge | UNNotificationPresentationOptionSound | 
                             UNNotificationPresentationOptionList | UNNotificationPresentationOptionBanner);
        }
    } else if ([notificationType isEqualToString:@"admin_reply"] || [notificationType isEqualToString:@"ticket_reply"]) {
        // For ticket replies, show an alert even when in foreground
        NSNumber *ticketId = userInfo[@"ticket_id"];
        if (ticketId) {
            dispatch_async(dispatch_get_main_queue(), ^{
                UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"Support Ticket Update"
                                                                              message:@"There's a new reply to your support ticket. Would you like to view it now?"
                                                                       preferredStyle:UIAlertControllerStyleAlert];
                
                [alert addAction:[UIAlertAction actionWithTitle:@"Later" style:UIAlertActionStyleCancel handler:nil]];
                [alert addAction:[UIAlertAction actionWithTitle:@"View" style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {
                    // Open the ticket detail view
                    [self openTicketDetail:ticketId];
                }]];
                
                [self.window.rootViewController presentViewController:alert animated:YES completion:nil];
            });
            // Don't show the system notification since we're showing our own alert
            completionHandler(UNNotificationPresentationOptionNone);
        } else {
            // If no valid ticket ID, still show the system notification
            completionHandler(UNNotificationPresentationOptionBadge | UNNotificationPresentationOptionSound | 
                             UNNotificationPresentationOptionList | UNNotificationPresentationOptionBanner);
        }
    } else {
        // For other notification types, show the system notification
        completionHandler(UNNotificationPresentationOptionBadge | UNNotificationPresentationOptionSound | 
                         UNNotificationPresentationOptionList | UNNotificationPresentationOptionBanner);
    }
}

// Called to let your app know which action was selected by the user
- (void)userNotificationCenter:(UNUserNotificationCenter *)center 
didReceiveNotificationResponse:(UNNotificationResponse *)response 
         withCompletionHandler:(void (^)(void))completionHandler {
    
    NSLog(@"[WeaponX] User responded to notification: %@", response.notification.request.content.userInfo);
    
    // Get the notification data
    NSDictionary *userInfo = response.notification.request.content.userInfo;
    NSString *notificationType = userInfo[@"type"];
    
    // Handle different action types
    if ([response.actionIdentifier isEqualToString:@"VIEW_BROADCAST"] || 
        [response.actionIdentifier isEqualToString:UNNotificationDefaultActionIdentifier]) {
        
        if ([notificationType isEqualToString:@"broadcast"]) {
            NSNumber *broadcastId = userInfo[@"broadcast_id"];
            if (broadcastId) {
                [self openBroadcastDetail:broadcastId];
            }
        } else if ([notificationType isEqualToString:@"admin_reply"] || [notificationType isEqualToString:@"ticket_reply"]) {
            NSNumber *ticketId = userInfo[@"ticket_id"];
            if (ticketId) {
                [self openTicketDetail:ticketId];
            }
        }
    }
    
    // Call the completion handler when done
    completionHandler();
}

// Method to request notification permissions and register for push notifications
- (void)registerForPushNotifications {
    // Check if we've already attempted to request permissions before
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
    BOOL hasAttemptedPermissionRequest = [defaults boolForKey:@"WeaponXNotificationPermissionRequested"];
    
    // If we've already attempted to request permissions, don't show the prompt again
    if (hasAttemptedPermissionRequest) {
        NSLog(@"[WeaponX] Already attempted notification permission request before, not showing prompt again");
        
        // Just configure categories and register for remote notifications if we have permission
        UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
        [center getNotificationSettingsWithCompletionHandler:^(UNNotificationSettings * _Nonnull settings) {
            // Configure notification categories
            [self configureNotificationCategories];
            
            // Only register for remote notifications if authorized
            if (settings.authorizationStatus == UNAuthorizationStatusAuthorized || 
                settings.authorizationStatus == UNAuthorizationStatusProvisional) {
                dispatch_async(dispatch_get_main_queue(), ^{
                    [[UIApplication sharedApplication] registerForRemoteNotifications];
                });
            }
        }];
        return;
    }
    
    // First check if we already have notification permission before requesting
    UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
    
    [center getNotificationSettingsWithCompletionHandler:^(UNNotificationSettings * _Nonnull settings) {
        // If we haven't determined the permission status yet, request it
        if (settings.authorizationStatus == UNAuthorizationStatusNotDetermined) {
            NSLog(@"[WeaponX] Notification permission not determined, requesting permissions...");
            
            // Mark that we've attempted to request permissions to prevent future prompts
            [defaults setBool:YES forKey:@"WeaponXNotificationPermissionRequested"];
            [defaults synchronize];
            
            [center requestAuthorizationWithOptions:(UNAuthorizationOptionAlert | UNAuthorizationOptionSound | UNAuthorizationOptionBadge)
                                  completionHandler:^(BOOL granted, NSError * _Nullable error) {
                if (granted) {
                    NSLog(@"[WeaponX] Notification permission granted");
                    
                    // Configure notification categories
                    [self configureNotificationCategories];
                    
                    // Register for remote notifications on the main thread
                    dispatch_async(dispatch_get_main_queue(), ^{
                        [[UIApplication sharedApplication] registerForRemoteNotifications];
                    });
                } else {
                    NSLog(@"[WeaponX] Notification permission denied: %@", error);
                }
            }];
        } 
        // If already determined, just register for notifications if needed
        else {
            NSLog(@"[WeaponX] Notification authorization status already determined: %ld", (long)settings.authorizationStatus);
            
            // Mark that we've checked permissions to prevent future prompts
            [defaults setBool:YES forKey:@"WeaponXNotificationPermissionRequested"];
            [defaults synchronize];
            
            // Still configure categories even if we already have permissions
            [self configureNotificationCategories];
            
            // Only register for remote notifications if authorized
            if (settings.authorizationStatus == UNAuthorizationStatusAuthorized || 
                settings.authorizationStatus == UNAuthorizationStatusProvisional) {
                dispatch_async(dispatch_get_main_queue(), ^{
                    [[UIApplication sharedApplication] registerForRemoteNotifications];
                });
            }
        }
    }];
}

// Configure notification categories for actionable notifications
- (void)configureNotificationCategories {
    // Create actions for broadcast notifications
    UNNotificationAction *viewBroadcastAction = [UNNotificationAction actionWithIdentifier:@"VIEW_BROADCAST"
                                                                                     title:@"View"
                                                                                   options:UNNotificationActionOptionForeground];
    
    // Create broadcast category with actions
    UNNotificationCategory *broadcastCategory = [UNNotificationCategory categoryWithIdentifier:@"BROADCAST_CATEGORY"
                                                                                      actions:@[viewBroadcastAction]
                                                                            intentIdentifiers:@[]
                                                                                      options:UNNotificationCategoryOptionNone];
    
    // Create actions for ticket notifications
    UNNotificationAction *viewTicketAction = [UNNotificationAction actionWithIdentifier:@"VIEW_TICKET"
                                                                                  title:@"View"
                                                                                options:UNNotificationActionOptionForeground];
    
    // Create ticket category with actions
    UNNotificationCategory *ticketCategory = [UNNotificationCategory categoryWithIdentifier:@"TICKET_CATEGORY"
                                                                                    actions:@[viewTicketAction]
                                                                          intentIdentifiers:@[]
                                                                                    options:UNNotificationCategoryOptionNone];
    
    // Register the categories with the notification center
    UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
    [center setNotificationCategories:[NSSet setWithObjects:broadcastCategory, ticketCategory, nil]];
}

// Helper method to show the broadcast alert to avoid code duplication
- (void)showBroadcastAlertForBroadcastId:(NSNumber *)broadcastId {
    dispatch_async(dispatch_get_main_queue(), ^{
        UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"New Announcement"
                                                                      message:@"A new announcement has been posted. Would you like to view it now?"
                                                               preferredStyle:UIAlertControllerStyleAlert];
        
        [alert addAction:[UIAlertAction actionWithTitle:@"Later" style:UIAlertActionStyleCancel handler:nil]];
        [alert addAction:[UIAlertAction actionWithTitle:@"View" style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {
            // Open the broadcast detail view
            [self openBroadcastDetail:broadcastId];
        }]];
        
        [self.window.rootViewController presentViewController:alert animated:YES completion:nil];
    });
}

@end

int main(int argc, char * argv[]) {
    NSString * appDelegateClassName;
    
    // Check if we're running a test command
    if (argc > 2 && [[NSString stringWithUTF8String:argv[1]] isEqualToString:@"clean_test"]) {
        NSLog(@"Running clean test for bundle ID: %s", argv[2]);
        NSString *bundleID = [NSString stringWithUTF8String:argv[2]];
        
        // Initialize the AppDataCleaner
        AppDataCleaner *cleaner = [[AppDataCleaner alloc] init];
        
        // Check if there's data to clean
        if ([cleaner hasDataToClear:bundleID]) {
            NSLog(@"Found data to clean for %@", bundleID);
            
            // Perform the cleaning
            [cleaner clearDataForBundleID:bundleID completion:^(BOOL success, NSError *error) {
                NSLog(@"Cleaning completed with status: %@", success ? @"SUCCESS" : @"FAILURE");
                
                if (error) {
                    NSLog(@"Error during cleaning: %@", error);
                }
                
                // Verify the clean
                [cleaner verifyDataCleared:bundleID];
                
                // Exit after test is complete
                exit(0);
            }];
            
            // Run the run loop until callback completes
            [[NSRunLoop currentRunLoop] run];
        } else {
            NSLog(@"No data found to clean for %@", bundleID);
            exit(0);
        }
    }
    
    @autoreleasepool {
        // Setup code that might create autoreleased objects goes here.
        appDelegateClassName = NSStringFromClass([AppDelegate class]);
    }
    return UIApplicationMain(argc, argv, nil, appDelegateClassName);
}
