// DESIGN SPEC — generated by Designer agent // Coder: implement TODO items, do not change component structure or accessibility attributes
#import "ProfileIndicatorView.h"

@implementation ProfileIndicatorView

+ (instancetype)sharedInstance {
    static ProfileIndicatorView *sharedInstance = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        sharedInstance = [[self alloc] initWithFrame:CGRectZero];
        sharedInstance.hidden = YES;
        sharedInstance.userInteractionEnabled = NO;
        sharedInstance.accessibilityElementsHidden = YES;
    });
    return sharedInstance;
}

- (instancetype)initWithFrame:(CGRect)frame {
    self = [super initWithFrame:frame];
    if (self) {
        self.hidden = YES;
        self.userInteractionEnabled = NO;
        self.accessibilityElementsHidden = YES;
    }
    return self;
}

- (void)show {
    self.hidden = YES;
}

- (void)hide {
    self.hidden = YES;
}

- (void)updateProfileIndicator {
    self.hidden = YES;
}

@end
