// DESIGN SPEC — generated by Designer agent // Preserve component structure and accessibility attributes.
#import "ProjectXViewController.h"

#import "AppDataCleaner.h"
#import "DeviceModelManager.h"
#import "GraphicsIdentity.h"
#import "IdentifierManager.h"
#import "KeychainCommand.h"
#import "NetworkIdentity.h"
#import "ProfileManifest.h"
#import "ProjectXLogging.h"
#import "PXAutomaticEnvironmentCoordinator.h"
#import "PXEnvironmentModelSelection.h"
#import "PXEnvironmentPolicy.h"
#import "PXEnvironmentFailureDetailsViewController.h"
#import "PXLocalizedStrings.h"
#import "PXProjectXEnvironmentOperations.h"
#import "PXRootHidePath.h"
#import "PXSettingsHubViewController.h"
#import "PXSmartLocationViewController.h"
#import "PXTargetAppsViewController.h"
#import "PXTargetSelectionServices.h"
#import "RegionIdentity.h"
#import "TrustedCarrierPolicy.h"

typedef NS_ENUM(NSInteger, PXHomeSection) {
    PXHomeSectionCurrentEnvironment,
    PXHomeSectionTargetApps,
    PXHomeSectionPendingChanges,
    PXHomeSectionGenerate,
    PXHomeSectionPrivacyCleanup,
    PXHomeSectionPhysicalDevice,
    PXHomeSectionCount
};

typedef NS_ENUM(NSInteger, PXHomeEnvironmentState) {
    PXHomeEnvironmentStateReady,
    PXHomeEnvironmentStateNeedsGeneration,
    PXHomeEnvironmentStateProcessing,
    PXHomeEnvironmentStatePartialFailure,
    PXHomeEnvironmentStateServiceUnavailable
};

typedef NS_ENUM(NSInteger, PXHomeCleanupAction) {
    PXHomeCleanupActionPasteboard,
    PXHomeCleanupActionKeychain,
    PXHomeCleanupActionWebData
};

// Keep the home screen on one 4pt-based vertical rhythm. Inset-grouped tables
// otherwise add their own per-section top padding, including to empty sections.
static const CGFloat PXHomeSectionSpacing = 8.0;
static const CGFloat PXHomeFirstSectionHeaderVerticalPadding = 4.0;
static const CGFloat PXHomeSectionHeaderVerticalPadding = 12.0;
static const CGFloat PXHomeContentTopInset = 0.0;
static const CGFloat PXHomeContentBottomInset = 12.0;
static const CGFloat PXHomePrimaryActionVerticalInset = 16.0;

@interface ProjectXViewController () <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, strong) UITableView *tableView;
@property (nonatomic, copy) NSSet<NSString *> *selectedTargetBundleIdentifiers;
@property (nonatomic, assign) NSInteger selectedTargetCount;
@property (nonatomic, assign) PXHomeEnvironmentState environmentState;
@property (nonatomic, copy) NSString *environmentModel;
@property (nonatomic, copy) NSString *environmentNetwork;
@property (nonatomic, copy) NSString *environmentCarrier;
@property (nonatomic, copy) NSString *environmentRegion;
@property (nonatomic, copy) NSString *environmentLocation;
@property (nonatomic, assign) BOOL hasPendingChanges;
@property (nonatomic, strong) PXEnvironmentPolicyStore *environmentPolicyStore;
@property (nonatomic, strong) PXProjectXEnvironmentOperations *environmentOperations;
@property (nonatomic, strong) PXAutomaticEnvironmentCoordinator *environmentCoordinator;
@property (nonatomic, strong, nullable) NSNumber *physicalStorageSize;
@property (nonatomic, strong, nullable) PXEnvironmentFailureReport *lastFailureReport;
@property (nonatomic, strong, nullable) UIAlertController *pendingAlert;
@property (nonatomic, assign) BOOL cleanupInProgress;
@property (nonatomic, copy, nullable) NSString *cleanupStatusMessage;
@property (nonatomic, assign) NSUInteger cleanupFeedbackRevision;
@property (nonatomic, strong, nullable) UIVisualEffectView *activeNotifyView;
@property (nonatomic, assign) NSUInteger notifyRevision;
@end

@implementation ProjectXViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.navigationItem.title = nil;
    self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeNever;
    self.view.backgroundColor = UIColor.systemGroupedBackgroundColor;
    [self configureNavigation];
    [self configureTableView];
    [self configureInitialSummary];
    self.environmentPolicyStore = [PXEnvironmentPolicyStore sharedStore];
    NSDictionary<NSFileAttributeKey, id> *storageAttributes =
        [NSFileManager.defaultManager attributesOfFileSystemForPath:PXRootFSPath(@"/var/mobile") error:nil];
    self.physicalStorageSize = storageAttributes[NSFileSystemSize];
    self.environmentOperations = [PXProjectXEnvironmentOperations sharedOperations];
    PXTargetSelectionServices *targetSelectionServices = [PXTargetSelectionServices sharedServices];
    self.environmentCoordinator = [[PXAutomaticEnvironmentCoordinator alloc]
        initWithOperations:self.environmentOperations
        targetSelectionReconciler:targetSelectionServices.reconciler
        workQueue:dispatch_queue_create("com.hydra.projectx.environment", DISPATCH_QUEUE_SERIAL)
        completionQueue:dispatch_get_main_queue()];
    NSError *failureLoadError = nil;
    self.lastFailureReport = [PXEnvironmentFailureReport
        lastPersistedReportWithError:&failureLoadError];
    if (failureLoadError) {
        PXLog(@"[environment-diagnostics] Last failure could not be loaded: domain=%@ code=%ld message=%@",
              failureLoadError.domain,
              (long)failureLoadError.code,
              failureLoadError.localizedDescription);
    } else if (self.lastFailureReport) {
        self.environmentState = PXHomeEnvironmentStatePartialFailure;
    }
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(handleLanguagePreferenceChanged:)
                                                 name:PXUILanguagePreferenceDidChangeNotification
                                               object:nil];
    [self refreshEnvironmentSummary];
}

- (void)dealloc {
    [[NSNotificationCenter defaultCenter] removeObserver:self
                                                    name:PXUILanguagePreferenceDidChangeNotification
                                                  object:nil];
}

- (void)handleLanguagePreferenceChanged:(NSNotification *)notification {
    (void)notification;
    [self configureNavigation];
    self.tableView.accessibilityLabel = PXLocalizedString(@"image.home.accessibility.list");
    [self refreshEnvironmentSummary];
    if (self.view.window) {
        UIAccessibilityPostNotification(UIAccessibilityScreenChangedNotification, self.tableView);
    }
}

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [self refreshEnvironmentSummary];
}

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    if (!self.pendingAlert) {
        return;
    }
    UIAlertController *alert = self.pendingAlert;
    self.pendingAlert = nil;
    [self presentAlertFromVisiblePresenter:alert];
}

- (void)configureNavigation {
    self.navigationItem.backButtonTitle = PXLocalizedString(@"navigation.back");
    UIBarButtonItem *settings = [[UIBarButtonItem alloc] initWithImage:[UIImage systemImageNamed:@"gearshape"] style:UIBarButtonItemStylePlain target:self action:@selector(handleSettingsTapped:)];
    settings.accessibilityIdentifier = @"image-home-settings";
    settings.accessibilityLabel = PXLocalizedString(@"image.home.settings.accessibility_label");
    settings.accessibilityHint = PXLocalizedString(@"image.home.settings.accessibility_hint");
    self.navigationItem.rightBarButtonItem = settings;
}

- (void)configureTableView {
    self.tableView = [[UITableView alloc] initWithFrame:CGRectZero style:UITableViewStyleInsetGrouped];
    self.tableView.translatesAutoresizingMaskIntoConstraints = NO;
    self.tableView.dataSource = self;
    self.tableView.delegate = self;
    self.tableView.backgroundColor = UIColor.systemGroupedBackgroundColor;
    self.tableView.cellLayoutMarginsFollowReadableWidth = YES;
    self.tableView.rowHeight = UITableViewAutomaticDimension;
    self.tableView.estimatedRowHeight = 64.0;
    self.tableView.estimatedSectionHeaderHeight = 0.0;
    self.tableView.estimatedSectionFooterHeight = 0.0;
    self.tableView.sectionHeaderTopPadding = 0.0;
    self.tableView.contentInset = UIEdgeInsetsMake(PXHomeContentTopInset,
                                                   0.0,
                                                   PXHomeContentBottomInset,
                                                   0.0);
    self.tableView.scrollIndicatorInsets = self.tableView.contentInset;
    self.tableView.accessibilityIdentifier = @"image-home-list";
    self.tableView.accessibilityLabel = PXLocalizedString(@"image.home.accessibility.list");
    [self.view addSubview:self.tableView];
    [NSLayoutConstraint activateConstraints:@[
        [self.tableView.topAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.topAnchor],
        [self.tableView.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor],
        [self.tableView.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor],
        [self.tableView.bottomAnchor constraintEqualToAnchor:self.view.bottomAnchor]
    ]];
}

- (void)configureInitialSummary {
    self.selectedTargetBundleIdentifiers = [NSSet set];
    self.environmentState = PXHomeEnvironmentStateNeedsGeneration;
    self.environmentModel = PXLocalizedString(@"image.summary.not_configured");
    self.environmentNetwork = PXLocalizedString(@"image.summary.not_configured");
    self.environmentCarrier = PXLocalizedString(@"image.summary.not_configured");
    self.environmentRegion = PXLocalizedString(@"image.summary.derived_after_carrier");
    self.environmentLocation = PXLocalizedString(@"image.summary.not_configured");
}

- (void)refreshEnvironmentSummary {
    IdentifierManager *identifierManager = [IdentifierManager sharedManager];
    NSMutableSet<NSString *> *selectedBundleIdentifiers = [NSMutableSet set];
    for (NSString *bundleIdentifier in [identifierManager getApplicationInfo:nil]) {
        if ([identifierManager isApplicationInScope:bundleIdentifier]) {
            [selectedBundleIdentifiers addObject:bundleIdentifier];
        }
    }
    self.selectedTargetBundleIdentifiers = [selectedBundleIdentifiers copy];
    self.selectedTargetCount = self.selectedTargetBundleIdentifiers.count;

    NSError *summaryError = nil;
    NSDictionary<NSString *, id> *pendingModel = [self
        resolvedEnvironmentModelWithDidMigrate:nil
        error:&summaryError];
    NSSet<NSNumber *> *pendingNetworks =
        [self.environmentPolicyStore selectedNetworkTypesWithError:&summaryError];
    NSDictionary<NSString *, id> *pendingLocation =
        [self.environmentPolicyStore configuredLocationWithError:&summaryError];
    BOOL pendingLocationWasCleared =
        [self.environmentPolicyStore locationWasExplicitlyClearedWithError:&summaryError];
    self.hasPendingChanges =
        [self.environmentPolicyStore hasPendingChangesWithError:&summaryError];
    NSString *lastAppliedGenerationID =
        [self.environmentPolicyStore lastAppliedGenerationIDWithError:&summaryError];

    PXProfileStore *profileStore = [[PXProfileStore alloc]
        initWithIdentityDirectory:[identifierManager profileIdentityPath]];
    PXProfileManifest *activeManifest = [profileStore activeManifestWithError:nil];
    NSString *modelName = [pendingModel[@"name"] isKindOfClass:[NSString class]]
        ? pendingModel[@"name"]
        : activeManifest.device[@"name"];
    self.environmentModel = modelName.length > 0
        ? modelName
        : PXLocalizedString(@"image.summary.not_configured");

    NSSet<NSNumber *> *displayedNetworks = pendingNetworks;
    if (displayedNetworks.count == 0 && !pendingModel) {
        NSMutableSet<NSNumber *> *activeNetworks = [NSMutableSet set];
        NSArray *identifiers = [activeManifest.network[@"configuredNetworkTypes"] isKindOfClass:NSArray.class]
            ? activeManifest.network[@"configuredNetworkTypes"]
            : @[activeManifest.network[@"configuredNetworkType"] ?: @""];
        for (id identifier in identifiers) {
            PXEnvironmentNetworkType type = [identifier isKindOfClass:NSString.class]
                ? PXEnvironmentNetworkTypeFromIdentifier(identifier)
                : PXEnvironmentNetworkTypeUnspecified;
            if (type != PXEnvironmentNetworkTypeUnspecified) [activeNetworks addObject:@(type)];
        }
        displayedNetworks = [activeNetworks copy];
    }
    self.environmentNetwork = [self localizedNetworkTypes:displayedNetworks];

    NSDictionary<NSString *, id> *carrier = [self selectedCarrierRecordForIdentityDirectory:
        [identifierManager profileIdentityPath]];
    NSString *carrierName = [carrier[@"name"] isKindOfClass:[NSString class]]
        ? carrier[@"name"]
        : activeManifest.network[@"carrierName"];
    self.environmentCarrier = carrierName.length > 0
        ? carrierName
        : PXLocalizedString(@"image.summary.not_configured");
    PXRegionIdentity *region = carrier
        ? PXRegionIdentityForCountryCode(carrier[@"isoCountryCode"],
            [carrier[@"carrierID"] dataUsingEncoding:NSUTF8StringEncoding])
        : nil;
    NSString *regionCountry = [carrier[@"country"] isKindOfClass:[NSString class]]
        ? carrier[@"country"]
        : activeManifest.region[@"countryCode"];
    NSString *timeZone = region.timeZoneIdentifier ?: activeManifest.region[@"timeZone"];
    self.environmentRegion = regionCountry.length > 0 && timeZone.length > 0
        ? PXLocalizedFormat(@"image.settings.region.summary", regionCountry, timeZone)
        : PXLocalizedString(@"image.summary.derived_after_carrier");

    NSString *locationSummary = [pendingLocation[@"address"] isKindOfClass:[NSString class]]
        ? pendingLocation[@"address"]
        : (pendingLocationWasCleared ? nil : activeManifest.location[@"address"]);
    self.environmentLocation = locationSummary.length > 0
        ? locationSummary
        : PXLocalizedString(@"image.summary.not_configured");

    if (summaryError || ![self.environmentOperations isServiceReady]) {
        self.environmentState = PXHomeEnvironmentStateServiceUnavailable;
    } else if (self.lastFailureReport) {
        self.environmentState = PXHomeEnvironmentStatePartialFailure;
    } else if (self.environmentState != PXHomeEnvironmentStateProcessing) {
        NSSet<NSString *> *activeTargetBundleIdentifiers =
            [NSSet setWithArray:activeManifest.appIdentities.allKeys ?: @[]];
        self.environmentState = PXEnvironmentAppliedStateIsReady(
            self.hasPendingChanges,
            lastAppliedGenerationID,
            activeManifest.generationID,
            self.selectedTargetBundleIdentifiers,
            activeTargetBundleIdentifiers)
            ? PXHomeEnvironmentStateReady
            : PXHomeEnvironmentStateNeedsGeneration;
    }
    [self.tableView reloadData];
}

- (nullable NSDictionary<NSString *, id> *)selectedCarrierRecordForIdentityDirectory:(NSString *)identityDirectory {
    if (identityDirectory.length == 0) return nil;
    PXTrustedCarrierPolicyStore *store = [[PXTrustedCarrierPolicyStore alloc] init];
    NSString *carrierID = [store selectedCarrierIDWithError:nil];
    for (NSDictionary<NSString *, id> *carrier in PXCarrierCatalog()) {
        if ([carrier[@"carrierID"] isEqualToString:carrierID]) {
            return carrier;
        }
    }
    return nil;
}

- (NSString *)localizedNetworkType:(PXEnvironmentNetworkType)networkType {
    switch (networkType) {
        case PXEnvironmentNetworkTypeWiFi: return PXLocalizedString(@"image.network.wifi");
        case PXEnvironmentNetworkType5GNR: return PXLocalizedString(@"image.network.5g");
        case PXEnvironmentNetworkType4GLTE: return PXLocalizedString(@"image.network.4g");
        case PXEnvironmentNetworkType3G: return PXLocalizedString(@"image.network.3g");
        case PXEnvironmentNetworkType2G: return PXLocalizedString(@"image.network.2g");
        case PXEnvironmentNetworkTypeNone: return PXLocalizedString(@"image.network.none");
        case PXEnvironmentNetworkTypeUnspecified: return PXLocalizedString(@"image.summary.not_configured");
    }
}

- (NSString *)localizedNetworkTypes:(NSSet<NSNumber *> *)networkTypes {
    if (networkTypes.count == 0) return PXLocalizedString(@"image.summary.not_configured");
    NSMutableArray<NSString *> *names = [NSMutableArray array];
    for (NSString *identifier in PXEnvironmentNetworkTypeIdentifiers(networkTypes)) {
        [names addObject:[self localizedNetworkType:PXEnvironmentNetworkTypeFromIdentifier(identifier)]];
    }
    return [names componentsJoinedByString:PXLocalizedString(@"image.network.summary.separator")];
}

- (PXHomeSection)homeSectionForTableSection:(NSInteger)tableSection {
    if (!self.hasPendingChanges && tableSection >= PXHomeSectionPendingChanges) {
        return (PXHomeSection)(tableSection + 1);
    }
    return (PXHomeSection)tableSection;
}

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    (void)tableView;
    return PXHomeSectionCount - (self.hasPendingChanges ? 0 : 1);
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    (void)tableView;
    PXHomeSection homeSection = [self homeSectionForTableSection:section];
    if (homeSection == PXHomeSectionCurrentEnvironment) { return 5; }
    if (homeSection == PXHomeSectionPrivacyCleanup) { return 3; }
    if (homeSection == PXHomeSectionPhysicalDevice) { return 1; }
    return 1;
}

- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section {
    (void)tableView;
    switch ([self homeSectionForTableSection:section]) {
        case PXHomeSectionTargetApps: return PXLocalizedString(@"image.home.section.target_apps");
        case PXHomeSectionCurrentEnvironment: return PXLocalizedString(@"image.home.section.current_environment");
        case PXHomeSectionPrivacyCleanup: return PXLocalizedString(@"image.home.section.cleanup");
        case PXHomeSectionPhysicalDevice: return PXLocalizedString(@"image.home.device.title");
        default: return nil;
    }
}

- (NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section {
    (void)tableView;
    if ([self homeSectionForTableSection:section] == PXHomeSectionPrivacyCleanup) {
        return self.cleanupStatusMessage;
    }
    return nil;
}

- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section {
    if ([self tableView:tableView numberOfRowsInSection:section] == 0) {
        return CGFLOAT_MIN;
    }
    if ([self tableView:tableView titleForHeaderInSection:section].length == 0) {
        return PXHomeSectionSpacing;
    }
    CGFloat verticalPadding = section == 0
        ? PXHomeFirstSectionHeaderVerticalPadding
        : PXHomeSectionHeaderVerticalPadding;
    return ceil([UIFont preferredFontForTextStyle:UIFontTextStyleFootnote].lineHeight) +
        verticalPadding;
}

- (CGFloat)tableView:(UITableView *)tableView heightForFooterInSection:(NSInteger)section {
    if ([self tableView:tableView numberOfRowsInSection:section] == 0) {
        return CGFLOAT_MIN;
    }
    if ([self homeSectionForTableSection:section] == PXHomeSectionPrivacyCleanup &&
        self.cleanupStatusMessage.length > 0) {
        return UITableViewAutomaticDimension;
    }
    return CGFLOAT_MIN;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    PXHomeSection section = [self homeSectionForTableSection:indexPath.section];
    if (section == PXHomeSectionGenerate) { return [self generationCellForTableView:tableView]; }
    if (section == PXHomeSectionPendingChanges) { return [self pendingChangesCellForTableView:tableView]; }
    static NSString *const reuseIdentifier = @"ImageHomeCell";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:reuseIdentifier];
    if (!cell) {
        cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:reuseIdentifier];
        cell.textLabel.adjustsFontForContentSizeCategory = YES;
        cell.detailTextLabel.adjustsFontForContentSizeCategory = YES;
        cell.detailTextLabel.numberOfLines = 2;
    }
    UIListContentConfiguration *content = [UIListContentConfiguration subtitleCellConfiguration];
    cell.selectionStyle = UITableViewCellSelectionStyleDefault;
    cell.accessoryView = nil;
    cell.accessoryType = UITableViewCellAccessoryNone;
    cell.userInteractionEnabled = YES;
    cell.accessibilityTraits = UIAccessibilityTraitButton;
    if (section == PXHomeSectionTargetApps) {
        content.text = PXLocalizedFormat(@"image.home.target_apps.selected", (long)self.selectedTargetCount); content.secondaryText = PXLocalizedString(@"image.home.target_apps.detail"); content.image = [UIImage systemImageNamed:@"app.badge.fill"];
        cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator; cell.accessibilityIdentifier = @"image-home-target-apps";
    } else if (section == PXHomeSectionCurrentEnvironment) {
        [self configureEnvironmentContent:content forRow:indexPath.row];
        cell.accessoryType = indexPath.row == 4 ? UITableViewCellAccessoryDisclosureIndicator : UITableViewCellAccessoryNone;
        cell.selectionStyle = indexPath.row == 4 ? UITableViewCellSelectionStyleDefault : UITableViewCellSelectionStyleNone;
        cell.accessibilityTraits = indexPath.row == 4 ? UIAccessibilityTraitButton : UIAccessibilityTraitStaticText;
        cell.accessibilityIdentifier = [NSString stringWithFormat:@"image-home-environment-%ld", (long)indexPath.row];
    } else if (section == PXHomeSectionPrivacyCleanup) {
        [self configureCleanupContent:content forRow:indexPath.row];
        cell.userInteractionEnabled = !self.cleanupInProgress;
        cell.selectionStyle = self.cleanupInProgress
            ? UITableViewCellSelectionStyleNone
            : UITableViewCellSelectionStyleDefault;
        if (self.cleanupInProgress) {
            content.textProperties.color = UIColor.secondaryLabelColor;
            content.secondaryTextProperties.color = UIColor.tertiaryLabelColor;
            cell.accessibilityTraits |= UIAccessibilityTraitNotEnabled;
        }
        cell.accessibilityIdentifier = [NSString stringWithFormat:@"image-home-cleanup-%ld", (long)indexPath.row];
    } else if (section == PXHomeSectionPhysicalDevice) {
        [self configurePhysicalDeviceContent:content];
        cell.selectionStyle = UITableViewCellSelectionStyleNone;
        cell.accessibilityTraits = UIAccessibilityTraitStaticText;
        cell.accessibilityIdentifier = [NSString stringWithFormat:@"image-home-device-%ld", (long)indexPath.row];
    }
    content.imageProperties.tintColor = UIColor.systemBlueColor;
    content.textProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleBody];
    content.secondaryTextProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleSubheadline];
    cell.contentConfiguration = content;
    cell.accessibilityLabel = PXLocalizedFormat(@"accessibility.settings.row", content.text, content.secondaryText);
    cell.accessibilityHint = cell.selectionStyle == UITableViewCellSelectionStyleNone ? nil : PXLocalizedString(@"image.home.open_hint");
    return cell;
}

- (UITableViewCell *)pendingChangesCellForTableView:(UITableView *)tableView {
    UITableViewCell *cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil];
    UIListContentConfiguration *content = [UIListContentConfiguration subtitleCellConfiguration];
    content.text = PXLocalizedString(@"image.home.pending.title"); content.secondaryText = PXLocalizedString(@"image.home.pending.message"); content.image = [UIImage systemImageNamed:@"exclamationmark.circle.fill"]; content.imageProperties.tintColor = UIColor.systemOrangeColor;
    content.textProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleFootnote];
    content.secondaryTextProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleCaption1];
    cell.contentConfiguration = content; cell.selectionStyle = UITableViewCellSelectionStyleNone; cell.backgroundColor = UIColor.secondarySystemGroupedBackgroundColor; cell.accessibilityIdentifier = @"image-home-pending"; cell.accessibilityLabel = PXLocalizedFormat(@"accessibility.state", content.text, content.secondaryText); cell.accessibilityTraits = UIAccessibilityTraitStaticText;
    return cell;
}

- (UITableViewCell *)generationCellForTableView:(UITableView *)tableView {
    UITableViewCell *cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:nil];
    UIButton *button = [UIButton buttonWithType:UIButtonTypeSystem];
    button.translatesAutoresizingMaskIntoConstraints = NO;
    BOOL isProcessing = self.environmentState == PXHomeEnvironmentStateProcessing;
    UIButtonConfiguration *configuration = [UIButtonConfiguration filledButtonConfiguration];
    configuration.title = PXLocalizedString(isProcessing
        ? @"image.home.generate.processing_title"
        : @"image.home.generate.title");
    configuration.image = isProcessing
        ? nil
        : [UIImage systemImageNamed:@"arrow.triangle.2.circlepath"];
    configuration.showsActivityIndicator = isProcessing;
    configuration.imagePadding = 8.0; configuration.cornerStyle = UIButtonConfigurationCornerStyleLarge; configuration.baseBackgroundColor = UIColor.systemBlueColor; configuration.baseForegroundColor = UIColor.whiteColor;
    button.configuration = configuration; button.titleLabel.font = [UIFont preferredFontForTextStyle:UIFontTextStyleHeadline]; button.titleLabel.adjustsFontForContentSizeCategory = YES; button.accessibilityIdentifier = @"image-home-generate"; button.accessibilityLabel = PXLocalizedString(@"image.home.generate.accessibility_label"); button.accessibilityHint = PXLocalizedString(@"image.home.generate.accessibility_hint");
    button.accessibilityValue = isProcessing
        ? PXLocalizedString(@"image.home.generate.processing_title")
        : nil;
    button.enabled = !isProcessing;
    [button addTarget:self action:@selector(handleGenerateTapped:) forControlEvents:UIControlEventTouchUpInside];
    [cell.contentView addSubview:button];
    [NSLayoutConstraint activateConstraints:@[[button.topAnchor constraintEqualToAnchor:cell.contentView.topAnchor constant:PXHomePrimaryActionVerticalInset], [button.leadingAnchor constraintEqualToAnchor:cell.contentView.layoutMarginsGuide.leadingAnchor], [button.trailingAnchor constraintEqualToAnchor:cell.contentView.layoutMarginsGuide.trailingAnchor], [button.bottomAnchor constraintEqualToAnchor:cell.contentView.bottomAnchor constant:-PXHomePrimaryActionVerticalInset], [button.heightAnchor constraintGreaterThanOrEqualToConstant:48.0]]];
    cell.selectionStyle = UITableViewCellSelectionStyleNone; return cell;
}

- (void)configureEnvironmentContent:(UIListContentConfiguration *)content forRow:(NSInteger)row {
    NSArray<NSString *> *titles = @[@"image.home.environment.model", @"image.home.environment.network", @"image.home.environment.carrier", @"image.home.environment.region", @"image.home.environment.location"];
    NSArray<NSString *> *details = @[self.environmentModel, self.environmentNetwork, self.environmentCarrier, self.environmentRegion, self.environmentLocation];
    NSArray<NSString *> *symbols = @[@"iphone", @"wifi", @"antenna.radiowaves.left.and.right", @"location.north.line", @"mappin.and.ellipse"];
    content.text = PXLocalizedString(titles[(NSUInteger)row]); content.secondaryText = details[(NSUInteger)row]; content.image = [UIImage systemImageNamed:symbols[(NSUInteger)row]];
    if (row == 4) {
        content.secondaryTextProperties.numberOfLines = 1;
        content.secondaryTextProperties.adjustsFontSizeToFitWidth = YES;
        content.secondaryTextProperties.minimumScaleFactor = 0.1;
    }
}

- (void)configureCleanupContent:(UIListContentConfiguration *)content forRow:(NSInteger)row {
    NSArray<NSString *> *titles = @[@"image.home.cleanup.pasteboard", @"image.home.cleanup.keychain", @"image.home.cleanup.safari"];
    NSArray<NSString *> *details = @[@"image.home.cleanup.pasteboard.detail", @"image.home.cleanup.keychain.detail", @"image.home.cleanup.safari.detail"];
    NSArray<NSString *> *symbols = @[@"doc.on.clipboard", @"key", @"safari"];
    content.text = PXLocalizedString(titles[(NSUInteger)row]); content.secondaryText = PXLocalizedString(details[(NSUInteger)row]); content.image = [UIImage systemImageNamed:symbols[(NSUInteger)row]];
}

- (void)configurePhysicalDeviceContent:(UIListContentConfiguration *)content {
    DeviceModelManager *manager = DeviceModelManager.sharedManager;
    NSDictionary<NSString *, id> *record = [manager physicalDeviceSpecificationRecord];
    NSString *unknown = PXLocalizedString(@"image.home.device.unknown");
    NSString *modelIdentifier = [record[@"identifier"] isKindOfClass:[NSString class]]
        ? record[@"identifier"] : [manager physicalDeviceModelIdentifier];
    NSString *modelName = [record[@"name"] isKindOfClass:[NSString class]]
        ? record[@"name"] : modelIdentifier;
    NSString *processor = [record[@"cpuArchitecture"] isKindOfClass:[NSString class]]
        ? record[@"cpuArchitecture"] : unknown;
    NSString *systemVersion = UIDevice.currentDevice.systemVersion.length > 0
        ? [@"iOS " stringByAppendingString:UIDevice.currentDevice.systemVersion]
        : unknown;
    content.text = modelName.length > 0 ? modelName : unknown;
    NSString *details = [NSString stringWithFormat:@"%@ · %@ · %@",
        systemVersion,
        modelIdentifier.length > 0 ? modelIdentifier : unknown,
        processor.length > 0 ? processor : unknown];
    if (self.physicalStorageSize.unsignedLongLongValue > 0) {
        NSString *storageSize = [NSByteCountFormatter
            stringFromByteCount:self.physicalStorageSize.longLongValue
                     countStyle:NSByteCountFormatterCountStyleDecimal];
        details = [details stringByAppendingFormat:@" · %@",
            PXLocalizedFormat(@"image.home.device.storage", storageSize)];
    }
    content.secondaryText = details;
    content.secondaryTextProperties.numberOfLines = 0;
    content.image = [UIImage systemImageNamed:@"iphone"];
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    PXHomeSection section = [self homeSectionForTableSection:indexPath.section];
    if (section == PXHomeSectionTargetApps) { [self handleTargetAppsTapped]; }
    if (section == PXHomeSectionCurrentEnvironment && indexPath.row == 4) { [self handleSmartLocationTapped]; }
    if (section == PXHomeSectionPrivacyCleanup) {
        if (self.cleanupInProgress) { return; }
        if (indexPath.row == 0) { [self handleClearPasteboardTapped]; }
        if (indexPath.row == 1) { [self handleClearKeychainTapped]; }
        if (indexPath.row == 2) { [self handleClearSafariTapped]; }
    }
}

- (void)handleSettingsTapped:(UIBarButtonItem *)sender { [self.navigationController pushViewController:[[PXSettingsHubViewController alloc] initWithStyle:UITableViewStyleInsetGrouped] animated:YES]; }
- (void)handleTargetAppsTapped { PXTargetAppsViewController *controller = [[PXTargetAppsViewController alloc] initWithSelectedBundleIdentifiers:self.selectedTargetBundleIdentifiers completion:^(NSSet<NSString *> *selectedBundleIdentifiers) { [self handleTargetAppsSelection:selectedBundleIdentifiers]; }]; [self.navigationController pushViewController:controller animated:YES]; }
- (void)handleSmartLocationTapped { PXSmartLocationViewController *controller = [[PXSmartLocationViewController alloc] initWithLocationCommittedHandler:@selector(handleCommittedLocationSummary:) target:self]; [self.navigationController pushViewController:controller animated:YES]; }
- (void)handleTargetAppsSelection:(NSSet<NSString *> *)selectedBundleIdentifiers { self.selectedTargetBundleIdentifiers = [selectedBundleIdentifiers copy]; self.selectedTargetCount = self.selectedTargetBundleIdentifiers.count; [self refreshEnvironmentSummary]; }
- (void)handleCommittedLocationSummary:(NSString *)summary { self.environmentLocation = summary; [self refreshEnvironmentSummary]; }
- (void)handleGenerateTapped:(UIButton *)sender { [self beginNewEnvironment]; }

- (void)beginNewEnvironment {
    if (self.selectedTargetCount == 0) { [self presentNoTargetsAlert]; return; }
    if (![self.environmentOperations isServiceReady]) {
        self.environmentState = PXHomeEnvironmentStateServiceUnavailable;
        [self refreshEnvironmentSummary];
        [self presentEnvironmentAlertWithTitleKey:@"image.home.service.unavailable"
                                        message:PXLocalizedString(@"image.home.generate.service_unavailable")];
        return;
    }
    NSError *modelCompatibilityError = nil;
    NSDictionary<NSString *, id> *pendingModel = [self
        resolvedEnvironmentModelWithDidMigrate:nil
        error:&modelCompatibilityError];
    if (!pendingModel || modelCompatibilityError) {
        NSString *safeMessage = [self localizedDiagnosticMessageForRawMessage:
            modelCompatibilityError.localizedDescription];
        PXEnvironmentFailureDiagnostic *diagnostic = [[PXEnvironmentFailureDiagnostic alloc]
            initWithStage:PXLocalizedString(@"diagnostics.stage.validation")
                   target:nil
                  message:safeMessage
              errorDomain:modelCompatibilityError.domain
                errorCode:modelCompatibilityError.code];
        PXEnvironmentFailureReport *report = [[PXEnvironmentFailureReport alloc]
            initWithSummary:PXLocalizedString(@"diagnostics.summary.generation_failed")
                 diagnostics:@[diagnostic]
                   timestamp:[NSDate date]
                   reference:[self nextFailureReference]];
        [self handleEnvironmentPartiallyFailedWithReport:report];
        return;
    }
    self.environmentState = PXHomeEnvironmentStateProcessing; [self refreshEnvironmentSummary];
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, PXLocalizedString(@"image.home.generate.processing_announcement"));
    [self.environmentCoordinator runWithTargetBundleIdentifiers:self.selectedTargetBundleIdentifiers
                                                      completion:^(PXAutomaticEnvironmentResult *result) {
        switch (result.outcome) {
            case PXAutomaticEnvironmentOutcomeSuccess: {
                NSError *policyError = nil;
                if (![self recordAppliedGenerationWithError:&policyError]) {
                    [self handleEnvironmentPartiallyFailedWithError:policyError
                        message:PXLocalizedString(@"image.home.generate.state_save_failed")];
                    return;
                }
                [self handleEnvironmentSucceeded];
                break;
            }
            case PXAutomaticEnvironmentOutcomePartialFailure: {
                NSError *policyError = nil;
                if (![self recordAppliedGenerationWithError:&policyError]) {
                    [self handleEnvironmentPartiallyFailedWithError:policyError
                        message:PXLocalizedString(@"image.home.generate.state_save_failed")];
                    return;
                }
                [self handleEnvironmentPartiallyFailedWithReport:[self failureReportForEnvironmentResult:result]];
                break;
            }
            case PXAutomaticEnvironmentOutcomeFailure:
                [self handleEnvironmentPartiallyFailedWithReport:[self failureReportForEnvironmentResult:result]];
                break;
            case PXAutomaticEnvironmentOutcomeNoTargets:
                self.environmentState = PXHomeEnvironmentStateNeedsGeneration;
                [self refreshEnvironmentSummary];
                [self presentNoTargetsAlert];
                break;
            case PXAutomaticEnvironmentOutcomeBusy:
                [self handleEnvironmentPartiallyFailedWithMessage:
                    PXLocalizedString(@"image.home.generate.busy")];
                break;
        }
    }];
}
- (BOOL)recordAppliedGenerationWithError:(NSError **)error { IdentifierManager *manager = [IdentifierManager sharedManager]; PXProfileManifest *manifest = [[[PXProfileStore alloc] initWithIdentityDirectory:[manager profileIdentityPath]] activeManifestWithError:error]; if (!manifest.generationID) return NO; return [self.environmentPolicyStore markAppliedGenerationID:manifest.generationID date:[NSDate date] error:error]; }
- (void)handleEnvironmentSucceeded {
    NSError *clearError = nil;
    if (![PXEnvironmentFailureReport clearLastPersistedReportWithError:&clearError]) {
        PXLog(@"[environment-diagnostics] Last failure could not be cleared: domain=%@ code=%ld message=%@",
              clearError.domain,
              (long)clearError.code,
              clearError.localizedDescription);
    } else {
        PXLog(@"[environment-diagnostics] Last failure cleared after successful generation");
    }
    self.lastFailureReport = nil;
    self.environmentState = PXHomeEnvironmentStateReady;
    [self refreshEnvironmentSummary];
    [self showInAppNotifyWithMessage:PXLocalizedString(@"image.home.generate.success.notify")];
}
- (void)showInAppNotifyWithMessage:(NSString *)message {
    [self.activeNotifyView removeFromSuperview];
    self.activeNotifyView = nil;
    self.notifyRevision += 1;
    NSUInteger revision = self.notifyRevision;

    UIVisualEffectView *notifyView = [[UIVisualEffectView alloc]
        initWithEffect:[UIBlurEffect effectWithStyle:UIBlurEffectStyleSystemMaterial]];
    notifyView.translatesAutoresizingMaskIntoConstraints = NO;
    notifyView.layer.cornerRadius = 14.0;
    notifyView.layer.masksToBounds = YES;
    notifyView.alpha = 0.0;
    notifyView.transform = CGAffineTransformMakeTranslation(0.0, -12.0);
    notifyView.isAccessibilityElement = YES;
    notifyView.accessibilityIdentifier = @"image-home-notify";
    notifyView.accessibilityLabel = message;
    notifyView.accessibilityTraits = UIAccessibilityTraitStaticText;

    UIImageView *iconView = [[UIImageView alloc]
        initWithImage:[UIImage systemImageNamed:@"checkmark.circle.fill"]];
    iconView.translatesAutoresizingMaskIntoConstraints = NO;
    iconView.tintColor = UIColor.systemGreenColor;
    iconView.isAccessibilityElement = NO;

    UILabel *messageLabel = [[UILabel alloc] init];
    messageLabel.translatesAutoresizingMaskIntoConstraints = NO;
    messageLabel.text = message;
    messageLabel.textColor = UIColor.labelColor;
    messageLabel.font = [UIFont preferredFontForTextStyle:UIFontTextStyleSubheadline];
    messageLabel.adjustsFontForContentSizeCategory = YES;
    messageLabel.numberOfLines = 0;
    messageLabel.isAccessibilityElement = NO;

    [notifyView.contentView addSubview:iconView];
    [notifyView.contentView addSubview:messageLabel];
    [self.view addSubview:notifyView];
    [NSLayoutConstraint activateConstraints:@[
        [notifyView.topAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.topAnchor constant:8.0],
        [notifyView.leadingAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.leadingAnchor constant:16.0],
        [notifyView.trailingAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.trailingAnchor constant:-16.0],
        [notifyView.heightAnchor constraintGreaterThanOrEqualToConstant:52.0],
        [iconView.leadingAnchor constraintEqualToAnchor:notifyView.contentView.leadingAnchor constant:16.0],
        [iconView.centerYAnchor constraintEqualToAnchor:notifyView.contentView.centerYAnchor],
        [iconView.widthAnchor constraintEqualToConstant:24.0],
        [iconView.heightAnchor constraintEqualToConstant:24.0],
        [messageLabel.topAnchor constraintEqualToAnchor:notifyView.contentView.topAnchor constant:12.0],
        [messageLabel.leadingAnchor constraintEqualToAnchor:iconView.trailingAnchor constant:10.0],
        [messageLabel.trailingAnchor constraintEqualToAnchor:notifyView.contentView.trailingAnchor constant:-16.0],
        [messageLabel.bottomAnchor constraintEqualToAnchor:notifyView.contentView.bottomAnchor constant:-12.0]
    ]];
    self.activeNotifyView = notifyView;

    NSTimeInterval presentationDuration = UIAccessibilityIsReduceMotionEnabled() ? 0.0 : 0.22;
    [UIView animateWithDuration:presentationDuration animations:^{
        notifyView.alpha = 1.0;
        notifyView.transform = CGAffineTransformIdentity;
    } completion:^(BOOL finished) {
        (void)finished;
        UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, message);
    }];
    UINotificationFeedbackGenerator *feedback = [[UINotificationFeedbackGenerator alloc] init];
    [feedback notificationOccurred:UINotificationFeedbackTypeSuccess];

    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3.0 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        if (self.notifyRevision != revision || self.activeNotifyView != notifyView) {
            return;
        }
        NSTimeInterval dismissalDuration = UIAccessibilityIsReduceMotionEnabled() ? 0.0 : 0.16;
        [UIView animateWithDuration:dismissalDuration animations:^{
            notifyView.alpha = 0.0;
            notifyView.transform = CGAffineTransformMakeTranslation(0.0, -8.0);
        } completion:^(BOOL finished) {
            (void)finished;
            if (self.notifyRevision == revision && self.activeNotifyView == notifyView) {
                [notifyView removeFromSuperview];
                self.activeNotifyView = nil;
            }
        }];
    });
}
- (void)handleEnvironmentPartiallyFailedWithMessage:(NSString *)message { PXEnvironmentFailureDiagnostic *diagnostic = [[PXEnvironmentFailureDiagnostic alloc] initWithStage:PXLocalizedString(@"diagnostics.stage.generation") target:nil message:message]; PXEnvironmentFailureReport *report = [[PXEnvironmentFailureReport alloc] initWithSummary:PXLocalizedString(@"diagnostics.summary.generation_failed") diagnostics:@[diagnostic] timestamp:[NSDate date] reference:[self nextFailureReference]]; [self handleEnvironmentPartiallyFailedWithReport:report]; }
- (void)handleEnvironmentPartiallyFailedWithError:(NSError *)error message:(NSString *)message { PXEnvironmentFailureDiagnostic *diagnostic = [[PXEnvironmentFailureDiagnostic alloc] initWithStage:PXLocalizedString(@"diagnostics.stage.state_save") target:nil message:[self localizedDiagnosticMessageForRawMessage:error.localizedDescription ?: message] errorDomain:error.domain ?: @"com.hydra.projectx.environment-policy" errorCode:error.code]; PXEnvironmentFailureReport *report = [[PXEnvironmentFailureReport alloc] initWithSummary:message diagnostics:@[diagnostic] timestamp:[NSDate date] reference:[self nextFailureReference]]; [self handleEnvironmentPartiallyFailedWithReport:report]; }
- (void)handleEnvironmentPartiallyFailedWithReport:(PXEnvironmentFailureReport *)report {
    self.lastFailureReport = report;
    self.environmentState = PXHomeEnvironmentStatePartialFailure;
    NSError *persistenceError = nil;
    if (![report persistAsLastReportWithError:&persistenceError]) {
        PXLog(@"[environment-diagnostics] Failure %@ could not be persisted: domain=%@ code=%ld message=%@",
              report.reference,
              persistenceError.domain,
              (long)persistenceError.code,
              persistenceError.localizedDescription);
    }
    [self refreshEnvironmentSummary];
    [self presentFailureAlertForReport:report];
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, PXLocalizedString(@"image.home.generate.failure.announcement"));
}
- (PXEnvironmentFailureReport *)failureReportForEnvironmentResult:(PXAutomaticEnvironmentResult *)result { NSMutableArray<PXEnvironmentFailureDiagnostic *> *diagnostics = [NSMutableArray array]; for (PXAutomaticEnvironmentFailure *failure in result.failures) { [diagnostics addObject:[[PXEnvironmentFailureDiagnostic alloc] initWithStage:[self localizedStageForAction:failure.action] target:failure.bundleIdentifier message:[self localizedDiagnosticMessageForRawMessage:failure.message] errorDomain:failure.errorDomain errorCode:failure.errorCode]]; } if (diagnostics.count == 0) { [diagnostics addObject:[[PXEnvironmentFailureDiagnostic alloc] initWithStage:PXLocalizedString(@"diagnostics.stage.generation") target:nil message:PXLocalizedString(@"diagnostics.message.generic") errorDomain:@"com.hydra.projectx.environment" errorCode:0]]; } return [[PXEnvironmentFailureReport alloc] initWithSummary:PXLocalizedFormat(@"diagnostics.summary.failure_count", (long)diagnostics.count) diagnostics:diagnostics timestamp:[NSDate date] reference:[self nextFailureReference]]; }
- (NSString *)nextFailureReference { return [NSString stringWithFormat:@"PX-%@", [[NSUUID UUID] UUIDString].lowercaseString]; }
- (NSString *)localizedStageForAction:(NSString *)action { if ([action localizedCaseInsensitiveContainsString:@"activate"]) return PXLocalizedString(@"diagnostics.stage.activation"); if ([action localizedCaseInsensitiveContainsString:@"relaunch"]) return PXLocalizedString(@"diagnostics.stage.relaunch"); if ([action localizedCaseInsensitiveContainsString:@"target termination"]) return PXLocalizedString(@"diagnostics.stage.target_termination"); if ([action localizedCaseInsensitiveContainsString:@"target data cleanup"]) return PXLocalizedString(@"diagnostics.stage.target_cleanup"); if ([action localizedCaseInsensitiveContainsString:@"pasteboard"]) return PXLocalizedString(@"diagnostics.stage.pasteboard_cleanup"); if ([action localizedCaseInsensitiveContainsString:@"web data"]) return PXLocalizedString(@"diagnostics.stage.web_cleanup"); if ([action localizedCaseInsensitiveContainsString:@"validate"]) return PXLocalizedString(@"diagnostics.stage.validation"); return PXLocalizedString(@"diagnostics.stage.generation"); }
- (NSString *)localizedDiagnosticMessageForRawMessage:(NSString *)message { NSString *action = nil; if ([message localizedCaseInsensitiveContainsString:@"device record"]) action = PXLocalizedString(@"diagnostics.message.model_incomplete"); else if ([message localizedCaseInsensitiveContainsString:@"graphics model"] || [message localizedCaseInsensitiveContainsString:@"graphics capabilities"]) action = PXLocalizedString(@"diagnostics.message.graphics_incompatible"); else if ([message localizedCaseInsensitiveContainsString:@"Operating system tuple"] || [message localizedCaseInsensitiveContainsString:@"compatible iOS tuple"]) action = PXLocalizedString(@"diagnostics.message.ios_incompatible"); else if ([message localizedCaseInsensitiveContainsString:@"Network radio"] || [message localizedCaseInsensitiveContainsString:@"configured 5G network"]) action = PXLocalizedString(@"diagnostics.message.network_carrier_mismatch"); else if ([message localizedCaseInsensitiveContainsString:@"Regional identity"] || [message localizedCaseInsensitiveContainsString:@"valid regional identity"]) action = PXLocalizedString(@"diagnostics.message.regional_inconsistent"); else if ([message localizedCaseInsensitiveContainsString:@"session metadata"]) action = PXLocalizedString(@"diagnostics.message.session_missing"); else if ([message localizedCaseInsensitiveContainsString:@"Identifier"] || [message localizedCaseInsensitiveContainsString:@"IMEI"] || [message localizedCaseInsensitiveContainsString:@"UUID"]) action = PXLocalizedString(@"diagnostics.message.identifier_invalid"); else if ([message localizedCaseInsensitiveContainsString:@"metadata"] || [message localizedCaseInsensitiveContainsString:@"non-empty catalogs"]) action = PXLocalizedString(@"diagnostics.message.metadata_incomplete"); else action = PXLocalizedString(@"diagnostics.message.generic"); return message.length > 0 ? PXLocalizedFormat(@"diagnostics.message.action_with_reason", action, message) : action; }
- (void)presentFailureAlertForReport:(PXEnvironmentFailureReport *)report {
    PXEnvironmentFailureDiagnostic *first = report.diagnostics.firstObject;
    NSDateFormatter *formatter = [[NSDateFormatter alloc] init];
    formatter.dateStyle = NSDateFormatterShortStyle;
    formatter.timeStyle = NSDateFormatterShortStyle;
    NSString *message = PXLocalizedFormat(
        @"diagnostics.alert.message",
        report.summary,
        first.stage,
        first.target ?: PXLocalizedString(@"diagnostics.target.none"),
        first.message,
        first.errorDomain,
        (long)first.errorCode,
        [formatter stringFromDate:report.timestamp],
        report.reference);
    UIAlertController *alert = [UIAlertController
        alertControllerWithTitle:PXLocalizedString(@"image.home.generate.failure.title")
        message:message
        preferredStyle:UIAlertControllerStyleAlert];
    NSError *diagnosticError = [NSError errorWithDomain:first.errorDomain
                                                   code:first.errorCode
                                               userInfo:nil];
    if (PXEnvironmentModelSelectionCanRecoverFromError(diagnosticError)) {
        [alert addAction:[UIAlertAction
            actionWithTitle:PXLocalizedString(@"diagnostics.action.use_this_device")
            style:UIAlertActionStyleDefault
            handler:^(UIAlertAction *action) {
                (void)action;
                [self recoverUsingPhysicalDeviceModel];
            }]];
    }
    [alert addAction:[UIAlertAction
        actionWithTitle:PXLocalizedString(@"diagnostics.action.view_details")
        style:UIAlertActionStyleDefault
        handler:^(UIAlertAction *action) {
            (void)action;
            [self presentLastFailureDetails];
        }]];
    [alert addAction:[UIAlertAction
        actionWithTitle:PXLocalizedString(@"diagnostics.action.copy")
        style:UIAlertActionStyleDefault
        handler:^(UIAlertAction *action) {
            (void)action;
            [self copyLastFailureDiagnostics];
        }]];
    [alert addAction:[UIAlertAction
        actionWithTitle:PXLocalizedString(@"navigation.close")
        style:UIAlertActionStyleCancel
        handler:nil]];
    [self presentAlertFromVisiblePresenter:alert];
}

- (void)recoverUsingPhysicalDeviceModel {
    NSError *error = nil;
    if (![self selectPhysicalDeviceModelWithError:&error]) {
        [self handleEnvironmentPartiallyFailedWithError:error
            message:PXLocalizedString(@"image.model.recovery.failed")];
        return;
    }
    [self refreshEnvironmentSummary];
    [self presentEnvironmentAlertWithTitleKey:@"image.model.recovery.success.title"
                                      message:PXLocalizedString(@"image.model.recovery.success.message")];
    UIAccessibilityPostNotification(
        UIAccessibilityAnnouncementNotification,
        PXLocalizedString(@"image.model.use_this_device.selected_announcement"));
}

- (BOOL)selectPhysicalDeviceModelWithError:(NSError **)error {
    NSDictionary<NSString *, id> *physicalModel =
        [DeviceModelManager.sharedManager physicalDeviceSpecificationRecord];
    if (!physicalModel) {
        if (error) {
            *error = [NSError errorWithDomain:PXEnvironmentModelSelectionErrorDomain
                                         code:1
                                     userInfo:@{NSLocalizedDescriptionKey:
                                         @"The physical device model is unavailable"}];
        }
        return NO;
    }
    if (!PXGraphicsModelRecordIsCompatibleWithHostCapabilities(
        physicalModel,
        PXCurrentGraphicsHostCapabilities(),
        error)) {
        return NO;
    }
    return [self.environmentPolicyStore savePhysicalDeviceModelRecord:physicalModel error:error];
}
- (void)presentLastFailureDetails { if (!self.lastFailureReport) return; PXEnvironmentFailureDetailsViewController *details = [[PXEnvironmentFailureDetailsViewController alloc] initWithReport:self.lastFailureReport]; UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:details]; navigationController.modalPresentationStyle = UIModalPresentationPageSheet; UIViewController *presenter = [self visiblePresenter]; if ([presenter isKindOfClass:[UIAlertController class]]) { UIViewController *underlyingPresenter = presenter.presentingViewController ?: self; [presenter dismissViewControllerAnimated:YES completion:^{ [underlyingPresenter presentViewController:navigationController animated:YES completion:nil]; }]; return; } [presenter presentViewController:navigationController animated:YES completion:nil]; }
- (void)copyLastFailureDiagnostics { if (!self.lastFailureReport) return; UIPasteboard.generalPasteboard.string = [self.lastFailureReport redactedTextRepresentation]; UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, PXLocalizedString(@"diagnostics.copy.confirmation")); }
- (UIViewController *)visiblePresenter { UIViewController *presenter = self.navigationController.topViewController ?: self; while (presenter.presentedViewController) { presenter = presenter.presentedViewController; } return presenter; }
- (void)presentEnvironmentAlertWithTitleKey:(NSString *)titleKey message:(NSString *)message { UIAlertController *alert = [UIAlertController alertControllerWithTitle:PXLocalizedString(titleKey) message:message preferredStyle:UIAlertControllerStyleAlert]; [alert addAction:[UIAlertAction actionWithTitle:PXLocalizedString(@"navigation.close") style:UIAlertActionStyleCancel handler:nil]]; [self presentAlertFromVisiblePresenter:alert]; }
- (void)presentAlertFromVisiblePresenter:(UIAlertController *)alert { UIViewController *presenter = [self visiblePresenter]; if ([presenter isKindOfClass:[UIAlertController class]]) { UIViewController *underlyingPresenter = presenter.presentingViewController ?: self; [presenter dismissViewControllerAnimated:YES completion:^{ [underlyingPresenter presentViewController:alert animated:YES completion:nil]; }]; return; } if (!presenter.view.window) { self.pendingAlert = alert; return; } id<UIViewControllerTransitionCoordinator> transitionCoordinator = presenter.transitionCoordinator; if (transitionCoordinator) { [transitionCoordinator animateAlongsideTransition:nil completion:^(id<UIViewControllerTransitionCoordinatorContext> context) { (void)context; [self presentAlertFromVisiblePresenter:alert]; }]; return; } [presenter presentViewController:alert animated:YES completion:nil]; }
- (void)presentNoTargetsAlert { UIAlertController *alert = [UIAlertController alertControllerWithTitle:PXLocalizedString(@"image.home.no_targets.title") message:PXLocalizedString(@"image.home.no_targets.message") preferredStyle:UIAlertControllerStyleAlert]; [alert addAction:[UIAlertAction actionWithTitle:PXLocalizedString(@"navigation.cancel") style:UIAlertActionStyleCancel handler:nil]]; [alert addAction:[UIAlertAction actionWithTitle:PXLocalizedString(@"image.home.no_targets.choose") style:UIAlertActionStyleDefault handler:^(UIAlertAction *action) { [self handleTargetAppsTapped]; }]]; [self presentViewController:alert animated:YES completion:nil]; }

- (void)handleClearPasteboardTapped { [self presentCleanupConfirmationForAction:PXHomeCleanupActionPasteboard titleKey:@"image.home.cleanup.pasteboard" messageKey:@"image.home.cleanup.pasteboard.confirmation"]; }
- (void)handleClearKeychainTapped { [self presentCleanupConfirmationForAction:PXHomeCleanupActionKeychain titleKey:@"image.home.cleanup.keychain" messageKey:@"image.home.cleanup.keychain.confirmation"]; }
- (void)handleClearSafariTapped { [self presentCleanupConfirmationForAction:PXHomeCleanupActionWebData titleKey:@"image.home.cleanup.safari" messageKey:@"image.home.cleanup.safari.confirmation"]; }
- (void)presentCleanupConfirmationForAction:(PXHomeCleanupAction)cleanupAction titleKey:(NSString *)titleKey messageKey:(NSString *)messageKey {
    if (self.cleanupInProgress) {
        return;
    }
    if (cleanupAction != PXHomeCleanupActionPasteboard && self.selectedTargetBundleIdentifiers.count == 0) {
        [self presentNoTargetsAlert];
        return;
    }
    NSString *title = PXLocalizedString(titleKey);
    UIAlertController *alert = [UIAlertController alertControllerWithTitle:title message:PXLocalizedString(messageKey) preferredStyle:UIAlertControllerStyleAlert];
    [alert addAction:[UIAlertAction actionWithTitle:PXLocalizedString(@"navigation.cancel") style:UIAlertActionStyleCancel handler:nil]];
    [alert addAction:[UIAlertAction actionWithTitle:title style:UIAlertActionStyleDestructive handler:^(UIAlertAction *action) { [self beginCleanupAction:cleanupAction name:title]; }]];
    [self presentViewController:alert animated:YES completion:nil];
}
- (void)setCleanupStatusMessage:(nullable NSString *)message clearAfterDelay:(NSTimeInterval)delay {
    self.cleanupStatusMessage = [message copy];
    self.cleanupFeedbackRevision += 1;
    NSUInteger revision = self.cleanupFeedbackRevision;
    [self.tableView reloadData];
    if (message.length == 0 || delay <= 0.0) {
        return;
    }
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(delay * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        if (self.cleanupFeedbackRevision != revision) {
            return;
        }
        self.cleanupStatusMessage = nil;
        self.cleanupFeedbackRevision += 1;
        [self.tableView reloadData];
    });
}
- (void)beginCleanupAction:(PXHomeCleanupAction)cleanupAction name:(NSString *)cleanupName {
    if (self.cleanupInProgress) {
        return;
    }
    if (self.selectedTargetBundleIdentifiers.count == 0) {
        if (cleanupAction != PXHomeCleanupActionPasteboard) {
            [self presentNoTargetsAlert];
            return;
        }
    }
    self.cleanupInProgress = YES;
    [self setCleanupStatusMessage:PXLocalizedFormat(@"image.home.cleanup.in_progress", cleanupName)
                  clearAfterDelay:0.0];
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, PXLocalizedFormat(@"image.home.cleanup.started_announcement", cleanupName));
    AppDataCleaner *cleaner = [AppDataCleaner sharedManager];
    if (cleanupAction == PXHomeCleanupActionPasteboard) {
        [cleaner clearClipboard];
        dispatch_async(dispatch_get_main_queue(), ^{
            [self presentCleanupResultForName:cleanupName
                                     failures:@[]
              protectedSharedAccessGroupCount:0];
        });
        return;
    }
    dispatch_group_t group = dispatch_group_create();
    dispatch_queue_t failureQueue = dispatch_queue_create("com.hydra.projectx.cleanup.failures", DISPATCH_QUEUE_SERIAL);
    NSMutableArray<NSString *> *failures = [NSMutableArray array];
    __block NSUInteger protectedSharedAccessGroupCount = 0;
    for (NSString *bundleIdentifier in self.selectedTargetBundleIdentifiers) {
        if (cleanupAction == PXHomeCleanupActionKeychain) {
            dispatch_group_enter(group);
            [cleaner clearKeychainForBundleID:bundleIdentifier includeAppFamily:NO completion:^(BOOL success, NSArray<PXKeychainCommandResponse *> *responses, NSError *error) {
                NSUInteger responseProtectedGroupCount = 0;
                for (PXKeychainCommandResponse *response in responses) {
                    responseProtectedGroupCount += response.protectedSharedAccessGroupCount;
                }
                dispatch_sync(failureQueue, ^{
                    protectedSharedAccessGroupCount += responseProtectedGroupCount;
                    if (!success) {
                        [failures addObject:error.localizedDescription ?: bundleIdentifier];
                    }
                });
                dispatch_group_leave(group);
            }];
            continue;
        }
        dispatch_group_enter(group);
        dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED, 0), ^{
            NSError *error = nil;
            if (![cleaner clearWebDataForBundleID:bundleIdentifier error:&error]) {
                dispatch_sync(failureQueue, ^{ [failures addObject:error.localizedDescription ?: bundleIdentifier]; });
            }
            dispatch_group_leave(group);
        });
    }
    dispatch_group_notify(group, dispatch_get_main_queue(), ^{
        [self presentCleanupResultForName:cleanupName
                                 failures:[failures copy]
          protectedSharedAccessGroupCount:protectedSharedAccessGroupCount];
    });
}
- (void)presentCleanupResultForName:(NSString *)cleanupName
                           failures:(NSArray<NSString *> *)failures
    protectedSharedAccessGroupCount:(NSUInteger)protectedSharedAccessGroupCount {
    self.cleanupInProgress = NO;
    if (failures.count == 0) {
        NSString *message = PXLocalizedFormat(@"image.home.cleanup.success", cleanupName);
        if (protectedSharedAccessGroupCount > 0) {
            message = [NSString stringWithFormat:@"%@\n%@",
                message,
                PXLocalizedFormat(@"image.home.cleanup.keychain.protected_groups_retained",
                                  (long)protectedSharedAccessGroupCount)];
        }
        [self setCleanupStatusMessage:message clearAfterDelay:4.0];
        UINotificationFeedbackGenerator *feedback = [[UINotificationFeedbackGenerator alloc] init];
        [feedback notificationOccurred:UINotificationFeedbackTypeSuccess];
        UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, message);
        return;
    }
    NSString *message = [NSString stringWithFormat:@"%@\n\n%@",
        PXLocalizedFormat(@"image.home.cleanup.failure", (long)failures.count),
        [failures componentsJoinedByString:@"\n"]];
    if (protectedSharedAccessGroupCount > 0) {
        message = [NSString stringWithFormat:@"%@\n\n%@",
            message,
            PXLocalizedFormat(@"image.home.cleanup.keychain.protected_groups_retained",
                              (long)protectedSharedAccessGroupCount)];
    }
    [self setCleanupStatusMessage:nil clearAfterDelay:0.0];
    [self presentEnvironmentAlertWithTitleKey:@"image.home.cleanup.failure.title"
                                      message:message];
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, message);
}

- (nullable NSDictionary<NSString *, id> *)resolvedEnvironmentModelWithDidMigrate:(BOOL *)didMigrate error:(NSError **)error { DeviceModelManager *manager = DeviceModelManager.sharedManager; return PXResolveEnvironmentModelSelection(self.environmentPolicyStore, [manager allDeviceSpecificationRecords], [manager physicalDeviceSpecificationRecord], PXCurrentGraphicsHostCapabilities(), didMigrate, error); }
@end
