// DESIGN SPEC — generated by Designer agent // Preserve component structure and accessibility attributes.
#import <UIKit/UIKit.h>
#import "PXEnvironmentFailureReport.h"

NS_ASSUME_NONNULL_BEGIN

@interface PXEnvironmentFailureDetailsViewController : UITableViewController
- (instancetype)initWithReport:(PXEnvironmentFailureReport *)report;
@end

NS_ASSUME_NONNULL_END
