// DESIGN SPEC — generated by Designer agent // Preserve component structure and accessibility attributes.
#import "PXEnvironmentFailureDetailsViewController.h"

#import "PXLocalizedStrings.h"

@interface PXEnvironmentFailureDetailsViewController ()
@property (nonatomic, strong) PXEnvironmentFailureReport *report;
@end

@implementation PXEnvironmentFailureDetailsViewController

- (instancetype)initWithReport:(PXEnvironmentFailureReport *)report {
    self = [super initWithStyle:UITableViewStyleInsetGrouped];
    if (self) { _report = report; }
    return self;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    self.title = PXLocalizedString(@"diagnostics.title");
    self.view.backgroundColor = UIColor.systemGroupedBackgroundColor;
    self.tableView.rowHeight = UITableViewAutomaticDimension;
    self.tableView.estimatedRowHeight = 76.0;
    self.tableView.cellLayoutMarginsFollowReadableWidth = YES;
    self.tableView.accessibilityIdentifier = @"environment-failure-details";
    self.tableView.accessibilityLabel = PXLocalizedString(@"diagnostics.accessibility.list");
    UIBarButtonItem *copy = [[UIBarButtonItem alloc] initWithImage:[UIImage systemImageNamed:@"doc.on.doc"] style:UIBarButtonItemStylePlain target:self action:@selector(handleCopyTapped:)];
    copy.accessibilityLabel = PXLocalizedString(@"diagnostics.copy.accessibility_label");
    copy.accessibilityHint = PXLocalizedString(@"diagnostics.copy.accessibility_hint");
    copy.accessibilityIdentifier = @"environment-failure-copy";
    self.navigationItem.rightBarButtonItem = copy;
    UIBarButtonItem *close = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemClose target:self action:@selector(handleCloseTapped:)];
    close.accessibilityLabel = PXLocalizedString(@"navigation.close");
    close.accessibilityIdentifier = @"environment-failure-close";
    self.navigationItem.leftBarButtonItem = close;
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(handleLanguagePreferenceChanged:)
                                                 name:PXUILanguagePreferenceDidChangeNotification
                                               object:nil];
}

- (void)dealloc {
    [[NSNotificationCenter defaultCenter] removeObserver:self
                                                    name:PXUILanguagePreferenceDidChangeNotification
                                                  object:nil];
}

- (void)handleLanguagePreferenceChanged:(NSNotification *)notification {
    (void)notification;
    self.title = PXLocalizedString(@"diagnostics.title");
    self.tableView.accessibilityLabel = PXLocalizedString(@"diagnostics.accessibility.list");
    self.navigationItem.rightBarButtonItem.accessibilityLabel = PXLocalizedString(@"diagnostics.copy.accessibility_label");
    self.navigationItem.rightBarButtonItem.accessibilityHint = PXLocalizedString(@"diagnostics.copy.accessibility_hint");
    self.navigationItem.leftBarButtonItem.accessibilityLabel = PXLocalizedString(@"navigation.close");
    [self.tableView reloadData];
    if (self.view.window) {
        UIAccessibilityPostNotification(UIAccessibilityScreenChangedNotification, self.tableView);
    }
}

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView { return self.report.diagnostics.count + 1; }
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section { return 1; }
- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section { return section == 0 ? PXLocalizedString(@"diagnostics.section.summary") : PXLocalizedFormat(@"diagnostics.section.failure", (long)section); }
- (NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section { return section == self.report.diagnostics.count ? PXLocalizedString(@"diagnostics.redaction.footer") : nil; }

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    static NSString *const reuseIdentifier = @"EnvironmentFailureDetailCell";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:reuseIdentifier];
    if (!cell) {
        cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:reuseIdentifier];
        cell.textLabel.adjustsFontForContentSizeCategory = YES;
        cell.detailTextLabel.adjustsFontForContentSizeCategory = YES;
        cell.detailTextLabel.numberOfLines = 0;
        cell.selectionStyle = UITableViewCellSelectionStyleNone;
    }
    UIListContentConfiguration *content = [UIListContentConfiguration subtitleCellConfiguration];
    content.image = [UIImage systemImageNamed:indexPath.section == 0 ? @"exclamationmark.triangle.fill" : @"xmark.circle.fill"];
    content.imageProperties.tintColor = UIColor.systemRedColor;
    if (indexPath.section == 0) {
        content.text = self.report.summary;
        content.secondaryText = PXLocalizedFormat(@"diagnostics.summary.detail", [self.report localizedTimestamp], self.report.reference);
        cell.accessibilityIdentifier = @"environment-failure-summary";
    } else {
        PXEnvironmentFailureDiagnostic *diagnostic = self.report.diagnostics[(NSUInteger)indexPath.section - 1];
        content.text = diagnostic.stage;
        content.secondaryText = diagnostic.target.length > 0
            ? PXLocalizedFormat(@"diagnostics.failure.with_target", diagnostic.target, diagnostic.message)
            : diagnostic.message;
        content.secondaryText = [content.secondaryText stringByAppendingFormat:@"\n%@",
            PXLocalizedFormat(@"diagnostics.error.metadata",
                diagnostic.errorDomain,
                (long)diagnostic.errorCode)];
        cell.accessibilityIdentifier = [NSString stringWithFormat:@"environment-failure-%ld", (long)indexPath.section];
    }
    content.textProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleBody];
    content.secondaryTextProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleSubheadline];
    cell.contentConfiguration = content;
    cell.accessibilityLabel = PXLocalizedFormat(@"accessibility.state", content.text, content.secondaryText);
    cell.accessibilityTraits = UIAccessibilityTraitStaticText;
    return cell;
}

- (void)handleCopyTapped:(UIBarButtonItem *)sender {
    UIPasteboard.generalPasteboard.string = [self.report redactedTextRepresentation];
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, PXLocalizedString(@"diagnostics.copy.confirmation"));
}

- (void)handleCloseTapped:(UIBarButtonItem *)sender {
    [self dismissViewControllerAnimated:YES completion:nil];
}

@end
