// DESIGN SPEC — generated by Designer agent // Coder: implement TODO items, do not change component structure or accessibility attributes
#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface PXLanguageSelectionViewController : UITableViewController
@end

NS_ASSUME_NONNULL_END
