// DESIGN SPEC — generated by Designer agent // Preserve component structure and accessibility attributes.
#import "PXLanguageSelectionViewController.h"

#import "PXLocalizedStrings.h"

@implementation PXLanguageSelectionViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.title = PXLocalizedString(@"language.title");
    self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeNever;
    self.view.backgroundColor = UIColor.systemGroupedBackgroundColor;
    self.tableView.backgroundColor = UIColor.systemGroupedBackgroundColor;
    self.tableView.rowHeight = UITableViewAutomaticDimension;
    self.tableView.estimatedRowHeight = 56.0;
    self.tableView.cellLayoutMarginsFollowReadableWidth = YES;
    self.tableView.accessibilityIdentifier = @"language-selection-list";
    self.tableView.accessibilityLabel = PXLocalizedString(@"language.accessibility.list");
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(handleLanguagePreferenceChanged:) name:PXUILanguagePreferenceDidChangeNotification object:nil];
}

- (void)dealloc {
    [[NSNotificationCenter defaultCenter] removeObserver:self name:PXUILanguagePreferenceDidChangeNotification object:nil];
}

- (void)handleLanguagePreferenceChanged:(NSNotification *)notification {
    (void)notification;
    self.title = PXLocalizedString(@"language.title");
    self.tableView.accessibilityLabel = PXLocalizedString(@"language.accessibility.list");
    [self.tableView reloadData];
    if (self.view.window) {
        UIAccessibilityPostNotification(UIAccessibilityScreenChangedNotification, self.tableView);
    }
}

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView { return 1; }
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section { return 3; }
- (NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section { return PXLocalizedString(@"language.footer"); }

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    static NSString *const reuseIdentifier = @"LanguageOptionCell";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:reuseIdentifier];
    if (!cell) {
        cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:reuseIdentifier];
        cell.textLabel.adjustsFontForContentSizeCategory = YES;
        cell.detailTextLabel.adjustsFontForContentSizeCategory = YES;
        cell.detailTextLabel.numberOfLines = 2;
    }
    PXUILanguagePreference option = (PXUILanguagePreference)indexPath.row;
    BOOL isSelected = PXCurrentUILanguagePreference() == option;
    UIListContentConfiguration *content = [UIListContentConfiguration subtitleCellConfiguration];
    content.text = PXLocalizedString(PXUILanguagePreferenceTitleKey(option));
    content.secondaryText = PXLocalizedString(PXUILanguagePreferenceDetailKey(option));
    content.image = [UIImage systemImageNamed:option == PXUILanguagePreferenceSystem ? @"gear" : @"character.bubble"];
    content.imageProperties.tintColor = UIColor.systemBlueColor;
    content.textProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleBody];
    content.secondaryTextProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleSubheadline];
    cell.contentConfiguration = content;
    cell.accessoryType = isSelected ? UITableViewCellAccessoryCheckmark : UITableViewCellAccessoryNone;
    cell.accessibilityIdentifier = [NSString stringWithFormat:@"language-option-%ld", (long)option];
    cell.accessibilityLabel = PXLocalizedFormat(@"accessibility.settings.row", content.text, content.secondaryText);
    cell.accessibilityValue = isSelected ? PXLocalizedString(@"accessibility.selected") : PXLocalizedString(@"accessibility.not_selected");
    cell.accessibilityHint = PXLocalizedString(@"language.selection_hint");
    cell.accessibilityTraits = UIAccessibilityTraitButton | (isSelected ? UIAccessibilityTraitSelected : 0);
    return cell;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    PXSetUILanguagePreference((PXUILanguagePreference)indexPath.row);
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, PXLocalizedString(@"language.changed_announcement"));
}

@end
