// DESIGN SPEC — generated by Designer agent // Preserve system-selected localization behavior.
#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSInteger, PXUILanguagePreference) {
    PXUILanguagePreferenceSystem,
    PXUILanguagePreferenceSimplifiedChinese,
    PXUILanguagePreferenceEnglish
};

FOUNDATION_EXPORT NSNotificationName const PXUILanguagePreferenceDidChangeNotification;
FOUNDATION_EXPORT NSString *PXLocalizedString(NSString *key);
FOUNDATION_EXPORT NSString *PXLocalizedFormat(NSString *key, ...);
FOUNDATION_EXPORT PXUILanguagePreference PXCurrentUILanguagePreference(void);
FOUNDATION_EXPORT void PXSetUILanguagePreference(PXUILanguagePreference preference);
FOUNDATION_EXPORT NSString *PXUILanguagePreferenceTitleKey(PXUILanguagePreference preference);
FOUNDATION_EXPORT NSString *PXUILanguagePreferenceDetailKey(PXUILanguagePreference preference);

NS_ASSUME_NONNULL_END
