// DESIGN SPEC — generated by Designer agent // Preserve system-selected localization behavior.
#import "PXLocalizedStrings.h"

NSNotificationName const PXUILanguagePreferenceDidChangeNotification = @"PXUILanguagePreferenceDidChangeNotification";

static NSString *const PXUILanguagePreferenceDefaultsKey = @"PXUILanguagePreference";
static PXUILanguagePreference PXCurrentLanguagePreference = PXUILanguagePreferenceSystem;
static NSBundle *PXCurrentLocalizationBundle = nil;
static NSString *PXCurrentLocalizationIdentifier = nil;

static NSBundle *PXLocalizationResourceBundle(void) {
#if defined(PROJECTX_LOCALIZATION_TESTING)
    return [NSBundle bundleWithPath:NSFileManager.defaultManager.currentDirectoryPath];
#else
    return NSBundle.mainBundle;
#endif
}

static BOOL PXUILanguagePreferenceIsValid(PXUILanguagePreference preference) {
    return preference >= PXUILanguagePreferenceSystem &&
        preference <= PXUILanguagePreferenceEnglish;
}

static NSString *PXLocalizationIdentifierForPreference(PXUILanguagePreference preference) {
    if (preference == PXUILanguagePreferenceSimplifiedChinese) {
        return @"zh-Hans";
    }
    if (preference == PXUILanguagePreferenceEnglish) {
        return @"en";
    }
    NSArray<NSString *> *preferred = [NSBundle preferredLocalizationsFromArray:@[@"zh-Hans", @"en"]
                                                                 forPreferences:NSLocale.preferredLanguages];
    NSString *identifier = preferred.firstObject;
    return [identifier isEqualToString:@"zh-Hans"] ? @"zh-Hans" : @"en";
}

static void PXLoadUILanguagePreferenceIfNeeded(void) {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSUserDefaults *defaults = NSUserDefaults.standardUserDefaults;
        if ([defaults objectForKey:PXUILanguagePreferenceDefaultsKey]) {
            NSInteger storedValue = [defaults integerForKey:PXUILanguagePreferenceDefaultsKey];
            PXUILanguagePreference storedPreference = (PXUILanguagePreference)storedValue;
            if (PXUILanguagePreferenceIsValid(storedPreference)) {
                PXCurrentLanguagePreference = storedPreference;
            }
        }
    });
}

static NSBundle *PXLocalizationBundle(void) {
    PXLoadUILanguagePreferenceIfNeeded();
    NSBundle *resourceBundle = PXLocalizationResourceBundle();
    @synchronized (resourceBundle) {
        NSString *identifier = PXLocalizationIdentifierForPreference(PXCurrentLanguagePreference);
        if (![PXCurrentLocalizationIdentifier isEqualToString:identifier]) {
            NSString *bundlePath = [resourceBundle pathForResource:identifier ofType:@"lproj"];
            PXCurrentLocalizationBundle = bundlePath.length > 0
                ? [NSBundle bundleWithPath:bundlePath]
                : nil;
            PXCurrentLocalizationIdentifier = [identifier copy];
        }
        return PXCurrentLocalizationBundle;
    }
}

NSString *PXLocalizedString(NSString *key) {
    NSBundle *bundle = PXLocalizationBundle();
    NSString *localized = [bundle localizedStringForKey:key value:nil table:nil];
    if (localized.length > 0 && ![localized isEqualToString:key]) {
        return localized;
    }
    NSString *englishPath = [PXLocalizationResourceBundle() pathForResource:@"en" ofType:@"lproj"];
    NSBundle *englishBundle = englishPath.length > 0 ? [NSBundle bundleWithPath:englishPath] : nil;
    NSString *english = [englishBundle localizedStringForKey:key value:key table:nil];
    return english.length > 0 ? english : key;
}

NSString *PXLocalizedFormat(NSString *key, ...) {
    NSString *format = PXLocalizedString(key);
    va_list arguments;
    va_start(arguments, key);
    NSString *localizedValue = [[NSString alloc] initWithFormat:format
                                                           locale:NSLocale.currentLocale
                                                       arguments:arguments];
    va_end(arguments);
    return localizedValue;
}

PXUILanguagePreference PXCurrentUILanguagePreference(void) {
    PXLoadUILanguagePreferenceIfNeeded();
    return PXCurrentLanguagePreference;
}

void PXSetUILanguagePreference(PXUILanguagePreference preference) {
    if (!PXUILanguagePreferenceIsValid(preference)) {
        return;
    }
    PXLoadUILanguagePreferenceIfNeeded();
    @synchronized (PXLocalizationResourceBundle()) {
        PXCurrentLanguagePreference = preference;
        [NSUserDefaults.standardUserDefaults setInteger:preference
                                                 forKey:PXUILanguagePreferenceDefaultsKey];
        PXCurrentLocalizationBundle = nil;
        PXCurrentLocalizationIdentifier = nil;
        (void)PXLocalizationBundle();
    }
    void (^postChangeNotification)(void) = ^{
        [[NSNotificationCenter defaultCenter]
            postNotificationName:PXUILanguagePreferenceDidChangeNotification
                          object:nil];
    };
    if (NSThread.isMainThread) {
        postChangeNotification();
    } else {
        dispatch_async(dispatch_get_main_queue(), postChangeNotification);
    }
}

NSString *PXUILanguagePreferenceTitleKey(PXUILanguagePreference preference) {
    switch (preference) {
        case PXUILanguagePreferenceSimplifiedChinese: return @"language.option.simplified_chinese.title";
        case PXUILanguagePreferenceEnglish: return @"language.option.english.title";
        case PXUILanguagePreferenceSystem: return @"language.option.system.title";
    }
    return @"language.option.system.title";
}

NSString *PXUILanguagePreferenceDetailKey(PXUILanguagePreference preference) {
    switch (preference) {
        case PXUILanguagePreferenceSimplifiedChinese: return @"language.option.simplified_chinese.detail";
        case PXUILanguagePreferenceEnglish: return @"language.option.english.detail";
        case PXUILanguagePreferenceSystem: return @"language.option.system.detail";
    }
    return @"language.option.system.detail";
}
