// DESIGN SPEC — generated by Designer agent // Coder: implement TODO items, do not change component structure or accessibility attributes
#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSInteger, PXSafariTargetReadinessState) {
    PXSafariTargetReadinessStateUnknown,
    PXSafariTargetReadinessStateReady,
    PXSafariTargetReadinessStateInjectionUnavailable,
    PXSafariTargetReadinessStateWebKitAttributionUnavailable,
    PXSafariTargetReadinessStateSafariLibraryAccessUnavailable,
    PXSafariTargetReadinessStateCleanupPartiallyFailed,
    PXSafariTargetReadinessStateActiveGenerationMismatch
};

@interface PXSafariTargetReadiness : NSObject

@property (nonatomic, readonly) PXSafariTargetReadinessState state;

- (instancetype)initWithState:(PXSafariTargetReadinessState)state;

@end

@protocol PXSafariTargetReadinessProviding <NSObject>

- (PXSafariTargetReadiness *)currentSafariTargetReadiness;

@end

@interface PXUnavailableSafariTargetReadinessProvider : NSObject <PXSafariTargetReadinessProviding>
@end

NS_ASSUME_NONNULL_END
