// DESIGN SPEC — generated by Designer agent // Coder: implement TODO items, do not change component structure or accessibility attributes
#import "PXSafariTargetReadiness.h"

@interface PXSafariTargetReadiness ()
@property (nonatomic, readwrite) PXSafariTargetReadinessState state;
@end

@implementation PXSafariTargetReadiness

- (instancetype)initWithState:(PXSafariTargetReadinessState)state {
    self = [super init];
    if (self) {
        _state = state;
    }
    return self;
}

@end

@implementation PXUnavailableSafariTargetReadinessProvider

- (PXSafariTargetReadiness *)currentSafariTargetReadiness {
    // TODO: Query system-target eligibility, MobileSafari/WebKit process scope, Safari cleanup readiness, active generation, and atomic selection persistence capability together.
    return [[PXSafariTargetReadiness alloc] initWithState:PXSafariTargetReadinessStateUnknown];
}

@end
