// DESIGN SPEC — generated by Designer agent // Preserve component structure and accessibility attributes.
#import "PXSettingsHubViewController.h"

#import "CarrierSelectionViewController.h"
#import "DeviceModelManager.h"
#import "GraphicsIdentity.h"
#import "IdentifierManager.h"
#import "NetworkIdentity.h"
#import "PXEnvironmentModelSelection.h"
#import "PXEnvironmentPolicy.h"
#import "PXLanguageSelectionViewController.h"
#import "PXLocalizedStrings.h"
#import "PXRootHidePath.h"
#import "PXSmartLocationViewController.h"
#import "PXTargetAppsViewController.h"
#import "RegionIdentity.h"
#import "TrustedCarrierPolicy.h"

typedef NS_ENUM(NSInteger, PXSettingsSection) {
    PXSettingsSectionEnvironment,
    PXSettingsSectionAppScope,
    PXSettingsSectionGeneral,
    PXSettingsSectionCount
};

typedef NS_ENUM(NSInteger, PXEnvironmentRow) {
    PXEnvironmentRowModel,
    PXEnvironmentRowNetwork,
    PXEnvironmentRowCarrier,
    PXEnvironmentRowRegion,
    PXEnvironmentRowSmartLocation,
    PXEnvironmentRowCount
};

@class PXEnvironmentModelSelectorViewController;
@class PXNetworkTypeSelectorViewController;

static NSString *const PXModelCompatibilityIsCompatibleKey = @"isCompatible";
static NSString *const PXModelCompatibilityMismatchSummaryKey = @"mismatchSummary";
static const CGFloat PXSettingsAboutLogoSize = 32.0;

static NSString *PXLocalizedModelCompatibilityReason(NSError *error) {
    if (![error.domain isEqualToString:PXModelCompatibilityErrorDomain]) {
        return nil;
    }
    NSString *reason = [error.userInfo[PXModelCompatibilityReasonErrorKey]
        isKindOfClass:NSString.class]
        ? error.userInfo[PXModelCompatibilityReasonErrorKey]
        : @"";
    if ([reason isEqualToString:PXModelCompatibilityReasonPhysicalUnavailable]) {
        return PXLocalizedString(@"image.model.incompatible.reason.physical_unavailable");
    }
    if ([reason isEqualToString:PXModelCompatibilityReasonCandidateInvalid]) {
        return PXLocalizedString(@"image.model.incompatible.reason.candidate_invalid");
    }
    if ([reason isEqualToString:PXModelCompatibilityReasonHostCapabilitiesUnavailable]) {
        return PXLocalizedString(@"image.model.incompatible.reason.host_unavailable");
    }
    NSArray<NSString *> *mismatchFields =
        [error.userInfo[PXModelCompatibilityMismatchFieldsErrorKey] isKindOfClass:NSArray.class]
        ? error.userInfo[PXModelCompatibilityMismatchFieldsErrorKey]
        : @[];
    NSDictionary<NSString *, NSString *> *localizationKeyByField = @{
        PXModelCompatibilityFieldMarketingFamily: @"image.model.incompatible.field.marketing_family",
        PXModelCompatibilityFieldCPUClass: @"image.model.incompatible.field.cpu",
        PXModelCompatibilityFieldGraphicsClass: @"image.model.incompatible.field.graphics",
        PXModelCompatibilityFieldMemoryClass: @"image.model.incompatible.field.memory",
        PXModelCompatibilityFieldDisplayClass: @"image.model.incompatible.field.display",
        PXModelCompatibilityFieldHostGraphics: @"image.model.incompatible.field.host_graphics"
    };
    NSMutableArray<NSString *> *localizedFields = [NSMutableArray array];
    for (NSString *field in mismatchFields) {
        NSString *localizationKey = localizationKeyByField[field];
        if (localizationKey.length > 0) {
            [localizedFields addObject:PXLocalizedString(localizationKey)];
        }
    }
    if (localizedFields.count == 0) {
        return error.localizedDescription;
    }
    return PXLocalizedFormat(
        @"image.model.incompatible.reason.immutable_hardware",
        [localizedFields componentsJoinedByString:
            PXLocalizedString(@"image.model.incompatible.field_separator")]);
}

@protocol PXEnvironmentModelSelectorDelegate <NSObject>
- (void)environmentModelSelector:(PXEnvironmentModelSelectorViewController *)viewController didSelectModelIdentifier:(NSString *)modelIdentifier;
- (void)environmentModelSelectorDidSelectPhysicalDevice:(PXEnvironmentModelSelectorViewController *)viewController;
@end

@protocol PXNetworkTypeSelectorDelegate <NSObject>
- (void)networkTypeSelector:(PXNetworkTypeSelectorViewController *)viewController didSelectNetworkType:(PXEnvironmentNetworkType)networkType;
@end

@interface PXEnvironmentModelSelectorViewController : UITableViewController <UISearchResultsUpdating>
@property (nonatomic, weak) id<PXEnvironmentModelSelectorDelegate> delegate;
- (instancetype)initWithModelRecords:(NSArray<NSDictionary<NSString *, id> *> *)records
                  physicalModelRecord:(NSDictionary<NSString *, id> *)physicalModelRecord
                    usesPhysicalDevice:(BOOL)usesPhysicalDevice
                    selectedIdentifier:(nullable NSString *)selectedIdentifier
    compatibilityPresentationByIdentifier:(NSDictionary<NSString *, NSDictionary<NSString *, id> *> *)compatibilityPresentationByIdentifier;
@end

@interface PXNetworkTypeSelectorViewController : UITableViewController
@property (nonatomic, weak) id<PXNetworkTypeSelectorDelegate> delegate;
- (instancetype)initWithSelectedNetworkType:(PXEnvironmentNetworkType)selectedNetworkType
                                 modelRecord:(nullable NSDictionary<NSString *, id> *)modelRecord
                               carrierRecord:(nullable NSDictionary<NSString *, id> *)carrierRecord;
@end

@interface PXSettingsHubViewController () <PXEnvironmentModelSelectorDelegate, PXNetworkTypeSelectorDelegate, CarrierSelectionViewControllerDelegate>
@property (nonatomic, copy) NSString *modelSummary;
@property (nonatomic, copy) NSString *networkSummary;
@property (nonatomic, copy) NSString *carrierSummary;
@property (nonatomic, copy) NSString *regionSummary;
@property (nonatomic, copy) NSString *locationSummary;
@property (nonatomic, assign) NSInteger targetAppCount;
@property (nonatomic, strong) PXEnvironmentPolicyStore *environmentPolicyStore;
@property (nonatomic, copy, nullable) NSDictionary<NSString *, id> *selectedModelRecord;
@property (nonatomic, copy, nullable) NSDictionary<NSString *, id> *physicalModelRecord;
@property (nonatomic, assign) BOOL usesPhysicalDeviceModel;
@property (nonatomic, assign) PXEnvironmentNetworkType selectedNetworkType;
@property (nonatomic, copy, nullable) NSString *selectedCarrierID;
- (NSDictionary<NSString *, NSDictionary<NSString *, id> *> *)compatibilityPresentationByIdentifierForModelRecords:(NSArray<NSDictionary<NSString *, id> *> *)records
                                                                   physicalModelRecord:(NSDictionary<NSString *, id> *)physicalModelRecord;
@end

@implementation PXSettingsHubViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.title = PXLocalizedString(@"image.settings.title");
    self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeNever;
    self.view.backgroundColor = UIColor.systemGroupedBackgroundColor;
    self.tableView.backgroundColor = UIColor.systemGroupedBackgroundColor;
    self.tableView.rowHeight = UITableViewAutomaticDimension;
    self.tableView.estimatedRowHeight = 60.0;
    self.tableView.cellLayoutMarginsFollowReadableWidth = YES;
    self.tableView.accessibilityIdentifier = @"image-settings-list";
    self.tableView.accessibilityLabel = PXLocalizedString(@"image.settings.accessibility.list");
    self.tableView.tableHeaderView = [self pendingChangesBanner];
    self.environmentPolicyStore = [PXEnvironmentPolicyStore sharedStore];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(handleUILanguagePreferenceChanged:) name:PXUILanguagePreferenceDidChangeNotification object:nil];
    [self reloadPendingConfigurationSummaries];
}

- (void)dealloc {
    [[NSNotificationCenter defaultCenter] removeObserver:self name:PXUILanguagePreferenceDidChangeNotification object:nil];
}

- (void)handleUILanguagePreferenceChanged:(NSNotification *)notification {
    (void)notification;
    self.title = PXLocalizedString(@"image.settings.title");
    self.tableView.accessibilityLabel = PXLocalizedString(@"image.settings.accessibility.list");
    self.tableView.tableHeaderView = [self pendingChangesBanner];
    [self reloadPendingConfigurationSummaries];
    if (self.view.window) {
        UIAccessibilityPostNotification(UIAccessibilityScreenChangedNotification, self.tableView);
    }
}

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [self reloadPendingConfigurationSummaries];
}

- (UIView *)pendingChangesBanner {
    UIListContentConfiguration *content = [UIListContentConfiguration subtitleCellConfiguration];
    content.text = PXLocalizedString(@"image.settings.pending.title");
    content.secondaryText = PXLocalizedString(@"image.settings.pending.message");
    content.image = [UIImage systemImageNamed:@"info.circle.fill"];
    content.imageProperties.tintColor = UIColor.systemBlueColor;
    content.textProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleFootnote];
    content.secondaryTextProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleCaption1];
    UITableViewCell *cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:nil];
    cell.contentConfiguration = content;
    cell.backgroundColor = UIColor.secondarySystemGroupedBackgroundColor;
    cell.layer.cornerRadius = 12.0;
    cell.accessibilityLabel = PXLocalizedFormat(@"accessibility.state", content.text, content.secondaryText);
    cell.accessibilityTraits = UIAccessibilityTraitStaticText;
    UIView *container = [[UIView alloc] initWithFrame:CGRectMake(0.0, 0.0, UIScreen.mainScreen.bounds.size.width, 76.0)];
    cell.translatesAutoresizingMaskIntoConstraints = NO;
    [container addSubview:cell];
    [NSLayoutConstraint activateConstraints:@[
        [cell.topAnchor constraintEqualToAnchor:container.topAnchor constant:8.0],
        [cell.leadingAnchor constraintEqualToAnchor:container.layoutMarginsGuide.leadingAnchor],
        [cell.trailingAnchor constraintEqualToAnchor:container.layoutMarginsGuide.trailingAnchor],
        [cell.bottomAnchor constraintEqualToAnchor:container.bottomAnchor constant:-8.0]
    ]];
    return container;
}

- (void)reloadPendingConfigurationSummaries {
    NSError *policyError = nil;
    DeviceModelManager *deviceModelManager = DeviceModelManager.sharedManager;
    self.physicalModelRecord = [deviceModelManager physicalDeviceSpecificationRecord];
    self.selectedModelRecord = PXResolveEnvironmentModelSelection(
        self.environmentPolicyStore,
        [deviceModelManager allDeviceSpecificationRecords],
        self.physicalModelRecord,
        PXCurrentGraphicsHostCapabilities(),
        nil,
        &policyError);
    self.usesPhysicalDeviceModel = [self.environmentPolicyStore
        selectedModelSelectionModeWithError:&policyError] ==
        PXEnvironmentModelSelectionModePhysicalDevice;
    self.selectedNetworkType = [self.environmentPolicyStore selectedNetworkTypeWithError:&policyError];
    NSDictionary<NSString *, id> *location =
        [self.environmentPolicyStore configuredLocationWithError:&policyError];
    if (policyError) {
        [self presentPolicyError:policyError];
    }
    NSString *selectedModelName = [self.selectedModelRecord[@"name"] isKindOfClass:[NSString class]]
        ? self.selectedModelRecord[@"name"]
        : nil;
    self.modelSummary = self.usesPhysicalDeviceModel && selectedModelName.length > 0
        ? PXLocalizedFormat(@"image.model.use_this_device.summary", selectedModelName)
        : (selectedModelName ?: PXLocalizedString(@"image.summary.not_configured"));
    self.networkSummary = [self localizedNetworkType:self.selectedNetworkType];
    self.locationSummary = [location[@"address"] isKindOfClass:[NSString class]]
        ? location[@"address"]
        : PXLocalizedString(@"image.summary.not_configured");

    PXTrustedCarrierPolicyStore *carrierStore = [self currentCarrierPolicyStore];
    self.selectedCarrierID = [carrierStore selectedCarrierIDWithError:&policyError];
    NSDictionary<NSString *, id> *carrier = [self carrierRecordForIdentifier:self.selectedCarrierID];
    self.carrierSummary = [carrier[@"name"] isKindOfClass:[NSString class]]
        ? carrier[@"name"]
        : PXLocalizedString(@"image.summary.not_configured");
    PXRegionIdentity *region = carrier
        ? PXRegionIdentityForCountryCode(carrier[@"isoCountryCode"],
            [self.selectedCarrierID dataUsingEncoding:NSUTF8StringEncoding])
        : nil;
    self.regionSummary = region
        ? PXLocalizedFormat(@"image.settings.region.summary",
            carrier[@"country"], region.timeZoneIdentifier)
        : PXLocalizedString(@"image.summary.derived_after_carrier");

    IdentifierManager *manager = [IdentifierManager sharedManager];
    NSInteger selectedCount = 0;
    for (NSString *bundleIdentifier in [manager getApplicationInfo:nil]) {
        if ([manager isApplicationInScope:bundleIdentifier]) {
            selectedCount++;
        }
    }
    self.targetAppCount = selectedCount;
    [self.tableView reloadData];
}

- (nullable PXTrustedCarrierPolicyStore *)currentCarrierPolicyStore {
    NSDictionary *profileInfo = [NSDictionary dictionaryWithContentsOfFile:PXCurrentProfileInfoPath()];
    NSString *profileID = [profileInfo[@"ProfileId"] isKindOfClass:[NSString class]]
        ? profileInfo[@"ProfileId"]
        : nil;
    if (profileID.length == 0 || ![profileID isEqualToString:profileID.lastPathComponent]) {
        return nil;
    }
    return [[PXTrustedCarrierPolicyStore alloc] initWithProfileDirectory:PXProfileDirectoryPath(profileID)];
}

- (nullable NSDictionary<NSString *, id> *)carrierRecordForIdentifier:(NSString *)carrierID {
    if (carrierID.length == 0) return nil;
    for (NSDictionary<NSString *, id> *carrier in PXCarrierCatalog()) {
        if ([carrier[@"carrierID"] isEqualToString:carrierID]) {
            return carrier;
        }
    }
    return nil;
}

- (void)presentPolicyError:(NSError *)error {
    UIViewController *presenter = self.navigationController.topViewController ?: self;
    if (!presenter.view.window || presenter.presentedViewController) return;
    NSLog(@"[ProjectX] Pending environment settings error: %@", error.localizedDescription);
    NSString *compatibilityDescription = PXLocalizedModelCompatibilityReason(error);
    NSString *errorDescription = compatibilityDescription.length > 0
        ? compatibilityDescription
        : error.localizedDescription.length > 0
            ? error.localizedDescription
        : PXLocalizedString(@"image.settings.save_failed.description_unavailable");
    UIAlertController *alert = [UIAlertController
        alertControllerWithTitle:PXLocalizedString(@"image.settings.save_failed.title")
        message:PXLocalizedFormat(@"image.settings.save_failed.message_with_reason",
            errorDescription,
            PXLocalizedString(@"image.settings.save_failed.recovery"))
        preferredStyle:UIAlertControllerStyleAlert];
    [alert addAction:[UIAlertAction actionWithTitle:PXLocalizedString(@"navigation.close")
                                            style:UIAlertActionStyleCancel
                                          handler:nil]];
    [presenter presentViewController:alert animated:YES completion:nil];
}

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView { return PXSettingsSectionCount; }

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    if (section == PXSettingsSectionEnvironment) { return PXEnvironmentRowCount; }
    return section == PXSettingsSectionAppScope ? 1 : 2;
}

- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section {
    if (section == PXSettingsSectionEnvironment) { return PXLocalizedString(@"image.settings.section.environment"); }
    if (section == PXSettingsSectionAppScope) { return PXLocalizedString(@"image.settings.section.app_scope"); }
    return PXLocalizedString(@"image.settings.section.general");
}

- (NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section {
    return section == PXSettingsSectionEnvironment ? PXLocalizedString(@"image.settings.environment.footer") : nil;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    static NSString *const reuseIdentifier = @"ImageSettingsRow";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:reuseIdentifier];
    if (!cell) {
        cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:reuseIdentifier];
        cell.textLabel.adjustsFontForContentSizeCategory = YES;
        cell.detailTextLabel.adjustsFontForContentSizeCategory = YES;
        cell.detailTextLabel.numberOfLines = 2;
        cell.selectionStyle = UITableViewCellSelectionStyleDefault;
        cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    }
    UIListContentConfiguration *content = [UIListContentConfiguration subtitleCellConfiguration];
    NSString *identifier = nil;
    cell.selectionStyle = UITableViewCellSelectionStyleDefault;
    cell.accessoryType = UITableViewCellAccessoryDisclosureIndicator;
    if (indexPath.section == PXSettingsSectionEnvironment) {
        switch (indexPath.row) {
            case PXEnvironmentRowModel: content.text = PXLocalizedString(@"image.settings.model.title"); content.secondaryText = self.modelSummary; content.image = [UIImage systemImageNamed:@"iphone"]; identifier = @"image-settings-model"; break;
            case PXEnvironmentRowNetwork: content.text = PXLocalizedString(@"image.settings.network.title"); content.secondaryText = self.networkSummary; content.image = [UIImage systemImageNamed:@"wifi"]; identifier = @"image-settings-network"; break;
            case PXEnvironmentRowCarrier: content.text = PXLocalizedString(@"image.settings.carrier.title"); content.secondaryText = self.carrierSummary; content.image = [UIImage systemImageNamed:@"antenna.radiowaves.left.and.right"]; identifier = @"image-settings-carrier"; break;
            case PXEnvironmentRowRegion: content.text = PXLocalizedString(@"image.settings.region.title"); content.secondaryText = self.regionSummary; content.image = [UIImage systemImageNamed:@"location.north.line"]; identifier = @"image-settings-region"; cell.selectionStyle = UITableViewCellSelectionStyleNone; cell.accessoryType = UITableViewCellAccessoryNone; break;
            case PXEnvironmentRowSmartLocation: content.text = PXLocalizedString(@"image.settings.location.title"); content.secondaryText = self.locationSummary; content.image = [UIImage systemImageNamed:@"mappin.and.ellipse"]; identifier = @"image-settings-location"; break;
            default: break;
        }
    } else if (indexPath.section == PXSettingsSectionAppScope) {
        content.text = PXLocalizedString(@"image.settings.target_apps.title");
        content.secondaryText = PXLocalizedFormat(@"image.settings.target_apps.summary", (long)self.targetAppCount);
        content.image = [UIImage systemImageNamed:@"app.badge"]; identifier = @"image-settings-target-apps";
    } else if (indexPath.row == 0) {
        content.text = PXLocalizedString(@"image.settings.language.title");
        content.secondaryText = PXLocalizedString(PXUILanguagePreferenceTitleKey(PXCurrentUILanguagePreference()));
        content.image = [UIImage systemImageNamed:@"globe"]; identifier = @"image-settings-language";
    } else {
        content.text = PXLocalizedString(@"image.settings.about.title");
        NSString *version = [NSBundle.mainBundle objectForInfoDictionaryKey:@"CFBundleShortVersionString"] ?: @"";
        content.secondaryText = PXLocalizedFormat(@"image.settings.about.version_format", version);
        content.image = [[UIImage imageNamed:@"Icon"] imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
        content.imageProperties.maximumSize = CGSizeMake(PXSettingsAboutLogoSize,
                                                         PXSettingsAboutLogoSize);
        identifier = @"image-settings-about";
        cell.selectionStyle = UITableViewCellSelectionStyleNone;
        cell.accessoryType = UITableViewCellAccessoryNone;
    }
    content.imageProperties.tintColor = UIColor.systemBlueColor;
    content.textProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleBody];
    content.secondaryTextProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleSubheadline];
    cell.contentConfiguration = content;
    cell.accessibilityIdentifier = identifier;
    cell.accessibilityLabel = PXLocalizedFormat(@"accessibility.settings.row", content.text, content.secondaryText);
    cell.accessibilityHint = cell.selectionStyle == UITableViewCellSelectionStyleNone ? nil : PXLocalizedString(@"image.settings.open_hint");
    cell.accessibilityTraits = cell.selectionStyle == UITableViewCellSelectionStyleNone ? UIAccessibilityTraitStaticText : UIAccessibilityTraitButton;
    return cell;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    if (indexPath.section == PXSettingsSectionEnvironment) {
        if (indexPath.row == PXEnvironmentRowModel) { [self handleModelTapped]; }
        if (indexPath.row == PXEnvironmentRowNetwork) { [self handleNetworkTapped]; }
        if (indexPath.row == PXEnvironmentRowCarrier) { [self handleCarrierTapped]; }
        if (indexPath.row == PXEnvironmentRowSmartLocation) { [self handleSmartLocationTapped]; }
    } else if (indexPath.section == PXSettingsSectionAppScope) {
        [self handleTargetAppsTapped];
    } else if (indexPath.section == PXSettingsSectionGeneral && indexPath.row == 0) {
        [self handleLanguageTapped];
    }
}

- (void)handleLanguageTapped {
    [self.navigationController pushViewController:[[PXLanguageSelectionViewController alloc] initWithStyle:UITableViewStyleInsetGrouped] animated:YES];
}

- (void)handleModelTapped {
    NSArray<NSDictionary<NSString *, id> *> *modelRecords =
        [DeviceModelManager.sharedManager allDeviceSpecificationRecords];
    NSString *selectedIdentifier = !self.usesPhysicalDeviceModel &&
        [self.selectedModelRecord[@"identifier"] isKindOfClass:[NSString class]]
        ? self.selectedModelRecord[@"identifier"]
        : nil;
    PXEnvironmentModelSelectorViewController *controller = [[PXEnvironmentModelSelectorViewController alloc]
        initWithModelRecords:modelRecords
        physicalModelRecord:self.physicalModelRecord
        usesPhysicalDevice:self.usesPhysicalDeviceModel
        selectedIdentifier:selectedIdentifier
        compatibilityPresentationByIdentifier:[self
            compatibilityPresentationByIdentifierForModelRecords:modelRecords
            physicalModelRecord:self.physicalModelRecord]];
    controller.delegate = self;
    [self.navigationController pushViewController:controller animated:YES];
}

- (NSDictionary<NSString *, NSDictionary<NSString *, id> *> *)compatibilityPresentationByIdentifierForModelRecords:(NSArray<NSDictionary<NSString *, id> *> *)records
                                                                   physicalModelRecord:(NSDictionary<NSString *, id> *)physicalModelRecord {
    NSMutableDictionary<NSString *, NSDictionary<NSString *, id> *> *presentationByIdentifier =
        [NSMutableDictionary dictionary];
    NSDictionary<NSString *, id> *hostCapabilities = PXCurrentGraphicsHostCapabilities();

    for (NSDictionary<NSString *, id> *record in records) {
        NSString *identifier = [record[@"identifier"] isKindOfClass:NSString.class]
            ? record[@"identifier"]
            : @"";
        if (![identifier hasPrefix:@"iPhone"]) continue;
        NSError *compatibilityError = nil;
        BOOL isCompatible = PXModelRecordIsHardwareCompatibleWithPhysicalRecord(
            record,
            physicalModelRecord,
            hostCapabilities,
            &compatibilityError);
        NSString *mismatchSummary = isCompatible
            ? @""
            : PXLocalizedModelCompatibilityReason(compatibilityError);
        presentationByIdentifier[identifier] = @{
            PXModelCompatibilityIsCompatibleKey: @(isCompatible),
            PXModelCompatibilityMismatchSummaryKey: mismatchSummary.length > 0
                ? mismatchSummary
                : PXLocalizedString(@"image.model.incompatible.status_unavailable")
        };
    }

    return [presentationByIdentifier copy];
}

- (void)handleNetworkTapped {
    PXNetworkTypeSelectorViewController *controller = [[PXNetworkTypeSelectorViewController alloc]
        initWithSelectedNetworkType:self.selectedNetworkType
        modelRecord:self.selectedModelRecord
        carrierRecord:[self carrierRecordForIdentifier:self.selectedCarrierID]];
    controller.delegate = self;
    [self.navigationController pushViewController:controller animated:YES];
}

- (void)handleCarrierTapped {
    NSMutableArray<PXTrustedCarrierOption *> *options = [NSMutableArray array];
    for (NSDictionary<NSString *, id> *carrier in PXCarrierCatalog()) {
        NSString *identifier = [carrier[@"carrierID"] isKindOfClass:NSString.class] ? carrier[@"carrierID"] : nil;
        NSString *country = [carrier[@"country"] isKindOfClass:NSString.class] ? carrier[@"country"] : nil;
        NSString *name = [carrier[@"name"] isKindOfClass:NSString.class] ? carrier[@"name"] : nil;
        if (identifier.length > 0 && country.length > 0 && name.length > 0) {
            [options addObject:[[PXTrustedCarrierOption alloc] initWithStableIdentifier:identifier countryName:country carrierName:name]];
        }
    }
    NSSet<NSString *> *selection = self.selectedCarrierID
        ? [NSSet setWithObject:self.selectedCarrierID]
        : [NSSet set];
    CarrierSelectionViewController *controller = [[CarrierSelectionViewController alloc] initWithCarrierOptions:options selectedCarrierIDs:selection];
    controller.usesPushNavigation = YES;
    controller.delegate = self;
    [self.navigationController pushViewController:controller animated:YES];
}

- (void)handleSmartLocationTapped {
    PXSmartLocationViewController *controller = [[PXSmartLocationViewController alloc] initWithLocationCommittedHandler:@selector(handleCommittedLocationSummary:) target:self];
    [self.navigationController pushViewController:controller animated:YES];
}

- (void)handleTargetAppsTapped {
    PXTargetAppsViewController *controller = [[PXTargetAppsViewController alloc] initWithSelectedBundleIdentifiers:[NSSet set] completion:^(NSSet<NSString *> *selectedBundleIdentifiers) {
        [self handleImmediateTargetAppsSelection:selectedBundleIdentifiers];
    }];
    [self.navigationController pushViewController:controller animated:YES];
}

- (void)handleImmediateTargetAppsSelection:(NSSet<NSString *> *)selectedBundleIdentifiers {
    self.targetAppCount = selectedBundleIdentifiers.count;
    [self.tableView reloadData];
}

- (void)environmentModelSelector:(PXEnvironmentModelSelectorViewController *)viewController didSelectModelIdentifier:(NSString *)modelIdentifier {
    NSDictionary<NSString *, id> *selectedRecord = nil;
    for (NSDictionary<NSString *, id> *record in [DeviceModelManager.sharedManager allDeviceSpecificationRecords]) {
        if ([record[@"identifier"] isEqualToString:modelIdentifier]) {
            selectedRecord = record;
            break;
        }
    }
    NSError *error = nil;
    NSDictionary<NSString *, id> *candidateRecord = selectedRecord ?: @{};
    if (![self.environmentPolicyStore
        saveSelectedModelRecord:candidateRecord
        physicalModelRecord:self.physicalModelRecord
        hostGraphicsCapabilities:PXCurrentGraphicsHostCapabilities()
        error:&error]) {
        [self presentPolicyError:error ?: [NSError errorWithDomain:PXEnvironmentPolicyErrorDomain code:1 userInfo:nil]];
        return;
    }
    [self reloadPendingConfigurationSummaries];
}

- (void)environmentModelSelectorDidSelectPhysicalDevice:(PXEnvironmentModelSelectorViewController *)viewController {
    NSError *error = nil;
    NSDictionary<NSString *, id> *physicalModelRecord =
        [DeviceModelManager.sharedManager physicalDeviceSpecificationRecord];
    if (!physicalModelRecord ||
        ![self.environmentPolicyStore savePhysicalDeviceModelRecord:physicalModelRecord
                                                              error:&error]) {
        [self presentPolicyError:error ?: [NSError
            errorWithDomain:PXEnvironmentModelSelectionErrorDomain
                       code:1
                   userInfo:nil]];
        return;
    }
    [self reloadPendingConfigurationSummaries];
    UIAccessibilityPostNotification(
        UIAccessibilityAnnouncementNotification,
        PXLocalizedString(@"image.model.use_this_device.selected_announcement"));
}

- (void)networkTypeSelector:(PXNetworkTypeSelectorViewController *)viewController didSelectNetworkType:(PXEnvironmentNetworkType)networkType {
    NSError *error = nil;
    if (![self.environmentPolicyStore saveSelectedNetworkType:networkType
                                                   modelRecord:self.selectedModelRecord
                                                         error:&error]) {
        [self presentPolicyError:error];
        return;
    }
    [self reloadPendingConfigurationSummaries];
}

- (void)carrierSelectionViewController:(CarrierSelectionViewController *)viewController didCommitSelectedCarrierIDs:(NSSet<NSString *> *)selectedCarrierIDs {
    (void)selectedCarrierIDs;
    [self reloadPendingConfigurationSummaries];
}

- (BOOL)carrierSelectionViewController:(CarrierSelectionViewController *)viewController persistSelectedCarrierIDs:(NSSet<NSString *> *)selectedCarrierIDs {
    NSString *selectedCarrierID = [selectedCarrierIDs.allObjects
        sortedArrayUsingSelector:@selector(compare:)].firstObject;
    NSError *error = nil;
    PXTrustedCarrierPolicyStore *carrierStore = [self currentCarrierPolicyStore];
    if (!carrierStore || ![carrierStore saveSelectedCarrierID:selectedCarrierID error:&error]) {
        [self presentPolicyError:error ?: [NSError errorWithDomain:PXEnvironmentPolicyErrorDomain code:2 userInfo:nil]];
        return NO;
    }
    if (![self.environmentPolicyStore markPendingChangeWithError:&error]) {
        NSError *rollbackError = nil;
        if (self.selectedCarrierID.length > 0 &&
            ![carrierStore saveSelectedCarrierID:self.selectedCarrierID error:&rollbackError]) {
            NSLog(@"[ProjectX] Carrier selection rollback failed: %@",
                  rollbackError.localizedDescription);
        }
        [self presentPolicyError:error];
        return NO;
    }
    return YES;
}

- (BOOL)carrierSelectionViewController:(CarrierSelectionViewController *)viewController canCommitSelectedCarrierID:(NSString *)selectedCarrierID {
    NSDictionary<NSString *, id> *carrier = [self carrierRecordForIdentifier:selectedCarrierID];
    if (self.selectedNetworkType != PXEnvironmentNetworkType5GNR ||
        [self carrierRecordSupports5G:carrier]) {
        return YES;
    }
    UIAlertController *alert = [UIAlertController
        alertControllerWithTitle:PXLocalizedString(@"image.carrier.network_incompatible.title")
        message:PXLocalizedString(@"image.carrier.network_incompatible.message")
        preferredStyle:UIAlertControllerStyleAlert];
    [alert addAction:[UIAlertAction actionWithTitle:PXLocalizedString(@"navigation.close")
                                            style:UIAlertActionStyleCancel
                                          handler:nil]];
    [viewController presentViewController:alert animated:YES completion:nil];
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification,
                                    PXLocalizedString(@"image.carrier.network_incompatible.announcement"));
    return NO;
}

- (BOOL)carrierRecordSupports5G:(NSDictionary<NSString *, id> *)carrierRecord {
    return PXCarrierSupports5G(carrierRecord);
}

- (void)handleCommittedLocationSummary:(NSString *)summary {
    (void)summary;
    [self reloadPendingConfigurationSummaries];
}

- (NSString *)localizedNetworkType:(PXEnvironmentNetworkType)networkType {
    NSArray<NSString *> *keys = @[@"image.network.unspecified", @"image.network.wifi", @"image.network.5g", @"image.network.4g", @"image.network.3g", @"image.network.2g", @"image.network.none"];
    return PXLocalizedString(keys[(NSUInteger)networkType]);
}

@end

@interface PXEnvironmentModelSelectorViewController ()
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> *allRecords;
@property (nonatomic, copy) NSArray<NSDictionary<NSString *, id> *> *visibleRecords;
@property (nonatomic, copy) NSArray<NSString *> *visibleGroups;
@property (nonatomic, copy) NSDictionary<NSString *, NSArray<NSDictionary<NSString *, id> *> *> *recordsByGroup;
@property (nonatomic, copy, nullable) NSString *selectedIdentifier;
@property (nonatomic, strong) UISearchController *searchController;
@property (nonatomic, copy) NSDictionary<NSString *, id> *physicalModelRecord;
@property (nonatomic, copy) NSDictionary<NSString *, NSDictionary<NSString *, id> *> *compatibilityPresentationByIdentifier;
@property (nonatomic, assign) BOOL usesPhysicalDevice;
@end

@implementation PXEnvironmentModelSelectorViewController

- (instancetype)initWithModelRecords:(NSArray<NSDictionary<NSString *, id> *> *)records
                  physicalModelRecord:(NSDictionary<NSString *, id> *)physicalModelRecord
                    usesPhysicalDevice:(BOOL)usesPhysicalDevice
                    selectedIdentifier:(NSString *)selectedIdentifier
    compatibilityPresentationByIdentifier:(NSDictionary<NSString *, NSDictionary<NSString *, id> *> *)compatibilityPresentationByIdentifier {
    self = [super initWithStyle:UITableViewStyleInsetGrouped];
    if (self) {
        NSString *physicalIdentifier = [physicalModelRecord[@"identifier"] isKindOfClass:[NSString class]]
            ? physicalModelRecord[@"identifier"]
            : nil;
        _allRecords = [[records filteredArrayUsingPredicate:[NSPredicate
            predicateWithBlock:^BOOL(NSDictionary<NSString *, id> *record,
                                    NSDictionary<NSString *, id> *bindings) {
                (void)bindings;
                NSString *identifier = [record[@"identifier"] isKindOfClass:NSString.class]
                    ? record[@"identifier"]
                    : @"";
                return [identifier hasPrefix:@"iPhone"] &&
                    ![identifier isEqualToString:physicalIdentifier];
            }]] copy] ?: @[];
        _visibleRecords = _allRecords;
        _visibleGroups = @[];
        _recordsByGroup = @{};
        _selectedIdentifier = [selectedIdentifier copy];
        _physicalModelRecord = [physicalModelRecord copy];
        _compatibilityPresentationByIdentifier = [compatibilityPresentationByIdentifier copy] ?: @{};
        _usesPhysicalDevice = usesPhysicalDevice;
    }
    return self;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    self.title = PXLocalizedString(@"image.model.title");
    self.tableView.rowHeight = UITableViewAutomaticDimension;
    self.tableView.estimatedRowHeight = 96.0;
    self.tableView.cellLayoutMarginsFollowReadableWidth = YES;
    self.tableView.accessibilityIdentifier = @"image-model-selection-list";
    self.tableView.accessibilityLabel = PXLocalizedString(@"image.model.accessibility.list");
    self.searchController = [[UISearchController alloc] initWithSearchResultsController:nil];
    self.searchController.searchResultsUpdater = self;
    self.searchController.obscuresBackgroundDuringPresentation = NO;
    self.searchController.searchBar.placeholder = PXLocalizedString(@"image.model.search.placeholder");
    self.searchController.searchBar.accessibilityLabel = PXLocalizedString(@"image.model.search.accessibility_label");
    self.searchController.searchBar.accessibilityIdentifier = @"image-model-search";
    self.navigationItem.searchController = self.searchController;
    self.navigationItem.hidesSearchBarWhenScrolling = NO;
    self.definesPresentationContext = YES;
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(handleLanguagePreferenceChanged:)
                                                 name:PXUILanguagePreferenceDidChangeNotification
                                               object:nil];
    [self rebuildVisibleRecordsForQuery:@""];
}

- (void)dealloc {
    [[NSNotificationCenter defaultCenter] removeObserver:self
                                                    name:PXUILanguagePreferenceDidChangeNotification
                                                  object:nil];
}

- (void)handleLanguagePreferenceChanged:(NSNotification *)notification {
    (void)notification;
    self.title = PXLocalizedString(@"image.model.title");
    self.tableView.accessibilityLabel = PXLocalizedString(@"image.model.accessibility.list");
    self.searchController.searchBar.placeholder = PXLocalizedString(@"image.model.search.placeholder");
    self.searchController.searchBar.accessibilityLabel = PXLocalizedString(@"image.model.search.accessibility_label");
    [self rebuildVisibleRecordsForQuery:self.searchController.searchBar.text ?: @""];
    if (self.view.window) {
        UIAccessibilityPostNotification(UIAccessibilityScreenChangedNotification, self.tableView);
    }
}

- (void)updateSearchResultsForSearchController:(UISearchController *)searchController {
    NSString *query = [searchController.searchBar.text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];
    [self rebuildVisibleRecordsForQuery:query];
}

- (void)rebuildVisibleRecordsForQuery:(NSString *)query {
    self.visibleRecords = query.length == 0 ? self.allRecords : [self.allRecords filteredArrayUsingPredicate:[NSPredicate predicateWithBlock:^BOOL(NSDictionary<NSString *, id> *record, NSDictionary<NSString *, id> *bindings) {
        NSString *name = [record[@"name"] isKindOfClass:NSString.class] ? record[@"name"] : @"";
        NSString *identifier = [record[@"identifier"] isKindOfClass:NSString.class] ? record[@"identifier"] : @"";
        return [name localizedCaseInsensitiveContainsString:query] || [identifier localizedCaseInsensitiveContainsString:query];
    }]];
    NSMutableDictionary<NSString *, NSMutableArray<NSDictionary<NSString *, id> *> *> *grouped = [NSMutableDictionary dictionary];
    for (NSDictionary<NSString *, id> *record in self.visibleRecords) {
        NSString *name = [record[@"name"] isKindOfClass:[NSString class]] ? record[@"name"] : @"";
        NSArray<NSString *> *components = [name componentsSeparatedByString:@" "];
        NSString *group = components.count >= 2
            ? [NSString stringWithFormat:@"%@ %@", components[0], components[1]]
            : name;
        if (group.length == 0) group = PXLocalizedString(@"image.model.other_group");
        if (!grouped[group]) grouped[group] = [NSMutableArray array];
        [grouped[group] addObject:record];
    }
    self.visibleGroups = [grouped.allKeys sortedArrayUsingSelector:@selector(localizedCaseInsensitiveCompare:)];
    NSMutableDictionary<NSString *, NSArray<NSDictionary<NSString *, id> *> *> *recordsByGroup = [NSMutableDictionary dictionary];
    for (NSString *group in self.visibleGroups) {
        recordsByGroup[group] = [grouped[group] sortedArrayUsingComparator:^NSComparisonResult(NSDictionary<NSString *, id> *left, NSDictionary<NSString *, id> *right) {
            return [left[@"name"] localizedCaseInsensitiveCompare:right[@"name"]];
        }];
    }
    self.recordsByGroup = recordsByGroup;
    [self.tableView reloadData];
}

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView { return self.visibleGroups.count + 1; }
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section { return section == 0 ? 1 : self.recordsByGroup[self.visibleGroups[(NSUInteger)section - 1]].count; }
- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section { return section == 0 ? PXLocalizedString(@"image.model.use_this_device.section") : self.visibleGroups[(NSUInteger)section - 1]; }
- (NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section {
    if (section != self.visibleGroups.count) return nil;
    return PXLocalizedFormat(@"image.model.catalog.footer",
        (long)(self.visibleRecords.count + 1),
        PXLocalizedString(@"image.model.complete_identity.footer"));
}

- (NSString *)modelDetailForRecord:(NSDictionary<NSString *, id> *)record {
    NSString *identifier = [record[@"identifier"] isKindOfClass:NSString.class] ? record[@"identifier"] : @"";
    NSString *cpu = [record[@"cpuArchitecture"] isKindOfClass:NSString.class] ? record[@"cpuArchitecture"] : @"";
    NSString *gpu = [record[@"gpuFamily"] isKindOfClass:NSString.class] ? record[@"gpuFamily"] : @"";
    NSString *metal = [record[@"metalFeatureSet"] isKindOfClass:NSString.class] ? record[@"metalFeatureSet"] : @"";
    NSString *display = [record[@"screenResolution"] isKindOfClass:NSString.class] ? record[@"screenResolution"] : @"";
    NSArray<NSNumber *> *capacities = [record[@"supportedStorageCapacities"] isKindOfClass:NSArray.class]
        ? record[@"supportedStorageCapacities"]
        : @[];
    NSArray<NSString *> *capacityStrings = [capacities valueForKey:@"stringValue"];
    NSString *storage = [capacityStrings componentsJoinedByString:@" / "];
    return PXLocalizedFormat(@"image.model.complete_identity.detail",
        identifier, cpu, gpu, metal, display, storage);
}

- (NSDictionary<NSString *, id> *)compatibilityPresentationForIdentifier:(NSString *)identifier {
    NSDictionary<NSString *, id> *presentation =
        self.compatibilityPresentationByIdentifier[identifier];
    return [presentation isKindOfClass:NSDictionary.class] ? presentation : @{
        PXModelCompatibilityIsCompatibleKey: @NO,
        PXModelCompatibilityMismatchSummaryKey: PXLocalizedString(@"image.model.incompatible.status_unavailable")
    };
}

- (void)handleUseThisDeviceFromCompatibilityExplanation:(UIAlertAction *)action {
    (void)action;
    self.usesPhysicalDevice = YES;
    self.selectedIdentifier = nil;
    [self.delegate environmentModelSelectorDidSelectPhysicalDevice:self];
    [self.tableView reloadData];
}

- (void)presentIncompatibleModelExplanationForRecord:(NSDictionary<NSString *, id> *)record
                                      mismatchSummary:(NSString *)mismatchSummary {
    NSString *physicalName = [self.physicalModelRecord[@"name"] isKindOfClass:NSString.class]
        ? self.physicalModelRecord[@"name"]
        : PXLocalizedString(@"image.home.device.unknown");
    NSString *physicalIdentifier = [self.physicalModelRecord[@"identifier"] isKindOfClass:NSString.class]
        ? self.physicalModelRecord[@"identifier"]
        : @"";
    NSString *physicalGPU = [self.physicalModelRecord[@"gpuFamily"] isKindOfClass:NSString.class]
        ? self.physicalModelRecord[@"gpuFamily"]
        : PXLocalizedString(@"image.home.device.unknown");
    NSString *physicalMetal = [self.physicalModelRecord[@"metalFeatureSet"] isKindOfClass:NSString.class]
        ? self.physicalModelRecord[@"metalFeatureSet"]
        : PXLocalizedString(@"image.home.device.unknown");
    NSString *modelName = [record[@"name"] isKindOfClass:NSString.class]
        ? record[@"name"]
        : PXLocalizedString(@"image.home.device.unknown");
    NSString *modelIdentifier = [record[@"identifier"] isKindOfClass:NSString.class]
        ? record[@"identifier"]
        : @"";
    NSString *modelGPU = [record[@"gpuFamily"] isKindOfClass:NSString.class]
        ? record[@"gpuFamily"]
        : PXLocalizedString(@"image.home.device.unknown");
    NSString *modelMetal = [record[@"metalFeatureSet"] isKindOfClass:NSString.class]
        ? record[@"metalFeatureSet"]
        : PXLocalizedString(@"image.home.device.unknown");
    UIAlertController *alert = [UIAlertController
        alertControllerWithTitle:PXLocalizedString(@"image.model.incompatible.alert.title")
        message:PXLocalizedFormat(@"image.model.incompatible.alert.message",
            physicalName,
            physicalIdentifier,
            physicalGPU,
            physicalMetal,
            modelName,
            modelIdentifier,
            modelGPU,
            modelMetal,
            mismatchSummary)
        preferredStyle:UIAlertControllerStyleAlert];
    UIAlertAction *useThisDeviceAction = [UIAlertAction
        actionWithTitle:PXLocalizedString(@"image.model.incompatible.use_this_device.action")
                  style:UIAlertActionStyleDefault
                handler:^(UIAlertAction *action) {
                    [self handleUseThisDeviceFromCompatibilityExplanation:action];
                }];
    UIAlertAction *closeAction = [UIAlertAction
        actionWithTitle:PXLocalizedString(@"navigation.close")
                  style:UIAlertActionStyleCancel
                handler:nil];
    [alert addAction:useThisDeviceAction];
    [alert addAction:closeAction];
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification,
                                    PXLocalizedString(@"image.model.incompatible.announcement"));
    [self presentViewController:alert animated:YES completion:nil];
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    static NSString *const reuseIdentifier = @"ImageModelCell";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:reuseIdentifier] ?: [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:reuseIdentifier];
    if (indexPath.section == 0) {
        NSString *physicalName = [self.physicalModelRecord[@"name"] isKindOfClass:[NSString class]]
            ? self.physicalModelRecord[@"name"]
            : PXLocalizedString(@"image.home.device.unknown");
        NSString *physicalIdentifier = [self.physicalModelRecord[@"identifier"] isKindOfClass:[NSString class]]
            ? self.physicalModelRecord[@"identifier"]
            : @"";
        NSString *physicalGPU = [self.physicalModelRecord[@"gpuFamily"] isKindOfClass:NSString.class]
            ? self.physicalModelRecord[@"gpuFamily"]
            : PXLocalizedString(@"image.home.device.unknown");
        NSString *physicalMetal = [self.physicalModelRecord[@"metalFeatureSet"] isKindOfClass:NSString.class]
            ? self.physicalModelRecord[@"metalFeatureSet"]
            : PXLocalizedString(@"image.home.device.unknown");
        UIListContentConfiguration *content = [UIListContentConfiguration subtitleCellConfiguration];
        content.text = PXLocalizedString(@"image.model.use_this_device.title");
        content.secondaryText = PXLocalizedFormat(
            @"image.model.use_this_device.detail",
            physicalName,
            physicalIdentifier,
            physicalGPU,
            physicalMetal);
        content.image = [UIImage systemImageNamed:@"iphone.gen3"];
        content.imageProperties.tintColor = UIColor.systemGreenColor;
        content.textProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleBody];
        content.secondaryTextProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleSubheadline];
        content.secondaryTextProperties.numberOfLines = 3;
        cell.contentConfiguration = content;
        cell.accessoryType = self.usesPhysicalDevice
            ? UITableViewCellAccessoryCheckmark
            : UITableViewCellAccessoryNone;
        cell.userInteractionEnabled = YES;
        cell.selectionStyle = UITableViewCellSelectionStyleDefault;
        cell.accessibilityIdentifier = @"image-model-use-this-device";
        cell.accessibilityLabel = PXLocalizedFormat(@"accessibility.settings.row", content.text, content.secondaryText);
        cell.accessibilityValue = self.usesPhysicalDevice
            ? PXLocalizedString(@"accessibility.selected")
            : PXLocalizedString(@"accessibility.not_selected");
        cell.accessibilityHint = PXLocalizedString(@"image.model.use_this_device.selection_hint");
        cell.accessibilityTraits = UIAccessibilityTraitButton |
            (self.usesPhysicalDevice ? UIAccessibilityTraitSelected : 0);
        return cell;
    }
    NSDictionary<NSString *, id> *record = self.recordsByGroup[self.visibleGroups[(NSUInteger)indexPath.section - 1]][(NSUInteger)indexPath.row];
    NSString *identifier = [record[@"identifier"] isKindOfClass:NSString.class] ? record[@"identifier"] : @"";
    NSString *name = [record[@"name"] isKindOfClass:NSString.class] ? record[@"name"] : identifier;
    NSDictionary<NSString *, id> *compatibilityPresentation =
        [self compatibilityPresentationForIdentifier:identifier];
    BOOL isCompatible = [compatibilityPresentation[PXModelCompatibilityIsCompatibleKey] boolValue];
    NSString *mismatchSummary = [compatibilityPresentation[PXModelCompatibilityMismatchSummaryKey]
        isKindOfClass:NSString.class]
        ? compatibilityPresentation[PXModelCompatibilityMismatchSummaryKey]
        : PXLocalizedString(@"image.model.incompatible.status_unavailable");
    UIListContentConfiguration *content = [UIListContentConfiguration subtitleCellConfiguration];
    content.text = name;
    NSString *modelDetail = [self modelDetailForRecord:record];
    content.secondaryText = isCompatible
        ? modelDetail
        : PXLocalizedFormat(@"image.model.incompatible.detail", modelDetail, mismatchSummary);
    content.image = [UIImage systemImageNamed:@"iphone"];
    content.imageProperties.tintColor = isCompatible ? UIColor.systemBlueColor : UIColor.systemOrangeColor;
    content.textProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleBody];
    content.secondaryTextProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleSubheadline];
    content.secondaryTextProperties.color = isCompatible ? UIColor.secondaryLabelColor : UIColor.labelColor;
    content.secondaryTextProperties.numberOfLines = isCompatible ? 3 : 4;
    BOOL selected = isCompatible && [identifier isEqualToString:self.selectedIdentifier];
    cell.accessoryType = selected ? UITableViewCellAccessoryCheckmark : UITableViewCellAccessoryNone;
    cell.userInteractionEnabled = YES;
    cell.selectionStyle = UITableViewCellSelectionStyleDefault;
    cell.contentConfiguration = content;
    cell.accessibilityIdentifier = [NSString stringWithFormat:@"image-model-%@", identifier];
    cell.accessibilityLabel = PXLocalizedFormat(@"accessibility.settings.row", name, content.secondaryText);
    cell.accessibilityValue = isCompatible
        ? (selected ? PXLocalizedString(@"accessibility.selected") : PXLocalizedString(@"accessibility.not_selected"))
        : PXLocalizedString(@"image.model.incompatible.status_unavailable");
    cell.accessibilityHint = isCompatible
        ? PXLocalizedString(@"image.model.selection_hint")
        : PXLocalizedString(@"image.model.incompatible.explanation_hint");
    cell.accessibilityTraits = UIAccessibilityTraitButton | (selected ? UIAccessibilityTraitSelected : 0);
    return cell;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    if (indexPath.section == 0) {
        self.usesPhysicalDevice = YES;
        self.selectedIdentifier = nil;
        [self.delegate environmentModelSelectorDidSelectPhysicalDevice:self];
        [self.tableView reloadData];
        return;
    }
    NSDictionary<NSString *, id> *record = self.recordsByGroup[self.visibleGroups[(NSUInteger)indexPath.section - 1]][(NSUInteger)indexPath.row];
    NSString *identifier = [record[@"identifier"] isKindOfClass:NSString.class] ? record[@"identifier"] : nil;
    if (identifier.length == 0) { return; }
    NSDictionary<NSString *, id> *compatibilityPresentation =
        [self compatibilityPresentationForIdentifier:identifier];
    BOOL isCompatible = [compatibilityPresentation[PXModelCompatibilityIsCompatibleKey] boolValue];
    if (!isCompatible) {
        NSString *mismatchSummary = [compatibilityPresentation[PXModelCompatibilityMismatchSummaryKey]
            isKindOfClass:NSString.class]
            ? compatibilityPresentation[PXModelCompatibilityMismatchSummaryKey]
            : PXLocalizedString(@"image.model.incompatible.status_unavailable");
        [self presentIncompatibleModelExplanationForRecord:record mismatchSummary:mismatchSummary];
        return;
    }
    self.usesPhysicalDevice = NO;
    self.selectedIdentifier = identifier;
    [self.delegate environmentModelSelector:self didSelectModelIdentifier:identifier];
    [self.tableView reloadData];
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, PXLocalizedString(@"image.model.selected_announcement"));
}
@end

@interface PXNetworkTypeSelectorViewController ()
@property (nonatomic, assign) PXEnvironmentNetworkType selectedNetworkType;
@property (nonatomic, copy, nullable) NSDictionary<NSString *, id> *modelRecord;
@property (nonatomic, copy, nullable) NSDictionary<NSString *, id> *carrierRecord;
@end

@implementation PXNetworkTypeSelectorViewController
- (instancetype)initWithSelectedNetworkType:(PXEnvironmentNetworkType)selectedNetworkType modelRecord:(NSDictionary<NSString *,id> *)modelRecord carrierRecord:(NSDictionary<NSString *,id> *)carrierRecord { self = [super initWithStyle:UITableViewStyleInsetGrouped]; if (self) { _selectedNetworkType = selectedNetworkType; _modelRecord = [modelRecord copy]; _carrierRecord = [carrierRecord copy]; } return self; }
- (void)viewDidLoad { [super viewDidLoad]; self.title = PXLocalizedString(@"image.network.title"); self.tableView.rowHeight = 56.0; self.tableView.accessibilityLabel = PXLocalizedString(@"image.network.accessibility.list"); [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(handleLanguagePreferenceChanged:) name:PXUILanguagePreferenceDidChangeNotification object:nil]; }
- (void)dealloc { [[NSNotificationCenter defaultCenter] removeObserver:self name:PXUILanguagePreferenceDidChangeNotification object:nil]; }
- (void)handleLanguagePreferenceChanged:(NSNotification *)notification { (void)notification; self.title = PXLocalizedString(@"image.network.title"); self.tableView.accessibilityLabel = PXLocalizedString(@"image.network.accessibility.list"); [self.tableView reloadData]; if (self.view.window) { UIAccessibilityPostNotification(UIAccessibilityScreenChangedNotification, self.tableView); } }
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section { return 6; }
- (NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section { return PXLocalizedString(@"image.network.footer"); }
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    static NSString *const reuseIdentifier = @"ImageNetworkCell";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:reuseIdentifier] ?: [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:reuseIdentifier];
    PXEnvironmentNetworkType type = (PXEnvironmentNetworkType)indexPath.row + 1;
    NSArray<NSString *> *keys = @[@"image.network.wifi", @"image.network.5g", @"image.network.4g", @"image.network.3g", @"image.network.2g", @"image.network.none"];
    NSArray<NSString *> *symbols = @[@"wifi", @"cellularbars", @"cellularbars", @"cellularbars", @"cellularbars", @"wifi.slash"];
    UIListContentConfiguration *content = [UIListContentConfiguration cellConfiguration]; content.text = PXLocalizedString(keys[(NSUInteger)indexPath.row]); content.image = [UIImage systemImageNamed:symbols[(NSUInteger)indexPath.row]]; content.imageProperties.tintColor = UIColor.systemBlueColor; cell.contentConfiguration = content;
    BOOL selected = type == self.selectedNetworkType; BOOL compatible = [self isNetworkTypeCompatible:type]; cell.accessoryType = selected ? UITableViewCellAccessoryCheckmark : UITableViewCellAccessoryNone; cell.userInteractionEnabled = compatible; content.textProperties.color = compatible ? UIColor.labelColor : UIColor.tertiaryLabelColor; cell.contentConfiguration = content;
    cell.accessibilityLabel = content.text; cell.accessibilityValue = selected ? PXLocalizedString(@"accessibility.selected") : compatible ? PXLocalizedString(@"accessibility.not_selected") : PXLocalizedString(@"image.network.unsupported"); cell.accessibilityHint = compatible ? PXLocalizedString(@"image.network.selection_hint") : nil; cell.accessibilityTraits = compatible ? UIAccessibilityTraitButton | (selected ? UIAccessibilityTraitSelected : 0) : UIAccessibilityTraitNotEnabled; return cell;
}
- (BOOL)isNetworkTypeCompatible:(PXEnvironmentNetworkType)networkType { if (!PXEnvironmentNetworkTypeIsCompatibleWithModelRecord(networkType, self.modelRecord)) return NO; return networkType != PXEnvironmentNetworkType5GNR || !self.carrierRecord || PXCarrierSupports5G(self.carrierRecord); }
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath { [tableView deselectRowAtIndexPath:indexPath animated:YES]; PXEnvironmentNetworkType networkType = (PXEnvironmentNetworkType)indexPath.row + 1; if (![self isNetworkTypeCompatible:networkType]) { UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, PXLocalizedString(@"image.network.unsupported_announcement")); return; } self.selectedNetworkType = networkType; [self.delegate networkTypeSelector:self didSelectNetworkType:self.selectedNetworkType]; [self.tableView reloadData]; UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, PXLocalizedString(@"image.network.selected_announcement")); }
@end
