// DESIGN SPEC — generated by Designer agent // Preserve component structure and accessibility attributes.
#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface PXSettingsHubViewController : UITableViewController
@end

NS_ASSUME_NONNULL_END
