// DESIGN SPEC — generated by Designer agent // Preserve component structure and accessibility attributes.
#import "PXSmartLocationViewController.h"

#import <MapKit/MapKit.h>

#import "NetworkIdentity.h"
#import "PXEnvironmentPolicy.h"
#import "PXLocalizedStrings.h"
#import "PXRootHidePath.h"
#import "TrustedCarrierPolicy.h"

@interface PXSmartLocationViewController () <UISearchBarDelegate, CLLocationManagerDelegate>
@property (nonatomic, weak) id callbackTarget;
@property (nonatomic, assign) SEL callbackSelector;
@property (nonatomic, strong) UISearchBar *searchBar;
@property (nonatomic, strong) MKMapView *mapView;
@property (nonatomic, strong) UILabel *addressLabel;
@property (nonatomic, strong) UILabel *coordinateLabel;
@property (nonatomic, strong) UILabel *mismatchLabel;
@property (nonatomic, strong) UIButton *currentLocationButton;
@property (nonatomic, strong) UIButton *clearLocationButton;
@property (nonatomic, strong) UIButton *useLocationButton;
@property (nonatomic, strong) CLGeocoder *geocoder;
@property (nonatomic, strong) CLLocationManager *locationManager;
@property (nonatomic, strong, nullable) CLLocation *displayedLocation;
@property (nonatomic, copy, nullable) NSString *displayedAddress;
@property (nonatomic, copy, nullable) NSString *displayedCountryCode;
@property (nonatomic, strong) PXEnvironmentPolicyStore *environmentPolicyStore;
@end

@implementation PXSmartLocationViewController

- (instancetype)initWithLocationCommittedHandler:(SEL)handler target:(id)target {
    self = [super initWithNibName:nil bundle:nil];
    if (self) { _callbackSelector = handler; _callbackTarget = target; }
    return self;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    self.title = PXLocalizedString(@"image.location.title");
    self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeNever;
    self.view.backgroundColor = UIColor.systemBackgroundColor;
    self.geocoder = [[CLGeocoder alloc] init];
    self.environmentPolicyStore = [PXEnvironmentPolicyStore sharedStore];
    [self buildLocationInterface];
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(handleLanguagePreferenceChanged:)
                                                 name:PXUILanguagePreferenceDidChangeNotification
                                               object:nil];
    [self restoreConfiguredLocation];
}

- (void)dealloc {
    [[NSNotificationCenter defaultCenter] removeObserver:self
                                                    name:PXUILanguagePreferenceDidChangeNotification
                                                  object:nil];
}

- (void)handleLanguagePreferenceChanged:(NSNotification *)notification {
    (void)notification;
    self.title = PXLocalizedString(@"image.location.title");
    self.searchBar.placeholder = PXLocalizedString(@"image.location.search.placeholder");
    self.searchBar.accessibilityLabel = PXLocalizedString(@"image.location.search.accessibility_label");
    self.mapView.accessibilityLabel = PXLocalizedString(@"image.location.map.accessibility_label");
    self.currentLocationButton.accessibilityLabel = PXLocalizedString(@"image.location.current.accessibility_label");
    self.currentLocationButton.accessibilityHint = PXLocalizedString(@"image.location.current.accessibility_hint");
    self.mismatchLabel.text = PXLocalizedString(@"image.location.mismatch.warning");
    UIButtonConfiguration *clearConfiguration = self.clearLocationButton.configuration;
    clearConfiguration.title = PXLocalizedString(@"image.location.clear.title");
    self.clearLocationButton.configuration = clearConfiguration;
    self.clearLocationButton.accessibilityLabel = PXLocalizedString(@"image.location.clear.accessibility_label");
    self.clearLocationButton.accessibilityHint = PXLocalizedString(@"image.location.clear.accessibility_hint");
    UIButtonConfiguration *useConfiguration = self.useLocationButton.configuration;
    useConfiguration.title = PXLocalizedString(@"image.location.use.title");
    self.useLocationButton.configuration = useConfiguration;
    self.useLocationButton.accessibilityLabel = PXLocalizedString(@"image.location.use.accessibility_label");
    self.useLocationButton.accessibilityHint = PXLocalizedString(@"image.location.use.accessibility_hint");
    if (!self.displayedLocation) {
        self.addressLabel.text = PXLocalizedString(@"image.location.address.placeholder");
        self.coordinateLabel.text = PXLocalizedString(@"image.location.coordinates.placeholder");
    }
    if (self.view.window) {
        UIAccessibilityPostNotification(UIAccessibilityScreenChangedNotification, self.view);
    }
}

- (void)buildLocationInterface {
    self.searchBar = [[UISearchBar alloc] init];
    self.searchBar.translatesAutoresizingMaskIntoConstraints = NO;
    self.searchBar.delegate = self;
    self.searchBar.placeholder = PXLocalizedString(@"image.location.search.placeholder");
    self.searchBar.accessibilityLabel = PXLocalizedString(@"image.location.search.accessibility_label");
    self.searchBar.accessibilityIdentifier = @"image-location-search";
    [self.view addSubview:self.searchBar];

    MKMapView *mapSurface = [[MKMapView alloc] init];
    mapSurface.translatesAutoresizingMaskIntoConstraints = NO;
    mapSurface.accessibilityLabel = PXLocalizedString(@"image.location.map.accessibility_label");
    mapSurface.showsCompass = YES;
    mapSurface.showsScale = YES;
    self.mapView = mapSurface;
    [self.view addSubview:mapSurface];

    UILongPressGestureRecognizer *pinGesture = [[UILongPressGestureRecognizer alloc]
        initWithTarget:self
        action:@selector(handleMapLongPress:)];
    [mapSurface addGestureRecognizer:pinGesture];

    UIButton *currentLocationButton = [UIButton buttonWithType:UIButtonTypeSystem];
    currentLocationButton.translatesAutoresizingMaskIntoConstraints = NO;
    currentLocationButton.configuration = [UIButtonConfiguration tintedButtonConfiguration];
    currentLocationButton.configuration.image = [UIImage systemImageNamed:@"location.fill"];
    currentLocationButton.accessibilityLabel = PXLocalizedString(@"image.location.current.accessibility_label");
    currentLocationButton.accessibilityHint = PXLocalizedString(@"image.location.current.accessibility_hint");
    currentLocationButton.accessibilityIdentifier = @"image-location-current";
    [currentLocationButton addTarget:self action:@selector(handleCurrentLocationTapped:) forControlEvents:UIControlEventTouchUpInside];
    self.currentLocationButton = currentLocationButton;
    [mapSurface addSubview:currentLocationButton];

    UIView *detailsCard = [[UIView alloc] init];
    detailsCard.translatesAutoresizingMaskIntoConstraints = NO;
    detailsCard.backgroundColor = UIColor.systemBackgroundColor;
    detailsCard.layer.cornerRadius = 14.0;
    [self.view addSubview:detailsCard];

    self.addressLabel = [self detailLabelWithStyle:UIFontTextStyleHeadline];
    self.addressLabel.text = PXLocalizedString(@"image.location.address.placeholder");
    self.coordinateLabel = [self detailLabelWithStyle:UIFontTextStyleFootnote];
    self.coordinateLabel.text = PXLocalizedString(@"image.location.coordinates.placeholder");
    [detailsCard addSubview:self.addressLabel];
    [detailsCard addSubview:self.coordinateLabel];

    self.mismatchLabel = [self detailLabelWithStyle:UIFontTextStyleFootnote];
    self.mismatchLabel.text = PXLocalizedString(@"image.location.mismatch.warning");
    self.mismatchLabel.textColor = UIColor.systemOrangeColor;
    self.mismatchLabel.numberOfLines = 0;
    self.mismatchLabel.accessibilityTraits = UIAccessibilityTraitStaticText;
    self.mismatchLabel.hidden = YES;
    [detailsCard addSubview:self.mismatchLabel];

    UIButton *clearButton = [UIButton buttonWithType:UIButtonTypeSystem];
    clearButton.translatesAutoresizingMaskIntoConstraints = NO;
    UIButtonConfiguration *clearConfiguration = [UIButtonConfiguration plainButtonConfiguration];
    clearConfiguration.title = PXLocalizedString(@"image.location.clear.title");
    clearConfiguration.image = [UIImage systemImageNamed:@"trash"];
    clearConfiguration.imagePadding = 8.0;
    clearConfiguration.baseForegroundColor = UIColor.systemRedColor;
    clearButton.configuration = clearConfiguration;
    clearButton.accessibilityLabel = PXLocalizedString(@"image.location.clear.accessibility_label");
    clearButton.accessibilityHint = PXLocalizedString(@"image.location.clear.accessibility_hint");
    [clearButton addTarget:self action:@selector(handleClearLocationTapped:) forControlEvents:UIControlEventTouchUpInside];
    self.clearLocationButton = clearButton;
    [detailsCard addSubview:clearButton];

    self.useLocationButton = [UIButton buttonWithType:UIButtonTypeSystem];
    self.useLocationButton.translatesAutoresizingMaskIntoConstraints = NO;
    UIButtonConfiguration *useConfiguration = [UIButtonConfiguration filledButtonConfiguration];
    useConfiguration.title = PXLocalizedString(@"image.location.use.title");
    useConfiguration.image = [UIImage systemImageNamed:@"location.fill"];
    useConfiguration.imagePadding = 8.0;
    useConfiguration.cornerStyle = UIButtonConfigurationCornerStyleLarge;
    useConfiguration.baseBackgroundColor = UIColor.systemBlueColor;
    useConfiguration.baseForegroundColor = UIColor.whiteColor;
    self.useLocationButton.configuration = useConfiguration;
    self.useLocationButton.accessibilityIdentifier = @"image-location-use";
    self.useLocationButton.accessibilityLabel = PXLocalizedString(@"image.location.use.accessibility_label");
    self.useLocationButton.accessibilityHint = PXLocalizedString(@"image.location.use.accessibility_hint");
    [self.useLocationButton addTarget:self action:@selector(handleUseLocationTapped:) forControlEvents:UIControlEventTouchUpInside];
    [self.view addSubview:self.useLocationButton];

    [NSLayoutConstraint activateConstraints:@[
        [self.searchBar.topAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.topAnchor constant:8.0],
        [self.searchBar.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor constant:12.0],
        [self.searchBar.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor constant:-12.0],
        [mapSurface.topAnchor constraintEqualToAnchor:self.searchBar.bottomAnchor constant:8.0],
        [mapSurface.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor],
        [mapSurface.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor],
        [mapSurface.bottomAnchor constraintEqualToAnchor:detailsCard.topAnchor constant:-12.0],
        [mapSurface.heightAnchor constraintGreaterThanOrEqualToConstant:180.0],
        [currentLocationButton.trailingAnchor constraintEqualToAnchor:mapSurface.trailingAnchor constant:-16.0],
        [currentLocationButton.bottomAnchor constraintEqualToAnchor:mapSurface.bottomAnchor constant:-16.0],
        [currentLocationButton.widthAnchor constraintGreaterThanOrEqualToConstant:44.0],
        [currentLocationButton.heightAnchor constraintGreaterThanOrEqualToConstant:44.0],
        [detailsCard.leadingAnchor constraintEqualToAnchor:self.view.layoutMarginsGuide.leadingAnchor],
        [detailsCard.trailingAnchor constraintEqualToAnchor:self.view.layoutMarginsGuide.trailingAnchor],
        [self.addressLabel.topAnchor constraintEqualToAnchor:detailsCard.topAnchor constant:14.0],
        [self.addressLabel.leadingAnchor constraintEqualToAnchor:detailsCard.layoutMarginsGuide.leadingAnchor],
        [self.addressLabel.trailingAnchor constraintEqualToAnchor:detailsCard.layoutMarginsGuide.trailingAnchor],
        [self.coordinateLabel.topAnchor constraintEqualToAnchor:self.addressLabel.bottomAnchor constant:4.0],
        [self.coordinateLabel.leadingAnchor constraintEqualToAnchor:detailsCard.layoutMarginsGuide.leadingAnchor],
        [self.coordinateLabel.trailingAnchor constraintEqualToAnchor:detailsCard.layoutMarginsGuide.trailingAnchor],
        [self.mismatchLabel.topAnchor constraintEqualToAnchor:self.coordinateLabel.bottomAnchor constant:12.0],
        [self.mismatchLabel.leadingAnchor constraintEqualToAnchor:detailsCard.layoutMarginsGuide.leadingAnchor],
        [self.mismatchLabel.trailingAnchor constraintEqualToAnchor:detailsCard.layoutMarginsGuide.trailingAnchor],
        [clearButton.topAnchor constraintEqualToAnchor:self.mismatchLabel.bottomAnchor constant:8.0],
        [clearButton.leadingAnchor constraintEqualToAnchor:detailsCard.layoutMarginsGuide.leadingAnchor],
        [clearButton.bottomAnchor constraintEqualToAnchor:detailsCard.bottomAnchor constant:-8.0],
        [self.useLocationButton.topAnchor constraintEqualToAnchor:detailsCard.bottomAnchor constant:12.0],
        [self.useLocationButton.leadingAnchor constraintEqualToAnchor:self.view.layoutMarginsGuide.leadingAnchor],
        [self.useLocationButton.trailingAnchor constraintEqualToAnchor:self.view.layoutMarginsGuide.trailingAnchor],
        [self.useLocationButton.bottomAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.bottomAnchor constant:-12.0],
        [self.useLocationButton.heightAnchor constraintGreaterThanOrEqualToConstant:48.0]
    ]];
}

- (UILabel *)detailLabelWithStyle:(UIFontTextStyle)style {
    UILabel *label = [[UILabel alloc] init];
    label.translatesAutoresizingMaskIntoConstraints = NO;
    label.font = [UIFont preferredFontForTextStyle:style];
    label.adjustsFontForContentSizeCategory = YES;
    label.numberOfLines = 0;
    return label;
}

- (void)searchBarSearchButtonClicked:(UISearchBar *)searchBar {
    [searchBar resignFirstResponder];
    NSString *query = [searchBar.text stringByTrimmingCharactersInSet:
        NSCharacterSet.whitespaceAndNewlineCharacterSet];
    if (query.length == 0) return;
    [self.geocoder cancelGeocode];
    [self.geocoder geocodeAddressString:query completionHandler:^(NSArray<CLPlacemark *> *placemarks,
                                                                  NSError *error) {
        dispatch_async(dispatch_get_main_queue(), ^{
            CLPlacemark *placemark = placemarks.firstObject;
            if ([error.domain isEqualToString:kCLErrorDomain] &&
                error.code == kCLErrorGeocodeCanceled) {
                return;
            }
            if (!placemark.location || error) {
                [self presentLocationError:error];
                return;
            }
            [self displayPlacemark:placemark fallbackAddress:query];
        });
    }];
}

- (void)handleCurrentLocationTapped:(UIButton *)sender {
    if (!self.locationManager) {
        self.locationManager = [[CLLocationManager alloc] init];
        self.locationManager.delegate = self;
        self.locationManager.desiredAccuracy = kCLLocationAccuracyHundredMeters;
    }
    CLAuthorizationStatus status = self.locationManager.authorizationStatus;
    if (status == kCLAuthorizationStatusNotDetermined) {
        [self.locationManager requestWhenInUseAuthorization];
    } else if (status == kCLAuthorizationStatusAuthorizedAlways ||
               status == kCLAuthorizationStatusAuthorizedWhenInUse) {
        [self.locationManager requestLocation];
    } else {
        [self presentLocationError:nil];
    }
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, PXLocalizedString(@"image.location.current.announcement"));
}

- (void)handleClearLocationTapped:(UIButton *)sender {
    NSError *error = nil;
    if (![self.environmentPolicyStore clearConfiguredLocationWithError:&error]) {
        [self presentLocationError:error];
        return;
    }
    self.displayedLocation = nil;
    self.displayedAddress = nil;
    self.displayedCountryCode = nil;
    [self.mapView removeAnnotations:self.mapView.annotations];
    self.addressLabel.text = PXLocalizedString(@"image.location.address.cleared");
    self.coordinateLabel.text = PXLocalizedString(@"image.location.coordinates.cleared");
    self.mismatchLabel.hidden = YES;
    [self notifyCommittedSummary:self.addressLabel.text];
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, PXLocalizedString(@"image.location.clear.announcement"));
}

- (void)handleUseLocationTapped:(UIButton *)sender {
    if (!self.displayedLocation) {
        [self presentLocationError:nil];
        return;
    }
    NSMutableDictionary<NSString *, id> *location = [@{
        @"latitude": @(self.displayedLocation.coordinate.latitude),
        @"longitude": @(self.displayedLocation.coordinate.longitude),
        @"address": self.displayedAddress ?: self.addressLabel.text ?: @""
    } mutableCopy];
    if (self.displayedCountryCode.length > 0) {
        location[@"countryCode"] = self.displayedCountryCode.uppercaseString;
    }
    NSError *error = nil;
    if (![self.environmentPolicyStore saveConfiguredLocation:location error:&error]) {
        [self presentLocationError:error];
        return;
    }
    [self notifyCommittedSummary:location[@"address"]];
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, PXLocalizedString(@"image.location.use.announcement"));
}

- (void)handleMapLongPress:(UILongPressGestureRecognizer *)recognizer {
    if (recognizer.state != UIGestureRecognizerStateBegan) return;
    CGPoint point = [recognizer locationInView:self.mapView];
    CLLocationCoordinate2D coordinate = [self.mapView convertPoint:point toCoordinateFromView:self.mapView];
    if (!CLLocationCoordinate2DIsValid(coordinate)) return;
    [self reverseGeocodeLocation:[[CLLocation alloc] initWithLatitude:coordinate.latitude
                                                           longitude:coordinate.longitude]];
}

- (void)locationManagerDidChangeAuthorization:(CLLocationManager *)manager {
    CLAuthorizationStatus status = manager.authorizationStatus;
    if (status == kCLAuthorizationStatusAuthorizedAlways ||
        status == kCLAuthorizationStatusAuthorizedWhenInUse) {
        [manager requestLocation];
    }
}

- (void)locationManager:(CLLocationManager *)manager didUpdateLocations:(NSArray<CLLocation *> *)locations {
    CLLocation *location = locations.lastObject;
    if (location) {
        [self reverseGeocodeLocation:location];
    }
}

- (void)locationManager:(CLLocationManager *)manager didFailWithError:(NSError *)error {
    [self presentLocationError:error];
}

- (void)reverseGeocodeLocation:(CLLocation *)location {
    [self.geocoder cancelGeocode];
    [self.geocoder reverseGeocodeLocation:location completionHandler:^(NSArray<CLPlacemark *> *placemarks,
                                                                       NSError *error) {
        dispatch_async(dispatch_get_main_queue(), ^{
            CLPlacemark *placemark = placemarks.firstObject;
            if (!placemark || error) {
                [self displayLocation:location
                              address:PXLocalizedString(@"image.location.address.unknown")
                          countryCode:nil];
                return;
            }
            [self displayPlacemark:placemark fallbackAddress:nil];
        });
    }];
}

- (void)displayPlacemark:(CLPlacemark *)placemark fallbackAddress:(NSString *)fallbackAddress {
    NSMutableArray<NSString *> *addressParts = [NSMutableArray array];
    for (NSString *part in @[placemark.name ?: @"", placemark.locality ?: @"",
                             placemark.administrativeArea ?: @"", placemark.country ?: @""]) {
        if (part.length > 0 && ![addressParts containsObject:part]) {
            [addressParts addObject:part];
        }
    }
    NSString *address = addressParts.count > 0
        ? [addressParts componentsJoinedByString:@", "]
        : (fallbackAddress ?: PXLocalizedString(@"image.location.address.unknown"));
    [self displayLocation:placemark.location address:address countryCode:placemark.ISOcountryCode];
}

- (void)displayLocation:(CLLocation *)location
                 address:(NSString *)address
             countryCode:(NSString *)countryCode {
    self.displayedLocation = location;
    self.displayedAddress = address;
    self.displayedCountryCode = countryCode.uppercaseString;
    self.addressLabel.text = address;
    self.coordinateLabel.text = [NSString stringWithFormat:@"%.4f, %.4f",
        location.coordinate.latitude, location.coordinate.longitude];
    [self.mapView removeAnnotations:self.mapView.annotations];
    MKPointAnnotation *annotation = [[MKPointAnnotation alloc] init];
    annotation.coordinate = location.coordinate;
    annotation.title = address;
    [self.mapView addAnnotation:annotation];
    [self.mapView setRegion:MKCoordinateRegionMakeWithDistance(location.coordinate, 12000.0, 12000.0)
                   animated:YES];
    [self updateCarrierMismatchWarning];
}

- (void)restoreConfiguredLocation {
    NSDictionary<NSString *, id> *location = [self.environmentPolicyStore configuredLocationWithError:nil];
    if (![location[@"latitude"] isKindOfClass:[NSNumber class]] ||
        ![location[@"longitude"] isKindOfClass:[NSNumber class]]) {
        return;
    }
    CLLocation *savedLocation = [[CLLocation alloc]
        initWithLatitude:[location[@"latitude"] doubleValue]
        longitude:[location[@"longitude"] doubleValue]];
    NSString *address = [location[@"address"] isKindOfClass:[NSString class]]
        ? location[@"address"]
        : PXLocalizedString(@"image.location.address.unknown");
    NSString *countryCode = [location[@"countryCode"] isKindOfClass:[NSString class]]
        ? location[@"countryCode"]
        : nil;
    [self displayLocation:savedLocation address:address countryCode:countryCode];
}

- (void)updateCarrierMismatchWarning {
    NSDictionary *profileInfo = [NSDictionary dictionaryWithContentsOfFile:PXCurrentProfileInfoPath()];
    NSString *profileID = [profileInfo[@"ProfileId"] isKindOfClass:[NSString class]]
        ? profileInfo[@"ProfileId"]
        : nil;
    if (profileID.length == 0 || ![profileID isEqualToString:profileID.lastPathComponent] ||
        self.displayedCountryCode.length == 0) {
        self.mismatchLabel.hidden = YES;
        return;
    }
    PXTrustedCarrierPolicyStore *store = [[PXTrustedCarrierPolicyStore alloc]
        initWithProfileDirectory:PXProfileDirectoryPath(profileID)];
    NSString *carrierID = [store selectedCarrierIDWithError:nil];
    NSString *carrierCountryCode = nil;
    for (NSDictionary<NSString *, id> *carrier in PXCarrierCatalog()) {
        if ([carrier[@"carrierID"] isEqualToString:carrierID]) {
            carrierCountryCode = [carrier[@"isoCountryCode"] uppercaseString];
            break;
        }
    }
    self.mismatchLabel.hidden = carrierCountryCode.length == 0 ||
        [carrierCountryCode isEqualToString:self.displayedCountryCode];
}

- (void)notifyCommittedSummary:(NSString *)summary {
    if (self.callbackTarget && self.callbackSelector &&
        [self.callbackTarget respondsToSelector:self.callbackSelector]) {
        void (*callback)(id, SEL, NSString *) =
            (void (*)(id, SEL, NSString *))[self.callbackTarget methodForSelector:self.callbackSelector];
        callback(self.callbackTarget, self.callbackSelector, summary);
    }
}

- (void)presentLocationError:(NSError *)error {
    if (self.presentedViewController) return;
    if (error) {
        NSLog(@"[ProjectX] Smart Location error: %@", error.localizedDescription);
    }
    UIAlertController *alert = [UIAlertController
        alertControllerWithTitle:PXLocalizedString(@"image.location.error.title")
        message:PXLocalizedString(@"image.location.error.message")
        preferredStyle:UIAlertControllerStyleAlert];
    [alert addAction:[UIAlertAction actionWithTitle:PXLocalizedString(@"navigation.close")
                                            style:UIAlertActionStyleCancel
                                          handler:nil]];
    [self presentViewController:alert animated:YES completion:nil];
}

@end
