// DESIGN SPEC — generated by Designer agent // Preserve component structure and accessibility attributes.
#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface PXSmartLocationViewController : UIViewController

- (instancetype)initWithLocationCommittedHandler:(SEL)handler target:(id)target;

@end

NS_ASSUME_NONNULL_END
