// DESIGN SPEC — generated by Designer agent // Coder: implement specified behavior, do not change component structure or accessibility attributes
#import "PXTargetAppsViewController.h"

#import "IdentifierManager.h"
#import "ProjectXLogging.h"
#import "PXLocalizedStrings.h"
#import "PXTargetAppEligibility.h"
#import "PXTargetSelectionServices.h"

typedef NS_ENUM(NSInteger, PXTargetAppsViewState) {
    PXTargetAppsViewStateLoading,
    PXTargetAppsViewStateReady,
    PXTargetAppsViewStateNoEligibleApps,
    PXTargetAppsViewStateSearchEmpty,
    PXTargetAppsViewStateEnumerationFailure
};

@interface PXTargetApp : NSObject

@property (nonatomic, copy) NSString *displayName;
@property (nonatomic, copy) NSString *bundleIdentifier;
@property (nonatomic, strong, nullable) UIImage *icon;
@property (nonatomic, assign) NSInteger eligibleExtensionCount;
@property (nonatomic, assign) BOOL isSystemApp;
@property (nonatomic, assign) BOOL isSafariTarget;

@end

@implementation PXTargetApp
@end

@interface PXTargetAppsViewController () <UITableViewDataSource, UITableViewDelegate, UISearchResultsUpdating>

@property (nonatomic, strong) UITableView *tableView;
@property (nonatomic, strong) UISearchController *searchController;
@property (nonatomic, copy) NSArray<PXTargetApp *> *allApps;
@property (nonatomic, copy) NSArray<PXTargetApp *> *visibleUserApps;
@property (nonatomic, copy) NSArray<PXTargetApp *> *visibleSystemApps;
@property (nonatomic, copy) NSArray<NSArray<PXTargetApp *> *> *visibleSections;
@property (nonatomic, copy) NSArray<NSString *> *visibleSectionTitleKeys;
@property (nonatomic, strong) NSMutableSet<NSString *> *selectedBundleIdentifiers;
@property (nonatomic, copy) PXTargetAppsSelectionCompletion selectionCompletion;
@property (nonatomic, assign) PXTargetAppsViewState viewState;
@property (nonatomic, strong) id<PXSafariTargetReadinessProviding> safariReadinessProvider;
@property (nonatomic, strong) PXSafariTargetReadiness *safariReadiness;
@property (nonatomic, strong) PXTargetSelectionReconciler *targetSelectionReconciler;

@end

@implementation PXTargetAppsViewController

- (instancetype)initWithSelectedBundleIdentifiers:(NSSet<NSString *> *)selectedBundleIdentifiers
                                         completion:(PXTargetAppsSelectionCompletion)completion {
    return [self initWithSelectedBundleIdentifiers:selectedBundleIdentifiers
                                         completion:completion
                           safariReadinessProvider:[[PXUnavailableSafariTargetReadinessProvider alloc] init]];
}

- (instancetype)initWithSelectedBundleIdentifiers:(NSSet<NSString *> *)selectedBundleIdentifiers
                                         completion:(PXTargetAppsSelectionCompletion)completion
                           safariReadinessProvider:(id<PXSafariTargetReadinessProviding>)safariReadinessProvider {
    PXTargetSelectionServices *services = [PXTargetSelectionServices sharedServices];
    return [self initWithSelectedBundleIdentifiers:selectedBundleIdentifiers
                                         completion:completion
                           safariReadinessProvider:safariReadinessProvider
                         targetSelectionReconciler:services.reconciler];
}

- (instancetype)initWithSelectedBundleIdentifiers:(NSSet<NSString *> *)selectedBundleIdentifiers
                                         completion:(PXTargetAppsSelectionCompletion)completion
                           safariReadinessProvider:(id<PXSafariTargetReadinessProviding>)safariReadinessProvider
                         targetSelectionReconciler:(PXTargetSelectionReconciler *)targetSelectionReconciler {
    self = [super initWithNibName:nil bundle:nil];
    if (self) {
        _selectedBundleIdentifiers = [selectedBundleIdentifiers mutableCopy] ?: [NSMutableSet set];
        _selectionCompletion = [completion copy];
        _allApps = @[];
        _visibleUserApps = @[];
        _visibleSystemApps = @[];
        _visibleSections = @[];
        _visibleSectionTitleKeys = @[];
        _viewState = PXTargetAppsViewStateLoading;
        _safariReadinessProvider = safariReadinessProvider ?: [[PXUnavailableSafariTargetReadinessProvider alloc] init];
        _safariReadiness = [[PXSafariTargetReadiness alloc] initWithState:PXSafariTargetReadinessStateUnknown];
        _targetSelectionReconciler = targetSelectionReconciler;
    }
    return self;
}

- (void)viewDidLoad {
    [super viewDidLoad];
    self.title = PXLocalizedString(@"image.target_apps.title");
    self.navigationItem.largeTitleDisplayMode = UINavigationItemLargeTitleDisplayModeNever;
    self.view.backgroundColor = UIColor.systemGroupedBackgroundColor;
    [self configureTableView];
    [self configureSearch];
    [self refreshSafariReadiness];
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(handleLanguagePreferenceChanged:)
                                                 name:PXUILanguagePreferenceDidChangeNotification
                                               object:nil];
    [self loadLocalApps];
}

- (void)dealloc {
    [[NSNotificationCenter defaultCenter] removeObserver:self
                                                    name:PXUILanguagePreferenceDidChangeNotification
                                                  object:nil];
}

- (void)handleLanguagePreferenceChanged:(NSNotification *)notification {
    (void)notification;
    self.title = PXLocalizedString(@"image.target_apps.title");
    self.tableView.accessibilityLabel = PXLocalizedString(@"image.target_apps.accessibility.list");
    self.searchController.searchBar.placeholder = PXLocalizedString(@"image.target_apps.search.placeholder");
    self.searchController.searchBar.accessibilityLabel = PXLocalizedString(@"image.target_apps.search.accessibility_label");
    [self refreshSafariReadiness];
    [self.tableView reloadData];
    if (self.view.window) {
        UIAccessibilityPostNotification(UIAccessibilityScreenChangedNotification, self.tableView);
    }
}

- (void)configureTableView {
    self.tableView = [[UITableView alloc] initWithFrame:CGRectZero style:UITableViewStyleInsetGrouped];
    self.tableView.translatesAutoresizingMaskIntoConstraints = NO;
    self.tableView.dataSource = self;
    self.tableView.delegate = self;
    self.tableView.backgroundColor = UIColor.systemGroupedBackgroundColor;
    self.tableView.cellLayoutMarginsFollowReadableWidth = YES;
    self.tableView.rowHeight = UITableViewAutomaticDimension;
    self.tableView.estimatedRowHeight = 64.0;
    self.tableView.allowsMultipleSelection = YES;
    self.tableView.accessibilityIdentifier = @"image-target-apps-list";
    self.tableView.accessibilityLabel = PXLocalizedString(@"image.target_apps.accessibility.list");
    [self.view addSubview:self.tableView];
    [NSLayoutConstraint activateConstraints:@[
        [self.tableView.topAnchor constraintEqualToAnchor:self.view.safeAreaLayoutGuide.topAnchor],
        [self.tableView.leadingAnchor constraintEqualToAnchor:self.view.leadingAnchor],
        [self.tableView.trailingAnchor constraintEqualToAnchor:self.view.trailingAnchor],
        [self.tableView.bottomAnchor constraintEqualToAnchor:self.view.bottomAnchor]
    ]];
}

- (void)configureSearch {
    self.searchController = [[UISearchController alloc] initWithSearchResultsController:nil];
    self.searchController.searchResultsUpdater = self;
    self.searchController.obscuresBackgroundDuringPresentation = NO;
    self.searchController.searchBar.placeholder = PXLocalizedString(@"image.target_apps.search.placeholder");
    self.searchController.searchBar.accessibilityLabel = PXLocalizedString(@"image.target_apps.search.accessibility_label");
    self.searchController.searchBar.accessibilityIdentifier = @"image-target-apps-search";
    self.navigationItem.searchController = self.searchController;
    self.navigationItem.hidesSearchBarWhenScrolling = NO;
    self.definesPresentationContext = YES;
}

- (void)loadLocalApps {
    self.viewState = PXTargetAppsViewStateLoading;
    [self.tableView reloadData];
    dispatch_async(dispatch_get_global_queue(QOS_CLASS_USER_INITIATED, 0), ^{
        NSError *snapshotError = nil;
        PXTargetSelectionReconciliationResult *reconciliation =
            [self.targetSelectionReconciler reconcileWithError:&snapshotError];
        PXInstalledAppSnapshot *snapshot = reconciliation.snapshot;
        if (!reconciliation) {
            PXLog(@"[target-reconciliation] Installed Target state preserved: domain=%@ code=%ld message=%@",
                  snapshotError.domain ?: PXTargetSelectionReconciliationErrorDomain,
                  (long)snapshotError.code,
                  snapshotError.localizedDescription ?: @"Installed Target enumeration is unavailable");
            dispatch_async(dispatch_get_main_queue(), ^{
                [self handleLocalAppEnumerationFailure];
            });
            return;
        }

        NSArray<NSDictionary<NSString *, id> *> *eligibleCandidates =
            PXEligibleTargetAppCandidates(snapshot.applicationCandidates);
        NSMutableArray<PXTargetApp *> *apps = [NSMutableArray array];
        for (NSDictionary<NSString *, id> *candidate in eligibleCandidates) {
            PXTargetApp *app = [[PXTargetApp alloc] init];
            app.displayName = candidate[@"displayName"];
            app.bundleIdentifier = candidate[@"bundleIdentifier"];
            app.isSystemApp = [candidate[@"applicationType"] isEqualToString:@"System"];
            app.isSafariTarget = PXTargetAppCandidateIsMobileSafari(candidate);
            NSURL *bundleURL = candidate[@"bundleURL"];
            app.icon = [self iconForBundleURL:bundleURL];
            app.eligibleExtensionCount = [self eligibleExtensionCountForBundleURL:bundleURL];
            [apps addObject:app];
        }
        NSSet<NSString *> *selectedBundleIdentifiers = reconciliation.selectedBundleIdentifiers;
        dispatch_async(dispatch_get_main_queue(), ^{
            self.selectedBundleIdentifiers = [selectedBundleIdentifiers mutableCopy];
            [self handleLocalAppEnumerationSucceededWithApps:apps];
            if (self.selectionCompletion) {
                self.selectionCompletion([selectedBundleIdentifiers copy]);
            }
        });
    });
}

- (nullable UIImage *)iconForBundleURL:(NSURL *)bundleURL {
    NSDictionary<NSString *, id> *info = [NSDictionary dictionaryWithContentsOfURL:
        [bundleURL URLByAppendingPathComponent:@"Info.plist"]];
    NSDictionary *icons = [info[@"CFBundleIcons"] isKindOfClass:[NSDictionary class]]
        ? info[@"CFBundleIcons"]
        : nil;
    NSDictionary *primaryIcon = [icons[@"CFBundlePrimaryIcon"] isKindOfClass:[NSDictionary class]]
        ? icons[@"CFBundlePrimaryIcon"]
        : nil;
    NSArray<NSString *> *iconFiles = [primaryIcon[@"CFBundleIconFiles"] isKindOfClass:[NSArray class]]
        ? primaryIcon[@"CFBundleIconFiles"]
        : ([info[@"CFBundleIconFiles"] isKindOfClass:[NSArray class]] ? info[@"CFBundleIconFiles"] : @[]);
    NSString *iconName = iconFiles.lastObject;
    NSMutableArray<NSString *> *candidateNames = [NSMutableArray array];
    if (iconName.length > 0) {
        [candidateNames addObjectsFromArray:@[
            iconName,
            [iconName stringByAppendingPathExtension:@"png"],
            [iconName stringByAppendingString:@"@2x.png"],
            [iconName stringByAppendingString:@"@3x.png"]
        ]];
    }
    NSArray<NSString *> *bundleContents = [[[NSFileManager defaultManager]
        contentsOfDirectoryAtPath:bundleURL.path
        error:nil] sortedArrayUsingSelector:@selector(localizedCaseInsensitiveCompare:)];
    for (NSString *entry in bundleContents) {
        if ([entry.pathExtension.lowercaseString isEqualToString:@"png"] &&
            [entry.lowercaseString containsString:@"icon"]) {
            [candidateNames addObject:entry];
        }
    }
    for (NSString *candidateName in candidateNames) {
        UIImage *icon = [UIImage imageWithContentsOfFile:
            [bundleURL.path stringByAppendingPathComponent:candidateName]];
        if (icon) {
            return icon;
        }
    }
    return nil;
}

- (NSInteger)eligibleExtensionCountForBundleURL:(NSURL *)bundleURL {
    NSString *pluginsPath = [bundleURL.path stringByAppendingPathComponent:@"PlugIns"];
    NSArray<NSString *> *contents = [[NSFileManager defaultManager]
        contentsOfDirectoryAtPath:pluginsPath
        error:nil];
    NSUInteger count = 0;
    for (NSString *entry in contents) {
        if ([entry.pathExtension.lowercaseString isEqualToString:@"appex"]) {
            count++;
        }
    }
    return (NSInteger)count;
}

- (void)handleLocalAppEnumerationSucceededWithApps:(NSArray<PXTargetApp *> *)apps {
    self.allApps = [apps copy] ?: @[];
    self.viewState = self.allApps.count > 0 ? PXTargetAppsViewStateReady : PXTargetAppsViewStateNoEligibleApps;
    [self rebuildVisibleApps];
}

- (void)handleLocalAppEnumerationFailure {
    self.viewState = PXTargetAppsViewStateEnumerationFailure;
    [self.tableView reloadData];
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, PXLocalizedString(@"image.target_apps.failure.announcement"));
}

- (void)updateSearchResultsForSearchController:(UISearchController *)searchController {
    if (self.viewState == PXTargetAppsViewStateLoading || self.viewState == PXTargetAppsViewStateEnumerationFailure) {
        return;
    }
    [self rebuildVisibleApps];
}

- (void)rebuildVisibleApps {
    NSString *query = [self.searchController.searchBar.text stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];
    NSArray<PXTargetApp *> *matchingApps = self.allApps;
    if (query.length > 0) {
        NSPredicate *predicate = [NSPredicate predicateWithBlock:^BOOL(PXTargetApp *app, NSDictionary<NSString *, id> *bindings) {
            return [app.displayName localizedCaseInsensitiveContainsString:query] || [app.bundleIdentifier localizedCaseInsensitiveContainsString:query];
        }];
        matchingApps = [matchingApps filteredArrayUsingPredicate:predicate];
    }
    self.visibleUserApps = [matchingApps filteredArrayUsingPredicate:[NSPredicate predicateWithBlock:^BOOL(PXTargetApp *app, NSDictionary<NSString *, id> *bindings) {
        (void)bindings;
        return !app.isSystemApp && !app.isSafariTarget;
    }]];
    self.visibleSystemApps = [matchingApps filteredArrayUsingPredicate:[NSPredicate predicateWithBlock:^BOOL(PXTargetApp *app, NSDictionary<NSString *, id> *bindings) {
        (void)bindings;
        return app.isSystemApp || app.isSafariTarget;
    }]];
    NSMutableArray<NSArray<PXTargetApp *> *> *sections = [NSMutableArray array];
    NSMutableArray<NSString *> *titleKeys = [NSMutableArray array];
    if (self.visibleUserApps.count > 0) {
        [sections addObject:self.visibleUserApps];
        [titleKeys addObject:@"image.target_apps.section.user"];
    }
    if (self.visibleSystemApps.count > 0) {
        [sections addObject:self.visibleSystemApps];
        [titleKeys addObject:@"image.target_apps.section.system"];
    }
    self.visibleSections = [sections copy];
    self.visibleSectionTitleKeys = [titleKeys copy];
    if (matchingApps.count == 0) {
        self.viewState = query.length > 0 ? PXTargetAppsViewStateSearchEmpty : PXTargetAppsViewStateNoEligibleApps;
    } else {
        self.viewState = PXTargetAppsViewStateReady;
    }
    [self.tableView reloadData];
}

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return self.viewState == PXTargetAppsViewStateReady ? self.visibleSections.count : 1;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    if (self.viewState != PXTargetAppsViewStateReady) {
        return 1;
    }
    return self.visibleSections[(NSUInteger)section].count;
}

- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section {
    if (self.viewState != PXTargetAppsViewStateReady) {
        return nil;
    }
    return PXLocalizedString(self.visibleSectionTitleKeys[(NSUInteger)section]);
}

- (NSString *)tableView:(UITableView *)tableView titleForFooterInSection:(NSInteger)section {
    if (self.viewState != PXTargetAppsViewStateReady ||
        section == self.visibleSections.count - 1) {
        return PXLocalizedFormat(@"image.target_apps.selection_summary", (long)self.selectedBundleIdentifiers.count);
    }
    return nil;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    if (self.viewState != PXTargetAppsViewStateReady) {
        return [self stateCellForTableView:tableView];
    }
    PXTargetApp *app = [self appForIndexPath:indexPath];
    static NSString *const reuseIdentifier = @"ImageTargetAppCell";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:reuseIdentifier];
    if (!cell) {
        cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:reuseIdentifier];
        cell.textLabel.adjustsFontForContentSizeCategory = YES;
        cell.detailTextLabel.adjustsFontForContentSizeCategory = YES;
        cell.detailTextLabel.numberOfLines = 2;
    }
    BOOL isSelected = [self.selectedBundleIdentifiers containsObject:app.bundleIdentifier];
    UIListContentConfiguration *content = [UIListContentConfiguration subtitleCellConfiguration];
    content.text = app.isSafariTarget
        ? PXLocalizedString(@"image.target_apps.safari.title")
        : app.displayName;
    content.secondaryText = app.isSafariTarget
        ? [self detailTextForSafari]
        : [self detailTextForApp:app];
    content.image = app.icon ?: [UIImage systemImageNamed:app.isSafariTarget ? @"safari.fill" : @"app.fill"];
    content.imageProperties.maximumSize = CGSizeMake(40.0, 40.0);
    content.imageProperties.cornerRadius = 9.0;
    content.imageProperties.tintColor = app.isSafariTarget
        ? [self colorForSafariReadiness]
        : UIColor.systemBlueColor;
    content.textProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleBody];
    content.secondaryTextProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleFootnote];
    cell.contentConfiguration = content;
    cell.selectionStyle = UITableViewCellSelectionStyleDefault;
    cell.accessoryType = app.isSafariTarget && ![self isSafariReady]
        ? UITableViewCellAccessoryNone
        : (isSelected ? UITableViewCellAccessoryCheckmark : UITableViewCellAccessoryNone);
    cell.accessoryView = app.isSafariTarget && ![self isSafariReady]
        ? [self safariReadinessAccessoryView]
        : nil;
    cell.accessibilityIdentifier = [@"image-target-app-" stringByAppendingString:app.bundleIdentifier];
    cell.accessibilityLabel = PXLocalizedFormat(@"accessibility.settings.row", content.text, content.secondaryText);
    cell.accessibilityValue = app.isSafariTarget
        ? [self accessibilityValueForSafariSelected:isSelected]
        : (isSelected ? PXLocalizedString(@"accessibility.selected") : PXLocalizedString(@"accessibility.not_selected"));
    cell.accessibilityHint = app.isSafariTarget && ![self isSafariReady]
        ? PXLocalizedString(@"image.target_apps.safari.not_ready.hint")
        : PXLocalizedString(@"image.target_apps.selection_hint");
    cell.accessibilityTraits = UIAccessibilityTraitButton | (isSelected ? UIAccessibilityTraitSelected : 0);
    return cell;
}

- (UITableViewCell *)stateCellForTableView:(UITableView *)tableView {
    static NSString *const reuseIdentifier = @"ImageTargetAppsStateCell";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:reuseIdentifier];
    if (!cell) {
        cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:reuseIdentifier];
        cell.textLabel.adjustsFontForContentSizeCategory = YES;
        cell.detailTextLabel.adjustsFontForContentSizeCategory = YES;
        cell.detailTextLabel.numberOfLines = 0;
    }
    UIListContentConfiguration *content = [UIListContentConfiguration subtitleCellConfiguration];
    cell.selectionStyle = UITableViewCellSelectionStyleNone;
    cell.accessoryType = UITableViewCellAccessoryNone;
    cell.accessoryView = nil;
    cell.accessibilityTraits = UIAccessibilityTraitStaticText;
    if (self.viewState == PXTargetAppsViewStateLoading) {
        content.text = PXLocalizedString(@"image.target_apps.loading.title");
        content.secondaryText = PXLocalizedString(@"image.target_apps.loading.message");
        content.image = [UIImage systemImageNamed:@"arrow.triangle.2.circlepath"];
        UIActivityIndicatorView *indicator = [[UIActivityIndicatorView alloc] initWithActivityIndicatorStyle:UIActivityIndicatorViewStyleMedium];
        [indicator startAnimating];
        cell.accessoryView = indicator;
        cell.accessibilityValue = PXLocalizedString(@"home.accessibility.processing");
    } else if (self.viewState == PXTargetAppsViewStateSearchEmpty) {
        content.text = PXLocalizedString(@"image.target_apps.search_empty.title");
        content.secondaryText = PXLocalizedString(@"image.target_apps.search_empty.message");
        content.image = [UIImage systemImageNamed:@"magnifyingglass"];
    } else if (self.viewState == PXTargetAppsViewStateNoEligibleApps) {
        content.text = PXLocalizedString(@"image.target_apps.empty.title");
        content.secondaryText = PXLocalizedString(@"image.target_apps.empty.message");
        content.image = [UIImage systemImageNamed:@"app.dashed"];
    } else {
        content.text = PXLocalizedString(@"image.target_apps.failure.title");
        content.secondaryText = PXLocalizedString(@"image.target_apps.failure.message");
        content.image = [UIImage systemImageNamed:@"exclamationmark.triangle"];
        cell.selectionStyle = UITableViewCellSelectionStyleDefault;
        cell.accessibilityTraits = UIAccessibilityTraitButton;
        cell.accessibilityHint = PXLocalizedString(@"image.target_apps.failure.retry_hint");
    }
    content.imageProperties.tintColor = UIColor.systemBlueColor;
    content.textProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleBody];
    content.secondaryTextProperties.font = [UIFont preferredFontForTextStyle:UIFontTextStyleSubheadline];
    cell.contentConfiguration = content;
    cell.accessibilityLabel = PXLocalizedFormat(@"accessibility.state", content.text, content.secondaryText);
    return cell;
}

- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    if (self.viewState == PXTargetAppsViewStateEnumerationFailure) {
        [self loadLocalApps];
        return;
    }
    if (self.viewState != PXTargetAppsViewStateReady) {
        return;
    }
    PXTargetApp *app = [self appForIndexPath:indexPath];
    if (app.isSafariTarget) {
        [self handleSafariSelectionForApp:app];
        return;
    }
    [self toggleSelectionForApp:app];
}

- (PXTargetApp *)appForIndexPath:(NSIndexPath *)indexPath {
    return self.visibleSections[(NSUInteger)indexPath.section][(NSUInteger)indexPath.row];
}

- (void)refreshSafariReadiness {
    PXSafariTargetReadiness *readiness = [self.safariReadinessProvider currentSafariTargetReadiness];
    self.safariReadiness = readiness ?: [[PXSafariTargetReadiness alloc]
        initWithState:PXSafariTargetReadinessStateUnknown];
}

- (BOOL)isSafariReady {
    return self.safariReadiness.state == PXSafariTargetReadinessStateReady;
}

- (void)handleSafariSelectionForApp:(PXTargetApp *)app {
    BOOL isSelected = [self.selectedBundleIdentifiers containsObject:app.bundleIdentifier];
    if (isSelected) {
        [self toggleSelectionForApp:app];
        return;
    }
    if (![self isSafariReady]) {
        [self presentSafariNotReadyExplanation];
        return;
    }
    [self presentSafariSelectionExplanationForApp:app];
}

- (void)presentSafariNotReadyExplanation {
    UIAlertController *alert = [UIAlertController
        alertControllerWithTitle:[self titleForSafariReadiness]
        message:[self detailForSafariReadiness]
        preferredStyle:UIAlertControllerStyleAlert];
    [alert addAction:[UIAlertAction actionWithTitle:PXLocalizedString(@"navigation.close")
                                             style:UIAlertActionStyleCancel
                                           handler:nil]];
    [alert addAction:[UIAlertAction
        actionWithTitle:PXLocalizedString(@"image.target_apps.safari.not_ready.recovery")
                  style:UIAlertActionStyleDefault
                handler:^(UIAlertAction *action) {
                    (void)action;
                    [self handleSafariReadinessRefresh];
                }]];
    [self presentViewController:alert animated:YES completion:nil];
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification,
                                    PXLocalizedString(@"image.target_apps.safari.not_ready.announcement"));
}

- (void)handleSafariReadinessRefresh {
    [self refreshSafariReadiness];
    [self.tableView reloadData];
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification,
                                    [self titleForSafariReadiness]);
}

- (void)presentSafariSelectionExplanationForApp:(PXTargetApp *)app {
    UIAlertController *alert = [UIAlertController
        alertControllerWithTitle:PXLocalizedString(@"image.target_apps.safari.confirmation.title")
        message:PXLocalizedString(@"image.target_apps.safari.confirmation.message")
        preferredStyle:UIAlertControllerStyleAlert];
    [alert addAction:[UIAlertAction actionWithTitle:PXLocalizedString(@"navigation.cancel")
                                             style:UIAlertActionStyleCancel
                                           handler:nil]];
    [alert addAction:[UIAlertAction
        actionWithTitle:PXLocalizedString(@"image.target_apps.safari.confirmation.action")
                  style:UIAlertActionStyleDefault
                handler:^(UIAlertAction *action) {
                    (void)action;
                    [self handleConfirmedSafariSelectionForApp:app];
                }]];
    [self presentViewController:alert animated:YES completion:nil];
}

- (void)handleConfirmedSafariSelectionForApp:(PXTargetApp *)app {
    [self toggleSelectionForApp:app];
}

- (void)toggleSelectionForApp:(PXTargetApp *)app {
    BOOL wasSelected = [self.selectedBundleIdentifiers containsObject:app.bundleIdentifier];
    NSError *persistenceError = nil;
    if (![[IdentifierManager sharedManager]
        setApplicationInScope:app.bundleIdentifier
        enabled:!wasSelected
        error:&persistenceError]) {
        [self.tableView reloadData];
        NSLog(@"[ProjectX] Target App selection persistence failed: %@",
              persistenceError.localizedDescription);
        UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification,
                                        PXLocalizedString(@"image.target_apps.persistence_failed.announcement"));
        UIAlertController *alert = [UIAlertController
            alertControllerWithTitle:PXLocalizedString(@"image.target_apps.persistence_failed.title")
            message:PXLocalizedString(@"image.target_apps.persistence_failed.message")
            preferredStyle:UIAlertControllerStyleAlert];
        [alert addAction:[UIAlertAction actionWithTitle:PXLocalizedString(@"navigation.close")
                                                style:UIAlertActionStyleCancel
                                              handler:nil]];
        [self presentViewController:alert animated:YES completion:nil];
        return;
    }
    if (wasSelected) {
        [self.selectedBundleIdentifiers removeObject:app.bundleIdentifier];
    } else {
        [self.selectedBundleIdentifiers addObject:app.bundleIdentifier];
    }
    if (self.selectionCompletion) {
        self.selectionCompletion([self.selectedBundleIdentifiers copy]);
    }
    [self.tableView reloadData];
    UIAccessibilityPostNotification(UIAccessibilityAnnouncementNotification, wasSelected
        ? PXLocalizedString(@"image.target_apps.deselected_announcement")
        : PXLocalizedString(@"image.target_apps.selected_announcement"));
}

- (NSString *)detailTextForApp:(PXTargetApp *)app {
    if (app.eligibleExtensionCount == 1) {
        return PXLocalizedFormat(@"image.target_apps.extension_one", app.bundleIdentifier);
    }
    if (app.eligibleExtensionCount > 1) {
        return PXLocalizedFormat(@"image.target_apps.extension_count", app.bundleIdentifier, (long)app.eligibleExtensionCount);
    }
    return app.bundleIdentifier;
}

- (NSString *)detailTextForSafari {
    return PXLocalizedFormat(@"image.target_apps.safari.detail_format",
        PXLocalizedString(@"image.target_apps.safari.identity"),
        [self titleForSafariReadiness]);
}

- (NSString *)titleForSafariReadiness {
    switch (self.safariReadiness.state) {
        case PXSafariTargetReadinessStateReady:
            return PXLocalizedString(@"image.target_apps.safari.ready.title");
        case PXSafariTargetReadinessStateInjectionUnavailable:
            return PXLocalizedString(@"image.target_apps.safari.injection_unavailable.title");
        case PXSafariTargetReadinessStateWebKitAttributionUnavailable:
            return PXLocalizedString(@"image.target_apps.safari.webkit_unavailable.title");
        case PXSafariTargetReadinessStateSafariLibraryAccessUnavailable:
            return PXLocalizedString(@"image.target_apps.safari.library_unavailable.title");
        case PXSafariTargetReadinessStateCleanupPartiallyFailed:
            return PXLocalizedString(@"image.target_apps.safari.cleanup_partial.title");
        case PXSafariTargetReadinessStateActiveGenerationMismatch:
            return PXLocalizedString(@"image.target_apps.safari.generation_mismatch.title");
        case PXSafariTargetReadinessStateUnknown:
            return PXLocalizedString(@"image.target_apps.safari.unknown.title");
    }
}

- (NSString *)detailForSafariReadiness {
    switch (self.safariReadiness.state) {
        case PXSafariTargetReadinessStateReady:
            return PXLocalizedString(@"image.target_apps.safari.ready.detail");
        case PXSafariTargetReadinessStateInjectionUnavailable:
            return PXLocalizedString(@"image.target_apps.safari.injection_unavailable.detail");
        case PXSafariTargetReadinessStateWebKitAttributionUnavailable:
            return PXLocalizedString(@"image.target_apps.safari.webkit_unavailable.detail");
        case PXSafariTargetReadinessStateSafariLibraryAccessUnavailable:
            return PXLocalizedString(@"image.target_apps.safari.library_unavailable.detail");
        case PXSafariTargetReadinessStateCleanupPartiallyFailed:
            return PXLocalizedString(@"image.target_apps.safari.cleanup_partial.detail");
        case PXSafariTargetReadinessStateActiveGenerationMismatch:
            return PXLocalizedString(@"image.target_apps.safari.generation_mismatch.detail");
        case PXSafariTargetReadinessStateUnknown:
            return PXLocalizedString(@"image.target_apps.safari.unknown.detail");
    }
}

- (UIColor *)colorForSafariReadiness {
    switch (self.safariReadiness.state) {
        case PXSafariTargetReadinessStateReady:
            return UIColor.systemGreenColor;
        case PXSafariTargetReadinessStateUnknown:
            return UIColor.systemBlueColor;
        case PXSafariTargetReadinessStateInjectionUnavailable:
        case PXSafariTargetReadinessStateWebKitAttributionUnavailable:
        case PXSafariTargetReadinessStateSafariLibraryAccessUnavailable:
        case PXSafariTargetReadinessStateCleanupPartiallyFailed:
        case PXSafariTargetReadinessStateActiveGenerationMismatch:
            return UIColor.systemOrangeColor;
    }
}

- (UIImageView *)safariReadinessAccessoryView {
    UIImageView *accessory = [[UIImageView alloc] initWithImage:[UIImage
        systemImageNamed:self.safariReadiness.state == PXSafariTargetReadinessStateUnknown
            ? @"questionmark.circle.fill"
            : @"exclamationmark.triangle.fill"]];
    accessory.tintColor = [self colorForSafariReadiness];
    accessory.frame = CGRectMake(0.0, 0.0, 24.0, 24.0);
    accessory.isAccessibilityElement = NO;
    return accessory;
}

- (NSString *)accessibilityValueForSafariSelected:(BOOL)isSelected {
    NSString *selection = isSelected
        ? PXLocalizedString(@"accessibility.selected")
        : PXLocalizedString(@"accessibility.not_selected");
    return PXLocalizedFormat(@"image.target_apps.safari.accessibility.value",
        selection,
        [self titleForSafariReadiness]);
}

@end
