// DESIGN SPEC — generated by Designer agent // Coder: implement specified behavior, do not change component structure or accessibility attributes
#import <UIKit/UIKit.h>

#import "PXSafariTargetReadiness.h"
#import "PXTargetSelectionReconciler.h"

NS_ASSUME_NONNULL_BEGIN

typedef void (^PXTargetAppsSelectionCompletion)(NSSet<NSString *> *selectedBundleIdentifiers);

@interface PXTargetAppsViewController : UIViewController

- (instancetype)initWithSelectedBundleIdentifiers:(NSSet<NSString *> *)selectedBundleIdentifiers
                                         completion:(PXTargetAppsSelectionCompletion)completion;

- (instancetype)initWithSelectedBundleIdentifiers:(NSSet<NSString *> *)selectedBundleIdentifiers
                                         completion:(PXTargetAppsSelectionCompletion)completion
                           safariReadinessProvider:(id<PXSafariTargetReadinessProviding>)safariReadinessProvider;

- (instancetype)initWithSelectedBundleIdentifiers:(NSSet<NSString *> *)selectedBundleIdentifiers
                                         completion:(PXTargetAppsSelectionCompletion)completion
                           safariReadinessProvider:(id<PXSafariTargetReadinessProviding>)safariReadinessProvider
                         targetSelectionReconciler:(PXTargetSelectionReconciler *)targetSelectionReconciler NS_DESIGNATED_INITIALIZER;

- (instancetype)initWithNibName:(nullable NSString *)nibNameOrNil
                          bundle:(nullable NSBundle *)nibBundleOrNil NS_UNAVAILABLE;
- (instancetype)initWithCoder:(NSCoder *)coder NS_UNAVAILABLE;

@end

NS_ASSUME_NONNULL_END
