// DESIGN SPEC — generated by Designer agent // Coder: implement TODO items, do not change component structure or accessibility attributes
#import <UIKit/UIKit.h>

@interface TabBarController : UITabBarController

- (void)showHomeForDeepLink;

// Compatibility selectors for legacy, non-primary callers. Neither presents account or support UI.
- (void)switchToAccountTab;
- (void)updateNotificationBadge;

@end
