// DESIGN SPEC — generated by Designer agent // Preserve the single-screen direct-use shell.
#import "TabBarController.h"
#import "ProjectXViewController.h"

@implementation TabBarController

- (void)viewDidLoad {
    [super viewDidLoad];

    ProjectXViewController *homeViewController = [[ProjectXViewController alloc] init];
    UINavigationController *homeNavigationController = [[UINavigationController alloc] initWithRootViewController:homeViewController];
    homeNavigationController.navigationBar.prefersLargeTitles = NO;
    homeNavigationController.navigationBar.accessibilityIdentifier = @"home-navigation";

    self.viewControllers = @[homeNavigationController];
    self.selectedViewController = homeNavigationController;
    self.tabBar.hidden = YES;
    self.tabBar.userInteractionEnabled = NO;
    self.tabBar.accessibilityElementsHidden = YES;
}

- (void)showHomeForDeepLink {
    UINavigationController *homeNavigationController = [self homeNavigationController];
    [homeNavigationController dismissViewControllerAnimated:NO completion:nil];
    [homeNavigationController popToRootViewControllerAnimated:NO];
    self.selectedViewController = homeNavigationController;
}

- (UINavigationController *)homeNavigationController {
    UIViewController *selectedViewController = self.selectedViewController ?: self.viewControllers.firstObject;
    if ([selectedViewController isKindOfClass:[UINavigationController class]]) {
        return (UINavigationController *)selectedViewController;
    }

    return nil;
}

- (void)switchToAccountTab {
    // Account presentation is intentionally unavailable in the direct-use shell.
}

- (void)updateNotificationBadge {
    // Support is intentionally unavailable in the single-screen primary experience.
}

@end
