#!/bin/sh

set -eu

LAUNCHCTL="/bin/launchctl"
LAUNCHDAEMON_LABEL="com.hydra.weaponx.guardian"

if [ -x "$LAUNCHCTL" ]; then
    "$LAUNCHCTL" bootout "system/$LAUNCHDAEMON_LABEL" 2>/dev/null || true
fi

exit 0
